#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=external_MAGs_TBLASTN
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=20G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail
shopt -s nullglob

# DESCRIPTION
# Searches protein sequences from conserved EET gene cassettes against an
# external MAG nucleotide dataset using TBLASTN from BLAST+ v2.14.1.
#
# Identity and query-coverage thresholds are applied downstream by
# 04_call_credible_EET_cassettes_from_TBLASTN.py.
#
# INPUT
# 1. Protein FASTA generated by 01_translate_EET_CDS_to_proteins.py.
# 2. Directory containing one external MAG nucleotide FASTA per genome.
# 3. Dataset label, for example SPRUCE or STORDALEN.
# 4. Output directory.
#
# OUTPUT
# Concatenated target FASTA, nucleotide BLAST database and raw TBLASTN table.
#
# USAGE
# sbatch 02_run_TBLASTN_external_MAGs.sh \
#   EET_query_proteins.faa \
#   external_MAG_directory \
#   SPRUCE \
#   SPRUCE_TBLASTN

if [[ $# -ne 4 ]]; then
    echo "Usage: sbatch $0 <query.faa> <MAG_directory> <dataset_label> <output_dir>" >&2
    exit 1
fi

QUERY_FASTA="$1"
MAG_DIR="$2"
DATASET="$3"
OUTPUT_DIR="$4"

THREADS="${SLURM_CPUS_PER_TASK:-16}"

if [[ ! -s "$QUERY_FASTA" ]]; then
    echo "ERROR: Protein query FASTA was not found or is empty: $QUERY_FASTA" >&2
    exit 1
fi

if [[ ! -d "$MAG_DIR" ]]; then
    echo "ERROR: MAG directory does not exist: $MAG_DIR" >&2
    exit 1
fi

if [[ -z "$DATASET" ]]; then
    echo "ERROR: Dataset label cannot be empty." >&2
    exit 1
fi

if [[ -e "$OUTPUT_DIR" ]] && [[ -n "$(find "$OUTPUT_DIR" -mindepth 1 -print -quit 2>/dev/null)" ]]; then
    echo "ERROR: Output directory already exists and is not empty: $OUTPUT_DIR" >&2
    exit 1
fi

MAG_FASTAS=(
    "$MAG_DIR"/*.fna
    "$MAG_DIR"/*.fa
    "$MAG_DIR"/*.fasta
)

if [[ ${#MAG_FASTAS[@]} -eq 0 ]]; then
    echo "ERROR: No uncompressed MAG FASTA files were found in: $MAG_DIR" >&2
    exit 1
fi

if ! command -v makeblastdb >/dev/null 2>&1 \
    || ! command -v tblastn >/dev/null 2>&1; then

    if command -v module >/dev/null 2>&1; then
        module load stack/2024-06
        module load gcc/12.2.0
        module load blast-plus/2.14.1
    fi
fi

if ! command -v makeblastdb >/dev/null 2>&1; then
    echo "ERROR: makeblastdb was not found in PATH." >&2
    exit 1
fi

if ! command -v tblastn >/dev/null 2>&1; then
    echo "ERROR: tblastn was not found in PATH." >&2
    exit 1
fi

FASTA_DIR="${OUTPUT_DIR}/database_fasta"
DB_DIR="${OUTPUT_DIR}/blast_database"
RAW_DIR="${OUTPUT_DIR}/raw_hits"

mkdir -p "$FASTA_DIR" "$DB_DIR" "$RAW_DIR"

COMBINED_FASTA="${FASTA_DIR}/${DATASET}_all_MAGs.fna"
CONTIG_IDS="${FASTA_DIR}/${DATASET}_contig_ids.txt"
DUPLICATE_IDS="${FASTA_DIR}/${DATASET}_duplicate_contig_ids.txt"
DB_PREFIX="${DB_DIR}/${DATASET}_MAGs"
TBLASTN_OUTPUT="${RAW_DIR}/${DATASET}_EET_proteins_TBLASTN.tsv"

printf '%s\n' "${MAG_FASTAS[@]}" \
    | sort \
    | while IFS= read -r FASTA; do
        cat "$FASTA"
    done \
    > "$COMBINED_FASTA"

if [[ ! -s "$COMBINED_FASTA" ]]; then
    echo "ERROR: Combined target FASTA was not generated." >&2
    exit 1
fi

grep '^>' "$COMBINED_FASTA" \
    | sed 's/^>//' \
    | awk '{print $1}' \
    > "$CONTIG_IDS"

N_CONTIGS="$(wc -l < "$CONTIG_IDS" | tr -d ' ')"

if [[ "$N_CONTIGS" -eq 0 ]]; then
    echo "ERROR: No target contig identifiers were found." >&2
    exit 1
fi

sort "$CONTIG_IDS" | uniq -d > "$DUPLICATE_IDS"

if [[ -s "$DUPLICATE_IDS" ]]; then
    echo "ERROR: Duplicate contig identifiers were found across MAG files." >&2
    head -20 "$DUPLICATE_IDS" >&2
    exit 1
fi

N_QUERIES="$(grep -c '^>' "$QUERY_FASTA" || true)"

if [[ "$N_QUERIES" -eq 0 ]]; then
    echo "ERROR: No protein query sequences were found." >&2
    exit 1
fi

echo "============================================================"
echo "Running external-dataset TBLASTN search"
echo "Dataset: $DATASET"
echo "Query proteins: $N_QUERIES"
echo "MAG files: ${#MAG_FASTAS[@]}"
echo "Target contigs: $N_CONTIGS"
echo "Output: $TBLASTN_OUTPUT"
echo "============================================================"

makeblastdb \
    -in "$COMBINED_FASTA" \
    -dbtype nucl \
    -parse_seqids \
    -out "$DB_PREFIX"

tblastn \
    -query "$QUERY_FASTA" \
    -db "$DB_PREFIX" \
    -out "$TBLASTN_OUTPUT" \
    -evalue 1e-10 \
    -max_target_seqs 5000 \
    -num_threads "$THREADS" \
    -seg yes \
    -comp_based_stats 2 \
    -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen"

if [[ ! -f "$TBLASTN_OUTPUT" ]]; then
    echo "ERROR: TBLASTN output was not created." >&2
    exit 1
fi

N_HITS="$(wc -l < "$TBLASTN_OUTPUT" | tr -d ' ')"

echo "============================================================"
echo "TBLASTN completed successfully."
echo "Raw HSPs: $N_HITS"
echo "Output: $TBLASTN_OUTPUT"
echo "============================================================"
