#!/usr/bin/env python3

# DESCRIPTION
# Combines EET machinery expression with selected alternative-respiration
# modules and builds complete MAG-by-sample comparison tables.
#
# INPUT
# Analysis output directory containing:
#   EET_machinery_expression_by_MAG_sample.tsv
#     generated by 02_build_EET_expression_by_MAG_sample.py
#   selected_modules_expression_by_MAG_sample.tsv
#     generated by 01_build_sample_resolved_alternative_pathways.py
#
# OUTPUT
# Alternative-module universe, long EET-versus-respiration table,
# coexpression summary, MAG-level summary and QC files.
#
# USAGE
# python3 11_prepare_EET_vs_alternative_respiration.py \
#   analysis_output_directory

from pathlib import Path
import argparse
import sys

import numpy as np
import pandas as pd


OUT_DIR = None
EET_FILE = None
ALT_FILE = None

EET_EXPRESSION_COLUMN = "mean_gene_MT_coverage_per_cell"
ALT_EXPRESSION_COLUMN = "mean_MT_coverage_per_cell"


###############################################################################
# READ AND VALIDATE INPUTS
###############################################################################

def read_eet():
    required = {
        "MAG_name",
        "EET_group",
        "MetaT_sample",
        "n_EET_proteins",
        "n_EET_proteins_expressed",
        EET_EXPRESSION_COLUMN,
        "EET_machinery_is_expressed",
        "all_EET_components_expressed",
    }

    eet = pd.read_csv(EET_FILE, sep="\t", low_memory=False)

    missing = required - set(eet.columns)
    if missing:
        raise RuntimeError(
            f"Missing columns in {EET_FILE}: {sorted(missing)}"
        )

    eet["source_MAG_name"] = eet["MAG_name"].astype(str)
    eet["source_MetaT_sample"] = eet["MetaT_sample"].astype(str)

    eet[EET_EXPRESSION_COLUMN] = pd.to_numeric(
        eet[EET_EXPRESSION_COLUMN],
        errors="coerce",
    )

    if eet[EET_EXPRESSION_COLUMN].isna().any():
        bad = eet[eet[EET_EXPRESSION_COLUMN].isna()]
        bad.to_csv(
            OUT_DIR / "QC_non_numeric_EET_expression.tsv",
            sep="\t",
            index=False,
        )
        raise RuntimeError(
            "Non-numeric EET expression values found."
        )

    key = ["MAG_name", "EET_group", "MetaT_sample"]
    duplicates = eet[eet.duplicated(subset=key, keep=False)].sort_values(key)

    duplicates.to_csv(
        OUT_DIR / "QC_duplicated_EET_MAG_group_sample.tsv",
        sep="\t",
        index=False,
    )

    if not duplicates.empty:
        raise RuntimeError(
            "Duplicated MAG + EET_group + MetaT_sample rows in EET table."
        )

    return eet


def read_alternative_modules():
    required = {
        "MAG_name",
        "MetaT_sample",
        "metabolic_module",
        "analysis_class",
        "include_in_competing_respiration_test",
        "n_markers_detected",
        "n_markers_expressed",
        ALT_EXPRESSION_COLUMN,
        "module_is_expressed",
    }

    alt = pd.read_csv(ALT_FILE, sep="\t", low_memory=False)

    missing = required - set(alt.columns)
    if missing:
        raise RuntimeError(
            f"Missing columns in {ALT_FILE}: {sorted(missing)}"
        )

    alt["source_MAG_name"] = alt["MAG_name"].astype(str)
    alt["source_MetaT_sample"] = alt["MetaT_sample"].astype(str)

    alt["include_in_competing_respiration_test"] = (
        alt["include_in_competing_respiration_test"]
        .astype(str)
        .str.strip()
        .str.lower()
        .map({"true": True, "false": False})
    )

    if alt["include_in_competing_respiration_test"].isna().any():
        bad = alt[
            alt["include_in_competing_respiration_test"].isna()
        ]
        bad.to_csv(
            OUT_DIR / "QC_invalid_competing_respiration_flags.tsv",
            sep="\t",
            index=False,
        )
        raise RuntimeError(
            "Invalid include_in_competing_respiration_test values."
        )

    alt = alt[
        alt["include_in_competing_respiration_test"]
    ].copy()

    alt[ALT_EXPRESSION_COLUMN] = pd.to_numeric(
        alt[ALT_EXPRESSION_COLUMN],
        errors="coerce",
    )

    if alt[ALT_EXPRESSION_COLUMN].isna().any():
        bad = alt[alt[ALT_EXPRESSION_COLUMN].isna()]
        bad.to_csv(
            OUT_DIR / "QC_non_numeric_alternative_expression.tsv",
            sep="\t",
            index=False,
        )
        raise RuntimeError(
            "Non-numeric alternative-pathway expression values found."
        )

    key = ["MAG_name", "MetaT_sample", "metabolic_module"]
    duplicates = alt[alt.duplicated(subset=key, keep=False)].sort_values(key)

    duplicates.to_csv(
        OUT_DIR / "QC_duplicated_alternative_MAG_sample_module.tsv",
        sep="\t",
        index=False,
    )

    if not duplicates.empty:
        raise RuntimeError(
            "Duplicated MAG + MetaT_sample + metabolic_module rows "
            "in alternative-module table."
        )

    return alt


###############################################################################
# BUILD COMPLETE COMPARISON TABLES
###############################################################################

def build_module_universe(alt_subset):
    module_universe = (
        alt_subset
        .groupby(
            [
                "MAG_name",
                "metabolic_module",
                "analysis_class",
            ],
            as_index=False,
        )
        .agg(
            n_markers_detected_any_sample=(
                "n_markers_detected",
                "max",
            ),
            n_samples_with_module_row=(
                "MetaT_sample",
                "nunique",
            ),
            n_samples_module_expressed_observed=(
                "module_is_expressed",
                "sum",
            ),
        )
    )

    module_universe["module_represented_for_MAG"] = True

    module_universe.to_csv(
        OUT_DIR / "alternative_module_universe_by_MAG.tsv",
        sep="\t",
        index=False,
    )

    return module_universe


def build_complete_alt_grid(eet, alt_subset, module_universe):
    eet_keys = (
        eet[
            [
                "MAG_name",
                "EET_group",
                "MetaT_sample",
                "n_EET_proteins",
                "n_EET_proteins_expressed",
                EET_EXPRESSION_COLUMN,
                "EET_machinery_is_expressed",
                "all_EET_components_expressed",
            ]
        ]
        .drop_duplicates()
    )

    module_universe = module_universe[
        module_universe["MAG_name"].isin(eet["MAG_name"])
    ].copy()

    grid = eet_keys.merge(
        module_universe,
        on="MAG_name",
        how="inner",
        validate="many_to_many",
    )

    observed_columns = [
        "MAG_name",
        "MetaT_sample",
        "metabolic_module",
        "n_markers_detected",
        "n_markers_expressed",
        ALT_EXPRESSION_COLUMN,
        "module_is_expressed",
    ]

    observed = alt_subset[observed_columns].copy()

    merged = grid.merge(
        observed,
        on=["MAG_name", "MetaT_sample", "metabolic_module"],
        how="left",
        validate="one_to_one",
        indicator="alternative_row_merge_status",
    )

    merged["alternative_row_was_observed"] = (
        merged["alternative_row_merge_status"] == "both"
    )
    merged = merged.drop(columns="alternative_row_merge_status")

    for column in [
        "n_markers_detected",
        "n_markers_expressed",
        ALT_EXPRESSION_COLUMN,
    ]:
        merged[column] = pd.to_numeric(
            merged[column],
            errors="coerce",
        ).fillna(0)

    merged["module_is_expressed"] = (
        merged[ALT_EXPRESSION_COLUMN] > 0
    )

    merged = merged.rename(
        columns={
            EET_EXPRESSION_COLUMN: "EET_mean_gene_MT_coverage_per_cell",
            ALT_EXPRESSION_COLUMN: (
                "alternative_mean_MT_coverage_per_cell"
            ),
        }
    )

    merged["log1p_EET_expression"] = np.log1p(
        merged["EET_mean_gene_MT_coverage_per_cell"]
    )
    merged["log1p_alternative_expression"] = np.log1p(
        merged["alternative_mean_MT_coverage_per_cell"]
    )

    merged = merged.sort_values(
        [
            "EET_group",
            "MAG_name",
            "MetaT_sample",
            "metabolic_module",
        ]
    )

    merged.to_csv(
        OUT_DIR / "EET_vs_alternative_respiration_long.tsv",
        sep="\t",
        index=False,
    )

    return merged


def build_coexpression_summary(long_table):
    grouping = [
        "MAG_name",
        "EET_group",
        "MetaT_sample",
        "n_EET_proteins",
        "n_EET_proteins_expressed",
        "EET_mean_gene_MT_coverage_per_cell",
        "EET_machinery_is_expressed",
        "all_EET_components_expressed",
    ]

    summary = (
        long_table
        .groupby(grouping, as_index=False, dropna=False)
        .agg(
            n_alternative_modules_represented=(
                "metabolic_module",
                "nunique",
            ),
            n_alternative_modules_expressed=(
                "module_is_expressed",
                "sum",
            ),
            sum_alternative_mean_expression=(
                "alternative_mean_MT_coverage_per_cell",
                "sum",
            ),
            mean_alternative_module_expression=(
                "alternative_mean_MT_coverage_per_cell",
                "mean",
            ),
            median_alternative_module_expression=(
                "alternative_mean_MT_coverage_per_cell",
                "median",
            ),
        )
    )

    expressed_lists = (
        long_table[long_table["module_is_expressed"]]
        .groupby(
            ["MAG_name", "EET_group", "MetaT_sample"]
        )["metabolic_module"]
        .apply(lambda values: ";".join(sorted(set(values))))
        .rename("expressed_alternative_modules")
        .reset_index()
    )

    summary = summary.merge(
        expressed_lists,
        on=["MAG_name", "EET_group", "MetaT_sample"],
        how="left",
        validate="one_to_one",
    )

    summary["expressed_alternative_modules"] = (
        summary["expressed_alternative_modules"].fillna("")
    )

    summary["fraction_alternative_modules_expressed"] = (
        summary["n_alternative_modules_expressed"]
        / summary["n_alternative_modules_represented"]
    )

    summary.to_csv(
        OUT_DIR / "coexpressed_modules_by_MAG_sample.tsv",
        sep="\t",
        index=False,
    )

    return summary


def build_mag_summary(coexpression, module_universe):
    module_counts = (
        module_universe
        .groupby("MAG_name", as_index=False)
        .agg(
            n_alternative_modules_represented=(
                "metabolic_module",
                "nunique",
            ),
            alternative_modules_represented=(
                "metabolic_module",
                lambda values: ";".join(sorted(set(values))),
            ),
        )
    )

    mag_summary = (
        coexpression
        .groupby(["MAG_name", "EET_group"], as_index=False)
        .agg(
            n_MetaT_samples=("MetaT_sample", "nunique"),
            n_samples_with_EET_expression=(
                "EET_machinery_is_expressed",
                "sum",
            ),
            n_samples_with_any_alternative_module_expression=(
                "n_alternative_modules_expressed",
                lambda values: int((values > 0).sum()),
            ),
            median_n_alternative_modules_expressed=(
                "n_alternative_modules_expressed",
                "median",
            ),
            max_n_alternative_modules_expressed=(
                "n_alternative_modules_expressed",
                "max",
            ),
            mean_EET_expression=(
                "EET_mean_gene_MT_coverage_per_cell",
                "mean",
            ),
            mean_alternative_module_expression=(
                "mean_alternative_module_expression",
                "mean",
            ),
        )
    )

    mag_summary = mag_summary.merge(
        module_counts,
        on="MAG_name",
        how="left",
        validate="one_to_one",
    )

    mag_summary.to_csv(
        OUT_DIR / "alternative_respiration_summary_by_MAG.tsv",
        sep="\t",
        index=False,
    )

    return mag_summary



def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Prepare EET-versus-alternative-respiration comparison tables."
        )
    )
    parser.add_argument(
        "analysis_directory",
        type=Path,
    )
    return parser.parse_args()


###############################################################################
# MAIN
###############################################################################

def main():
    global OUT_DIR
    global EET_FILE
    global ALT_FILE

    args = parse_args()

    OUT_DIR = args.analysis_directory
    EET_FILE = OUT_DIR / "EET_machinery_expression_by_MAG_sample.tsv"
    ALT_FILE = OUT_DIR / "selected_modules_expression_by_MAG_sample.tsv"

    eet = read_eet()
    alt = read_alternative_modules()

    eet_mags = set(eet["MAG_name"])
    alt_subset = alt[alt["MAG_name"].isin(eet_mags)].copy()

    matched_alt_mags = set(alt_subset["MAG_name"])
    missing_alt_mags = sorted(eet_mags - matched_alt_mags)

    (
        OUT_DIR / "QC_EET_MAGs_without_competing_respiration_modules.txt"
    ).write_text(
        "\n".join(missing_alt_mags) + ("\n" if missing_alt_mags else "")
    )

    if missing_alt_mags:
        raise RuntimeError(
            f"{len(missing_alt_mags)} EET MAGs have no selected "
            "competing-respiration modules."
        )

    module_universe = build_module_universe(alt_subset)
    long_table = build_complete_alt_grid(
        eet,
        alt_subset,
        module_universe,
    )
    coexpression = build_coexpression_summary(long_table)
    mag_summary = build_mag_summary(
        coexpression,
        module_universe[
            module_universe["MAG_name"].isin(eet_mags)
        ],
    )

    expected_coexpression_rows = (
        eet[
            ["MAG_name", "EET_group", "MetaT_sample"]
        ]
        .drop_duplicates()
        .shape[0]
    )
    if len(coexpression) != expected_coexpression_rows:
        raise RuntimeError(
            f"Expected {expected_coexpression_rows} MAG-sample rows in "
            f"coexpression summary, found {len(coexpression)}."
        )

    n_eet_expressed = int(
        coexpression["EET_machinery_is_expressed"].sum()
    )
    n_alt_expressed = int(
        (coexpression["n_alternative_modules_expressed"] > 0).sum()
    )
    n_both_expressed = int(
        (
            coexpression["EET_machinery_is_expressed"]
            & (coexpression["n_alternative_modules_expressed"] > 0)
        ).sum()
    )

    qc_lines = [
        f"EET MAGs in comparison: {eet['MAG_name'].nunique()}",
        f"EET groups in comparison: {eet['EET_group'].nunique()}",
        f"MetaT samples in comparison: {eet['MetaT_sample'].nunique()}",
        (
            "Alternative modules retained: "
            f"{module_universe['metabolic_module'].nunique()}"
        ),
        (
            "MAG-module combinations represented: "
            f"{len(module_universe)}"
        ),
        f"Long comparison rows: {len(long_table)}",
        f"MAG-sample coexpression rows: {len(coexpression)}",
        f"MAG-level summary rows: {len(mag_summary)}",
        (
            "MAG-sample rows with detectable EET expression: "
            f"{n_eet_expressed}"
        ),
        (
            "MAG-sample rows with at least one expressed alternative module: "
            f"{n_alt_expressed}"
        ),
        (
            "MAG-sample rows with both EET and at least one alternative "
            f"module expressed: {n_both_expressed}"
        ),
    ]

    (
        OUT_DIR / "QC_EET_vs_alternative_respiration_summary.txt"
    ).write_text(
        "\n".join(qc_lines) + "\n"
    )

    print("\n[COMPLETED]")
    for line in qc_lines:
        print(f"  {line}")

    print(f"\nOutputs written to:\n  {OUT_DIR}")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"\n[ERROR] {error}", file=sys.stderr)
        sys.exit(1)