#!/bin/bash

set -euo pipefail

# DESCRIPTION
# Predicts the subcellular localization of candidate multiheme cytochromes
# using the Gram-negative, Gram-positive and archaeal models of PSORTb v3.0.
#
# The main model used for this study is --negative
# --positive and --archaea were additionally used for screening protein localization of electroactive reference microbes
#
# INPUT
# A directory containing one or more taxonomy-specific protein FASTA files:
#   MHC.negative.cleaned.faa
#   MHC.positive.cleaned.faa
#   MHC.archaea.cleaned.faa
#
# Generated by:
# scripts/analyses/05_MHC_detection_clustering_and_scoring/
# 01_identify_putative_MHCs.py
#
# OUTPUT
# Separate PSORTb terse-format results and log files for each available
# organism type.
#
# USAGE
# bash 02_predict_MHC_subcellular_localization_psortb.sh \
#   input_directory \
#   output_directory \
#   path/to/psortb_app \
#   path/to/psortb.sif

###############################################################################
# ARGUMENTS
###############################################################################

if [[ $# -ne 4 ]]; then
    echo "Usage:" >&2
    echo "  bash $0 <input_dir> <output_dir> <psortb_app> <psortb.sif>" >&2
    exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"
PSORTB_APP="$3"
PSORTB_SIF="$4"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$INPUT_DIR" ]]; then
    echo "ERROR: Input directory not found: $INPUT_DIR" >&2
    exit 1
fi

if [[ ! -x "$PSORTB_APP" ]]; then
    echo "ERROR: PSORTb application was not found or is not executable:" >&2
    echo "$PSORTB_APP" >&2
    exit 1
fi

if [[ ! -s "$PSORTB_SIF" ]]; then
    echo "ERROR: PSORTb container was not found or is empty:" >&2
    echo "$PSORTB_SIF" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# FUNCTION: RUN PSORTB
###############################################################################

run_psortb() {

    local organism_type="$1"
    local mode_flag="$2"

    local input_fasta="${INPUT_DIR}/MHC.${organism_type}.cleaned.faa"
    local type_output="${OUTPUT_DIR}/${organism_type}"
    local direct_output="${type_output}/psortb_direct"
    local terse_output="${type_output}/psortb_${organism_type}.terse.txt"
    local log_file="${type_output}/psortb_${organism_type}.log"

    if [[ ! -s "$input_fasta" ]]; then
        echo "Input not available; skipping ${organism_type}: $input_fasta"
        return 0
    fi

    mkdir -p "$direct_output"

    if [[ -e "$terse_output" ]]; then
        echo "ERROR: Output already exists: $terse_output" >&2
        exit 1
    fi

    echo "============================================================"
    echo "Running PSORTb"
    echo "Organism type: $organism_type"
    echo "PSORTb model: $mode_flag"
    echo "Input: $input_fasta"
    echo "Output: $terse_output"
    echo "============================================================"

    "$PSORTB_APP" \
        -s "$PSORTB_SIF" \
        -i "$input_fasta" \
        -r "$direct_output" \
        "$mode_flag" \
        -o terse \
        > "$terse_output" \
        2> "$log_file"

    if [[ ! -s "$terse_output" ]]; then
        echo "ERROR: PSORTb output was not generated for $organism_type." >&2
        exit 1
    fi

    echo "PSORTb completed: $organism_type"
}

###############################################################################
# RUN AVAILABLE PSORTB MODELS
###############################################################################

AVAILABLE_INPUTS=0

for input_file in \
    "${INPUT_DIR}/MHC.negative.cleaned.faa" \
    "${INPUT_DIR}/MHC.positive.cleaned.faa" \
    "${INPUT_DIR}/MHC.archaea.cleaned.faa"
do
    if [[ -s "$input_file" ]]; then
        AVAILABLE_INPUTS=$((AVAILABLE_INPUTS + 1))
    fi
done

if [[ "$AVAILABLE_INPUTS" -eq 0 ]]; then
    echo "ERROR: No taxonomy-specific MHC FASTA files were found." >&2
    exit 1
fi

run_psortb "negative" "--negative"
run_psortb "positive" "--positive"
run_psortb "archaea" "--archaea"

echo "============================================================"
echo "PSORTb analyses completed successfully."
echo "Input categories processed: $AVAILABLE_INPUTS"
echo "Output directory: $OUTPUT_DIR"
echo "============================================================"
