#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=MHC_MMseqs2_clustering
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Clusters candidate MHC protein sequences from this study together with
# reference MHCs from Geobacter sulfurreducens PCA and Shewanella oneidensis
# MR-1 using MMseqs2 v14-7e284.
#
# INPUT
# A combined protein FASTA containing:
#   1. candidate MHCs identified in the metagenomic dataset;
#   2. 73 reference MHCs from Geobacter sulfurreducens PCA;
#   3. 23 reference MHCs from Shewanella oneidensis MR-1.
#
# Generated by:
# scripts/analyses/05_MHC_detection_clustering_and_scoring/
# 01_identify_putative_MHCs.py
#
# OUTPUT
# MMseqs2 cluster database, representative protein FASTA and a two-column
# table linking each cluster representative to its member proteins.
#
# USAGE
# sbatch 03_cluster_MHC_proteins_mmseqs2.sh \
#   combined_MHC_proteins.faa \
#   output_directory

###############################################################################
# ARGUMENTS
###############################################################################

if [[ $# -ne 2 ]]; then
    echo "Usage: sbatch $0 <combined_MHC_proteins.faa> <output_directory>" >&2
    exit 1
fi

INPUT_FASTA="$1"
OUTPUT_DIR="$2"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
MMSEQS_MODULE="${MMSEQS_MODULE:-mmseqs2/14-7e284}"

MIN_SEQUENCE_IDENTITY="0.50"
MIN_ALIGNMENT_COVERAGE="0.90"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -s "$INPUT_FASTA" ]]; then
    echo "ERROR: Input protein FASTA not found or empty: $INPUT_FASTA" >&2
    exit 1
fi

if [[ -e "$OUTPUT_DIR" ]] && [[ -n "$(find "$OUTPUT_DIR" -mindepth 1 -print -quit 2>/dev/null)" ]]; then
    echo "ERROR: Output directory already exists and is not empty:" >&2
    echo "$OUTPUT_DIR" >&2
    exit 1
fi

N_PROTEINS="$(grep -c '^>' "$INPUT_FASTA" || true)"

if [[ "$N_PROTEINS" -eq 0 ]]; then
    echo "ERROR: No protein FASTA records found in: $INPUT_FASTA" >&2
    exit 1
fi

N_UNIQUE_IDS="$(
    grep '^>' "$INPUT_FASTA" |
        sed 's/^>//' |
        awk '{print $1}' |
        sort -u |
        wc -l |
        tr -d ' '
)"

if [[ "$N_UNIQUE_IDS" -ne "$N_PROTEINS" ]]; then
    echo "ERROR: Duplicate protein identifiers were detected in the input FASTA." >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

if ! command -v mmseqs >/dev/null 2>&1; then

    if ! command -v module >/dev/null 2>&1; then
        echo "ERROR: MMseqs2 was not found and the module command is unavailable." >&2
        exit 1
    fi

    module load "$MMSEQS_MODULE"
fi

if ! command -v mmseqs >/dev/null 2>&1; then
    echo "ERROR: MMseqs2 could not be loaded." >&2
    exit 1
fi

###############################################################################
# OUTPUT PATHS
###############################################################################

mkdir -p "$OUTPUT_DIR"

INPUT_PREFIX="$(basename "$INPUT_FASTA")"
INPUT_PREFIX="${INPUT_PREFIX%.faa}"
INPUT_PREFIX="${INPUT_PREFIX%.fasta}"
INPUT_PREFIX="${INPUT_PREFIX%.fa}"

SEQUENCE_DATABASE="${OUTPUT_DIR}/${INPUT_PREFIX}.db"
CLUSTER_DATABASE="${OUTPUT_DIR}/${INPUT_PREFIX}.cluster.db"
REPRESENTATIVE_DATABASE="${OUTPUT_DIR}/${INPUT_PREFIX}.cluster_representatives.db"

REPRESENTATIVE_FASTA="${OUTPUT_DIR}/${INPUT_PREFIX}.cluster_representatives.faa"
CLUSTER_TABLE="${OUTPUT_DIR}/${INPUT_PREFIX}.cluster_membership.tsv"

TEMP_DIR="${OUTPUT_DIR}/tmp"

mkdir -p "$TEMP_DIR"

###############################################################################
# MMSEQS2 CLUSTERING
###############################################################################

echo "============================================================"
echo "Starting MMseqs2 clustering"
echo "Input proteins: $N_PROTEINS"
echo "Minimum sequence identity: $MIN_SEQUENCE_IDENTITY"
echo "Minimum alignment coverage: $MIN_ALIGNMENT_COVERAGE"
echo "Threads: $THREADS"
echo "Output directory: $OUTPUT_DIR"
echo "============================================================"

mmseqs createdb \
    "$INPUT_FASTA" \
    "$SEQUENCE_DATABASE"

mmseqs cluster \
    "$SEQUENCE_DATABASE" \
    "$CLUSTER_DATABASE" \
    "$TEMP_DIR" \
    --min-seq-id "$MIN_SEQUENCE_IDENTITY" \
    -c "$MIN_ALIGNMENT_COVERAGE" \
    --cluster-reassign \
    --threads "$THREADS"

###############################################################################
# REPRESENTATIVE SEQUENCES
###############################################################################

mmseqs createsubdb \
    "$CLUSTER_DATABASE" \
    "$SEQUENCE_DATABASE" \
    "$REPRESENTATIVE_DATABASE"

mmseqs convert2fasta \
    "$REPRESENTATIVE_DATABASE" \
    "$REPRESENTATIVE_FASTA"

###############################################################################
# CLUSTER MEMBERSHIP TABLE
###############################################################################

mmseqs createtsv \
    "$SEQUENCE_DATABASE" \
    "$SEQUENCE_DATABASE" \
    "$CLUSTER_DATABASE" \
    "$CLUSTER_TABLE" \
    --threads "$THREADS"

###############################################################################
# OUTPUT VALIDATION
###############################################################################

if [[ ! -s "$REPRESENTATIVE_FASTA" ]]; then
    echo "ERROR: Representative protein FASTA was not generated." >&2
    exit 1
fi

if [[ ! -s "$CLUSTER_TABLE" ]]; then
    echo "ERROR: Cluster membership table was not generated." >&2
    exit 1
fi

N_CLUSTERS="$(grep -c '^>' "$REPRESENTATIVE_FASTA" || true)"
N_CLUSTERED_PROTEINS="$(wc -l < "$CLUSTER_TABLE" | tr -d ' ')"

if [[ "$N_CLUSTERED_PROTEINS" -ne "$N_PROTEINS" ]]; then
    echo "WARNING: Input proteins: $N_PROTEINS; cluster membership rows: $N_CLUSTERED_PROTEINS." >&2
fi

echo "============================================================"
echo "MMseqs2 clustering completed successfully."
echo "Input proteins: $N_PROTEINS"
echo "Clusters: $N_CLUSTERS"
echo "Cluster membership rows: $N_CLUSTERED_PROTEINS"
echo "Representative proteins: $REPRESENTATIVE_FASTA"
echo "Cluster membership table: $CLUSTER_TABLE"
echo "============================================================"
