#!/usr/bin/env Rscript

###############################################################################
# FIGURE 1B — 16S rRNA TAXONOMIC COMPOSITION, SPATIAL PROFILING
#
# DESCRIPTION
#
# Generates the phylum-level 16S rRNA community-composition plot for the
# spatial peat profiles.
#
# INPUT
#
# Input file:
#   Phylum-level 16S rRNA relative-abundance table
#
# Generated by:
#   scripts/analyses/01_16S_rRNA_analysis/
#   04_prepare_16S_community_table.R
#
# Required columns:
#   Sample
#   Phylum
#   Abundance
#
# Supported input formats:
#   .xlsx
#   .xls
#   .tsv
#   .txt
#   .csv
#
# For Excel files, the default worksheet is:
#   relative_abundance
#
# The input table must contain one row per sample × phylum combination.
#
# SAMPLE SELECTION
#
# Includes the spatial profiles from Björsmossen, Norra Romyren and
# Lungsmossen.
#
# BM.3.10 is intentionally excluded from the final Figure 1B.
#
# OUTPUT
#
# Figure1B_16S_spatial_composition.svg
# Figure1B_16S_spatial_composition.pdf
# Figure1B_source_data.tsv
# Figure1B_sessionInfo.txt
#
# USAGE
#
# Rscript Figure1B_16S_spatial_composition.R \
#   path/to/input_table \
#   path/to/output_directory
#
# For an Excel worksheet other than `relative_abundance`:
#
# Rscript Figure1B_16S_spatial_composition.R \
#   path/to/input_table.xlsx \
#   path/to/output_directory \
#   worksheet_name
###############################################################################
###############################################################################
# 1. REQUIRED PACKAGES
###############################################################################

required_packages <- c(
  "dplyr",
  "ggplot2",
  "ggh4x",
  "svglite",
  "tidyr"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste(
      "Missing required R packages:",
      paste(missing_packages, collapse = ", ")
    )
  )
}

###############################################################################
# 2. COMMAND-LINE ARGUMENTS
###############################################################################

args <- commandArgs(
  trailingOnly = TRUE
)

if (length(args) < 1 || length(args) > 3) {
  stop(
    paste(
      "Usage:",
      "Rscript Figure1B_16S_spatial_composition.R",
      "<input_table>",
      "[output_directory]",
      "[excel_sheet]"
    )
  )
}

input_file <- args[[1]]

output_dir <- if (length(args) >= 2) {
  args[[2]]
} else {
  "."
}

excel_sheet <- if (length(args) == 3) {
  args[[3]]
} else {
  "relative_abundance"
}

if (!file.exists(input_file)) {
  stop(
    paste(
      "Input file not found:",
      input_file
    )
  )
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!dir.exists(output_dir)) {
  stop(
    paste(
      "Could not create output directory:",
      output_dir
    )
  )
}

###############################################################################
# 3. OUTPUT FILES
###############################################################################

output_svg <- file.path(
  output_dir,
  "Figure1B_16S_spatial_composition.svg"
)

output_pdf <- file.path(
  output_dir,
  "Figure1B_16S_spatial_composition.pdf"
)

source_data_file <- file.path(
  output_dir,
  "Figure1B_source_data.tsv"
)

session_info_file <- file.path(
  output_dir,
  "Figure1B_sessionInfo.txt"
)

###############################################################################
# 4. READ INPUT TABLE
###############################################################################

read_input_table <- function(
    input_file,
    excel_sheet
) {

  extension <- tolower(
    tools::file_ext(
      input_file
    )
  )

  if (extension %in% c("xlsx", "xls")) {

    if (!requireNamespace(
      "readxl",
      quietly = TRUE
    )) {
      stop(
        "Package 'readxl' is required to read Excel input files."
      )
    }

    available_sheets <- readxl::excel_sheets(
      input_file
    )

    if (!excel_sheet %in% available_sheets) {
      stop(
        paste0(
          "Worksheet '",
          excel_sheet,
          "' was not found. Available worksheets: ",
          paste(available_sheets, collapse = ", ")
        )
      )
    }

    input_table <- readxl::read_excel(
      input_file,
      sheet = excel_sheet
    )

  } else if (extension %in% c("tsv", "txt")) {

    input_table <- utils::read.delim(
      input_file,
      header = TRUE,
      sep = "\t",
      check.names = FALSE,
      stringsAsFactors = FALSE,
      comment.char = "",
      quote = ""
    )

  } else if (extension == "csv") {

    input_table <- utils::read.csv(
      input_file,
      header = TRUE,
      check.names = FALSE,
      stringsAsFactors = FALSE
    )

  } else {

    stop(
      paste0(
        "Unsupported input format: .",
        extension,
        ". Supported formats are .xlsx, .xls, .tsv, .txt and .csv."
      )
    )
  }

  as.data.frame(
    input_table,
    check.names = FALSE
  )
}

otu_plot_raw <- read_input_table(
  input_file = input_file,
  excel_sheet = excel_sheet
)

###############################################################################
# 5. STANDARDIZE AND VALIDATE COLUMN NAMES
###############################################################################

names(otu_plot_raw) <- trimws(
  names(otu_plot_raw)
)

names(otu_plot_raw) <- sub(
  "^\\ufeff",
  "",
  names(otu_plot_raw)
)

required_columns <- c(
  "Sample",
  "Phylum",
  "Abundance"
)

missing_columns <- setdiff(
  required_columns,
  names(otu_plot_raw)
)

if (length(missing_columns) > 0) {
  stop(
    paste(
      "Missing required columns:",
      paste(missing_columns, collapse = ", ")
    )
  )
}

###############################################################################
# 6. PREPARE INPUT DATA
###############################################################################

df_raw <- otu_plot_raw |>
  dplyr::transmute(
    Sample = trimws(
      as.character(
        .data$Sample
      )
    ),
    Phylum = trimws(
      tidyr::replace_na(
        as.character(
          .data$Phylum
        ),
        "NA"
      )
    ),
    Abundance = suppressWarnings(
      as.numeric(
        .data$Abundance
      )
    )
  )

if (any(
  is.na(df_raw$Sample) |
    df_raw$Sample == ""
)) {
  stop(
    "Missing or empty sample identifiers were found."
  )
}

if (any(
  is.na(df_raw$Phylum) |
    df_raw$Phylum == ""
)) {
  stop(
    "Missing or empty phylum assignments were found."
  )
}

non_numeric_abundance <- is.na(df_raw$Abundance) &
  !is.na(otu_plot_raw$Abundance) &
  trimws(as.character(otu_plot_raw$Abundance)) != ""

if (any(non_numeric_abundance)) {
  stop(
    paste(
      "Non-numeric values were found in the Abundance column.",
      "Check the input table before running the script."
    )
  )
}

# Preserve the behaviour of the original plotting workflow:
# empty abundance cells represent absent sample × phylum combinations.
df_raw <- df_raw |>
  dplyr::mutate(
    Abundance = dplyr::if_else(
      is.na(.data$Abundance),
      0,
      .data$Abundance
    )
  )

if (any(df_raw$Abundance < 0)) {
  stop(
    "Negative abundance values were found."
  )
}

###############################################################################
# 7. SPATIAL SAMPLE ORDER
###############################################################################

samples_spatial <- c(
  "BM.1.10",
  "BM.1.30",
  "BM.1.60",

  "BM.2.10",
  "BM.2.30",
  "BM.2.60",

  # BM.3.10 is intentionally excluded.
  "BM.3.30",
  "BM.3.60",

  "NR.1.10",
  "NR.1.30",
  "NR.1.60",

  "NR.2.10",
  "NR.2.30",
  "NR.2.60",

  "NR.3.10",
  "NR.3.30",
  "NR.3.60",

  "LM.1.10",
  "LM.1.30",
  "LM.1.60",

  "LM.2.10",
  "LM.2.30",
  "LM.2.60",

  "LM.3.10",
  "LM.3.30",
  "LM.3.60"
)

if (anyDuplicated(samples_spatial)) {
  stop(
    "The spatial sample-order vector contains duplicated sample names."
  )
}

###############################################################################
# 8. SELECT PHYLA
###############################################################################

archaeal_phyla <- c(
  "p__Halobacterota",
  "p__Crenarchaeota"
)

bacterial_phyla <- c(
  "p__Acidobacteriota",
  "p__Proteobacteria",
  "p__Verrucomicrobiota",
  "p__Desulfobacterota"
)

main_phyla <- c(
  archaeal_phyla,
  bacterial_phyla
)

phylum_order <- c(
  main_phyla,
  "Others"
)

phylum_colors <- c(
  "p__Halobacterota" = "#2171B5",
  "p__Crenarchaeota" = "#08306B",
  "p__Acidobacteriota" = "#B2182B",
  "p__Proteobacteria" = "#8C510A",
  "p__Verrucomicrobiota" = "#D8B365",
  "p__Desulfobacterota" = "#C77526",
  "Others" = "grey60"
)

###############################################################################
# 9. FILTER AND GROUP TAXA
###############################################################################

selected_data <- df_raw |>
  dplyr::filter(
    .data$Sample %in% samples_spatial
  )

missing_samples <- setdiff(
  samples_spatial,
  unique(selected_data$Sample)
)

if (length(missing_samples) > 0) {
  stop(
    paste(
      "Samples missing from the input table:",
      paste(missing_samples, collapse = ", ")
    )
  )
}

df_spatial <- selected_data |>
  dplyr::mutate(
    Phylum_plot = dplyr::if_else(
      .data$Phylum %in% main_phyla,
      .data$Phylum,
      "Others"
    )
  ) |>
  dplyr::group_by(
    .data$Sample,
    .data$Phylum_plot
  ) |>
  dplyr::summarise(
    Abundance = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  tidyr::complete(
    Sample = samples_spatial,
    Phylum_plot = phylum_order,
    fill = list(
      Abundance = 0
    )
  ) |>
  dplyr::mutate(
    Phylum_plot = factor(
      .data$Phylum_plot,
      levels = phylum_order
    ),
    Site = sub(
      "\\..*$",
      "",
      .data$Sample
    ),
    Microsite_number = sub(
      "^[A-Z]{2}\\.([0-9]+)\\..*$",
      "\\1",
      .data$Sample
    ),
    Microsite = factor(
      paste(
        "site",
        .data$Microsite_number
      ),
      levels = c(
        "site 1",
        "site 2",
        "site 3"
      )
    ),
    Site = factor(
      .data$Site,
      levels = c(
        "BM",
        "NR",
        "LM"
      )
    ),
    Sample = factor(
      .data$Sample,
      levels = rev(
        samples_spatial
      )
    )
  )

###############################################################################
# 10. VALIDATE SAMPLE TOTALS
###############################################################################

sample_totals <- df_spatial |>
  dplyr::group_by(
    .data$Sample
  ) |>
  dplyr::summarise(
    total_abundance = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  )

zero_abundance_samples <- sample_totals |>
  dplyr::filter(
    .data$total_abundance <= 0
  ) |>
  dplyr::pull(
    .data$Sample
  )

if (length(zero_abundance_samples) > 0) {
  stop(
    paste(
      "Samples with zero total abundance:",
      paste(zero_abundance_samples, collapse = ", ")
    )
  )
}

###############################################################################
# 11. DEPTH LABELS
###############################################################################

spatial_depth_labels <- stats::setNames(
  sub(
    "^.*\\.",
    "",
    samples_spatial
  ),
  samples_spatial
)

###############################################################################
# 12. FIGURE APPEARANCE
###############################################################################

plot_font <- Sys.getenv(
  "FIGURE_FONT",
  unset = "Arial"
)

fill_scale <- ggplot2::scale_fill_manual(
  values = phylum_colors,
  breaks = phylum_order,
  labels = function(x) {
    gsub(
      "^p__",
      "",
      x
    )
  },
  drop = FALSE
)

abundance_scale <- ggplot2::scale_x_continuous(
  breaks = seq(
    0,
    1,
    by = 0.25
  ),
  labels = function(x) {
    x * 100
  },
  limits = c(
    0,
    1
  ),
  expand = ggplot2::expansion(
    mult = c(
      0,
      0
    )
  )
)

common_theme <- ggplot2::theme_bw(
  base_size = 10,
  base_family = plot_font
) +
  ggplot2::theme(
    panel.grid.major.x = ggplot2::element_line(
      colour = "grey85",
      linewidth = 0.35
    ),
    panel.grid.minor.x = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_blank(),
    panel.grid.minor.y = ggplot2::element_blank(),
    panel.border = ggplot2::element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.7
    ),
    strip.background = ggplot2::element_rect(
      fill = "grey90",
      colour = "black",
      linewidth = 0.6
    ),
    axis.text = ggplot2::element_text(
      size = 8
    ),
    axis.title = ggplot2::element_text(
      size = 9
    ),
    legend.title = ggplot2::element_blank(),
    legend.position = "right",
    plot.margin = ggplot2::margin(
      6,
      6,
      6,
      6,
      unit = "pt"
    )
  )

###############################################################################
# 13. GENERATE FIGURE 1B
###############################################################################

p_spatial <- ggplot2::ggplot(
  df_spatial,
  ggplot2::aes(
    x = .data$Abundance,
    y = .data$Sample,
    fill = .data$Phylum_plot
  )
) +
  ggplot2::geom_col(
    width = 0.92,
    colour = "black",
    linewidth = 0.15,
    orientation = "y",
    position = ggplot2::position_fill(
      reverse = TRUE
    )
  ) +
  ggh4x::facet_nested(
    rows = ggplot2::vars(
      Site,
      Microsite
    ),
    scales = "free_y",
    space = "free_y",
    switch = "y"
  ) +
  abundance_scale +
  ggplot2::scale_y_discrete(
    labels = spatial_depth_labels,
    drop = TRUE
  ) +
  fill_scale +
  ggplot2::labs(
    x = "Relative abundance (%)",
    y = "Depth (cm)"
  ) +
  common_theme +
  ggplot2::theme(
    panel.spacing.y = grid::unit(
      0.8,
      "pt"
    ),
    strip.placement = "outside",
    strip.text.y.left = ggplot2::element_text(
      angle = 0,
      size = 9,
      margin = ggplot2::margin(
        2,
        3,
        2,
        3
      )
    )
  )

print(
  p_spatial
)

###############################################################################
# 14. WRITE FIGURE SOURCE DATA
###############################################################################

source_data_output <- df_spatial |>
  dplyr::mutate(
    Sample = as.character(
      .data$Sample
    ),
    Site = as.character(
      .data$Site
    ),
    Microsite = as.character(
      .data$Microsite
    ),
    Phylum_plot = as.character(
      .data$Phylum_plot
    )
  ) |>
  dplyr::arrange(
    match(
      .data$Sample,
      samples_spatial
    ),
    match(
      .data$Phylum_plot,
      phylum_order
    )
  )

utils::write.table(
  source_data_output,
  file = source_data_file,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

###############################################################################
# 15. SAVE SVG
###############################################################################

ggplot2::ggsave(
  filename = output_svg,
  plot = p_spatial,
  device = svglite::svglite,
  width = 6.0,
  height = 5.5,
  units = "in",
  bg = "white",
  system_fonts = list(
    sans = plot_font
  )
)

###############################################################################
# 16. SAVE PDF
###############################################################################

if (capabilities("cairo")) {

  ggplot2::ggsave(
    filename = output_pdf,
    plot = p_spatial,
    device = grDevices::cairo_pdf,
    width = 6.0,
    height = 5.5,
    units = "in",
    bg = "white"
  )

} else {

  warning(
    "PDF output was not generated because Cairo support is unavailable."
  )
}

###############################################################################
# 17. SESSION INFORMATION
###############################################################################

writeLines(
  capture.output(
    sessionInfo()
  ),
  session_info_file
)

cat(
  "\nFigure 1B generation completed successfully.\n"
)

cat(
  "Input file:\n",
  normalizePath(input_file),
  "\n",
  sep = ""
)

cat(
  "BM.3.10 was intentionally excluded from Figure 1B.\n"
)

cat(
  "SVG output:\n",
  normalizePath(output_svg),
  "\n",
  sep = ""
)
