#!/usr/bin/env Rscript

###############################################################################
# FIGURE 1C — dbRDA OF BM AND NR SPATIAL COMMUNITIES
#
# Generates the dbRDA of Björsmossen and Norra Romyren spatial 16S rRNA
# communities using the complete environmental dataset.
#
# INPUT
#
# Microbial community table generated by:
#   scripts/analyses/01_16S_rRNA_analysis/
#   04_prepare_16S_community_table.R
#
# Environmental metadata:
#   Supplementary_Table_2.xlsx
#
# Required microbial columns:
#   Sample, OTU, Abundance
#
# BM.3.10 is intentionally excluded.
#
# OUTPUT
#
# Figure1C_dbRDA_BM_NR.svg
#
# USAGE
#
# Rscript Figure1C_dbRDA_BM_NR.R \
#   microbial_table.xlsx \
#   Supplementary_Table_2.xlsx \
#   output_directory
###############################################################################
###############################################################################
# 1. REQUIRED PACKAGES
###############################################################################

required_packages <- c(
  "dplyr",
  "ggplot2",
  "ggrepel",
  "readxl",
  "scales",
  "svglite",
  "tidyr",
  "vegan"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste(
      "Missing required R packages:",
      paste(missing_packages, collapse = ", ")
    )
  )
}

###############################################################################
# 2. REPRODUCIBILITY
###############################################################################

set.seed(123)

###############################################################################
# 3. COMMAND-LINE ARGUMENTS
###############################################################################

args <- commandArgs(
  trailingOnly = TRUE
)

if (length(args) < 2 || length(args) > 3) {
  stop(
    paste(
      "Usage:",
      "Rscript Figure1C_dbRDA_BM_NR.R",
      "<microbial_community_file>",
      "<Supplementary_Table_2_file>",
      "[output_directory]"
    )
  )
}

microbial_file <- args[[1]]
metadata_file <- args[[2]]

output_dir <- if (length(args) == 3) {
  args[[3]]
} else {
  "."
}

input_files <- c(
  microbial_file,
  metadata_file
)

missing_input_files <- input_files[
  !file.exists(input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste(
      "The following input files were not found:",
      paste(
        missing_input_files,
        collapse = "\n"
      ),
      sep = "\n"
    )
  )
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!dir.exists(output_dir)) {
  stop(
    paste(
      "Could not create output directory:",
      output_dir
    )
  )
}

###############################################################################
# 4. OUTPUT FILES
###############################################################################

output_svg <- file.path(
  output_dir,
  "Figure1C_dbRDA_BM_NR.svg"
)

permanova_output <- file.path(
  output_dir,
  "Figure1C_PERMANOVA_results.txt"
)

site_scores_output <- file.path(
  output_dir,
  "Figure1C_site_scores.tsv"
)

environmental_vectors_output <- file.path(
  output_dir,
  "Figure1C_environmental_vectors.tsv"
)

samples_used_output <- file.path(
  output_dir,
  "Figure1C_samples_used.tsv"
)

session_info_output <- file.path(
  output_dir,
  "Figure1C_sessionInfo.txt"
)

###############################################################################
# 5. LOAD MICROBIAL-COMMUNITY TABLE
###############################################################################

microbial_sheets <- readxl::excel_sheets(
  microbial_file
)

microbial_sheet <- "relative_abundance"

if (!microbial_sheet %in% microbial_sheets) {
  stop(
    paste0(
      "Worksheet '",
      microbial_sheet,
      "' was not found in the microbial-community file. Available sheets: ",
      paste(
        microbial_sheets,
        collapse = ", "
      )
    )
  )
}

microbial_data <- readxl::read_excel(
  microbial_file,
  sheet = microbial_sheet
)

names(microbial_data) <- trimws(
  names(microbial_data)
)

names(microbial_data) <- sub(
  "^\\ufeff",
  "",
  names(microbial_data)
)

required_microbial_columns <- c(
  "Sample",
  "OTU",
  "Abundance"
)

missing_microbial_columns <- setdiff(
  required_microbial_columns,
  names(microbial_data)
)

if (length(missing_microbial_columns) > 0) {
  stop(
    paste(
      "Missing microbial-table columns:",
      paste(
        missing_microbial_columns,
        collapse = ", "
      )
    )
  )
}

microbial_data <- microbial_data |>
  dplyr::transmute(
    Sample = trimws(
      as.character(
        .data$Sample
      )
    ),
    OTU = trimws(
      as.character(
        .data$OTU
      )
    ),
    Abundance = suppressWarnings(
      as.numeric(
        .data$Abundance
      )
    )
  )

if (any(
  is.na(microbial_data$Sample) |
    microbial_data$Sample == ""
)) {
  stop(
    "Missing or empty sample identifiers were found in the microbial table."
  )
}

if (any(
  is.na(microbial_data$OTU) |
    microbial_data$OTU == ""
)) {
  stop(
    "Missing or empty OTU identifiers were found in the microbial table."
  )
}

if (anyNA(microbial_data$Abundance)) {
  stop(
    "Missing or non-numeric abundance values were found in the microbial table."
  )
}

if (any(microbial_data$Abundance < 0)) {
  stop(
    "Negative abundance values were found in the microbial table."
  )
}

duplicate_microbial_rows <- microbial_data |>
  dplyr::count(
    .data$Sample,
    .data$OTU,
    name = "n_rows"
  ) |>
  dplyr::filter(
    .data$n_rows > 1
  )

if (nrow(duplicate_microbial_rows) > 0) {
  stop(
    paste(
      "Duplicated sample × OTU combinations were found",
      "in the microbial-community table."
    )
  )
}

###############################################################################
# 6. LOAD SUPPLEMENTARY TABLE 2
###############################################################################

metadata_sheet <- "Supplementary_Table_2"

metadata_sheets <- readxl::excel_sheets(
  metadata_file
)

if (!metadata_sheet %in% metadata_sheets) {
  stop(
    paste0(
      "Worksheet '",
      metadata_sheet,
      "' was not found. Available sheets: ",
      paste(
        metadata_sheets,
        collapse = ", "
      )
    )
  )
}

environmental_data_raw <- readxl::read_excel(
  metadata_file,
  sheet = metadata_sheet,
  skip = 4,
  na = ""
)

names(environmental_data_raw) <- trimws(
  names(environmental_data_raw)
)

required_metadata_columns <- c(
  "Sampling",
  "Peatland",
  "Site",
  "Depth (cm)",
  "Sample name",
  "pH",
  "Temperature (°C)",
  "Electrical conductivity (μS cm⁻¹)",
  "CO₂:CH₄ (mol mol⁻¹)",
  "NO₃⁻ (µM)",
  "SO₄²⁻(µM)",
  "total Mn (µM)",
  "total Fe (µM)",
  "Propionate (mM)",
  "Acetate (mM)"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  names(environmental_data_raw)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    paste(
      "Missing columns in Supplementary Table 2:",
      paste(
        missing_metadata_columns,
        collapse = ", "
      )
    )
  )
}

###############################################################################
# 7. FORMAT NUMERIC METADATA
#
# Dashes represent non-detected or below-detection measurements and are
# converted to zero. Empty cells remain NA.
###############################################################################

to_numeric_metadata <- function(
    x,
    column_name
) {

  original_values <- trimws(
    as.character(
      x
    )
  )

  converted_values <- original_values

  converted_values[
    converted_values %in% c(
      "-",
      "–",
      "—"
    )
  ] <- "0"

  converted_values[
    is.na(converted_values) |
      converted_values == ""
  ] <- NA_character_

  numeric_values <- suppressWarnings(
    as.numeric(
      converted_values
    )
  )

  invalid_values <- is.na(numeric_values) &
    !is.na(converted_values)

  if (any(invalid_values)) {
    stop(
      paste0(
        "Non-numeric values were found in metadata column '",
        column_name,
        "': ",
        paste(
          unique(
            converted_values[invalid_values]
          ),
          collapse = ", "
        )
      )
    )
  }

  numeric_values
}

###############################################################################
# 8. FORMAT ENVIRONMENTAL METADATA
###############################################################################

environmental_data <- environmental_data_raw |>
  tidyr::fill(
    .data$Sampling,
    .data$Peatland,
    .data$Site,
    .direction = "down"
  ) |>
  dplyr::filter(
    .data$Sampling == "Spatial profiling"
  ) |>
  dplyr::mutate(
    Group = dplyr::case_when(
      .data$Peatland == "Björsmossen" ~ "BM",
      .data$Peatland == "Norra Romyren" ~ "NR",
      .data$Peatland == "Lungsmossen" ~ "LM",
      .data$Peatland == "Havsjömossen" ~ "HV",
      TRUE ~ NA_character_
    ),
    Site = suppressWarnings(
      as.integer(
        .data$Site
      )
    ),
    Depth_end = suppressWarnings(
      as.integer(
        sub(
          ".*[-–—]",
          "",
          as.character(
            .data$`Depth (cm)`
          )
        )
      )
    ),
    Sample = paste(
      .data$Group,
      .data$Site,
      .data$Depth_end,
      sep = "."
    )
  ) |>
  dplyr::transmute(
    Sample = .data$Sample,
    Group = .data$Group,
    Temperature = to_numeric_metadata(
      .data$`Temperature (°C)`,
      "Temperature (°C)"
    ),
    pH = to_numeric_metadata(
      .data$pH,
      "pH"
    ),
    Conductivity = to_numeric_metadata(
      .data$`Electrical conductivity (μS cm⁻¹)`,
      "Electrical conductivity (μS cm⁻¹)"
    ),
    CO2_CH4 = to_numeric_metadata(
      .data$`CO₂:CH₄ (mol mol⁻¹)`,
      "CO₂:CH₄ (mol mol⁻¹)"
    ),
    NO3 = to_numeric_metadata(
      .data$`NO₃⁻ (µM)`,
      "NO₃⁻ (µM)"
    ),
    SO4 = to_numeric_metadata(
      .data$`SO₄²⁻(µM)`,
      "SO₄²⁻(µM)"
    ),
    Propionate = to_numeric_metadata(
      .data$`Propionate (mM)`,
      "Propionate (mM)"
    ),
    Acetate = to_numeric_metadata(
      .data$`Acetate (mM)`,
      "Acetate (mM)"
    ),
    total_Mn = to_numeric_metadata(
      .data$`total Mn (µM)`,
      "total Mn (µM)"
    ),
    total_Fe = to_numeric_metadata(
      .data$`total Fe (µM)`,
      "total Fe (µM)"
    )
  )

if (any(
  is.na(environmental_data$Sample) |
    environmental_data$Sample == "NA.NA.NA"
)) {
  stop(
    "One or more spatial-profile sample identifiers could not be constructed."
  )
}

if (anyDuplicated(environmental_data$Sample)) {

  duplicated_samples <- unique(
    environmental_data$Sample[
      duplicated(
        environmental_data$Sample
      )
    ]
  )

  stop(
    paste(
      "Duplicated sample identifiers in the formatted metadata:",
      paste(
        duplicated_samples,
        collapse = ", "
      )
    )
  )
}

###############################################################################
# 9. MATCH MICROBIAL AND ENVIRONMENTAL SAMPLES
###############################################################################

matching_samples <- intersect(
  unique(
    microbial_data$Sample
  ),
  unique(
    environmental_data$Sample
  )
)

if (length(matching_samples) == 0) {
  stop(
    paste(
      "No sample identifiers match between the microbial table",
      "and Supplementary Table 2."
    )
  )
}

cat(
  "\nMatched samples:",
  length(matching_samples),
  "\n"
)

###############################################################################
# 10. SELECT BM AND NR AND EXCLUDE BM.3.10
###############################################################################

selected_groups <- c(
  "BM",
  "NR"
)

selected_variables <- c(
  "Temperature",
  "pH",
  "Conductivity",
  "CO2_CH4",
  "NO3",
  "SO4",
  "Propionate",
  "Acetate",
  "total_Mn",
  "total_Fe"
)

selected_metadata <- environmental_data |>
  dplyr::filter(
    .data$Sample %in% matching_samples,
    .data$Group %in% selected_groups,
    .data$Sample != "BM.3.10"
  ) |>
  dplyr::select(
    Sample,
    Group,
    dplyr::all_of(
      selected_variables
    )
  ) |>
  dplyr::filter(
    stats::complete.cases(
      dplyr::across(
        dplyr::all_of(
          selected_variables
        )
      )
    )
  ) |>
  dplyr::arrange(
    .data$Sample
  )

if (nrow(selected_metadata) < 3) {
  stop(
    paste(
      "Too few complete BM and NR samples are available",
      "for the full-variable dbRDA."
    )
  )
}

selected_microbial_data <- microbial_data |>
  dplyr::filter(
    .data$Sample %in% selected_metadata$Sample,
    .data$Sample != "BM.3.10"
  )

if ("BM.3.10" %in% selected_metadata$Sample ||
    "BM.3.10" %in% selected_microbial_data$Sample) {
  stop(
    "BM.3.10 was not successfully excluded."
  )
}

###############################################################################
# 11. BUILD SAMPLE × OTU COMMUNITY MATRIX
###############################################################################

microbial_wide <- selected_microbial_data |>
  dplyr::select(
    Sample,
    OTU,
    Abundance
  ) |>
  tidyr::pivot_wider(
    names_from = OTU,
    values_from = Abundance,
    values_fill = list(
      Abundance = 0
    )
  ) |>
  dplyr::arrange(
    .data$Sample
  )

community_matrix <- microbial_wide |>
  dplyr::select(
    -Sample
  ) |>
  as.matrix()

storage.mode(
  community_matrix
) <- "numeric"

rownames(
  community_matrix
) <- microbial_wide$Sample

missing_community_samples <- setdiff(
  selected_metadata$Sample,
  rownames(
    community_matrix
  )
)

if (length(missing_community_samples) > 0) {
  stop(
    paste(
      "Selected metadata samples missing from the community matrix:",
      paste(
        missing_community_samples,
        collapse = ", "
      )
    )
  )
}

community_matrix <- community_matrix[
  selected_metadata$Sample,
  ,
  drop = FALSE
]

if (!identical(
  rownames(community_matrix),
  selected_metadata$Sample
)) {
  stop(
    "Community and environmental samples are not in the same order."
  )
}

if (anyNA(community_matrix)) {
  stop(
    "NA values were found in the community matrix."
  )
}

if (any(
  rowSums(
    community_matrix
  ) <= 0
)) {
  stop(
    "At least one selected sample has zero total community abundance."
  )
}

###############################################################################
# 12. STANDARDIZE ENVIRONMENTAL VARIABLES
###############################################################################

zero_variance_variables <- selected_variables[
  vapply(
    selected_metadata[
      selected_variables
    ],
    function(x) {
      stats::sd(
        x,
        na.rm = TRUE
      ) == 0
    },
    FUN.VALUE = logical(1)
  )
]

if (length(zero_variance_variables) > 0) {
  stop(
    paste(
      "Environmental variables with zero variance:",
      paste(
        zero_variance_variables,
        collapse = ", "
      )
    )
  )
}

scaled_metadata <- selected_metadata

scaled_metadata[
  selected_variables
] <- scale(
  selected_metadata[
    selected_variables
  ]
)

rownames(
  scaled_metadata
) <- scaled_metadata$Sample

###############################################################################
# 13. HELLINGER TRANSFORMATION
###############################################################################

community_hellinger <- vegan::decostand(
  community_matrix,
  method = "hellinger"
)

###############################################################################
# 14. PERMANOVA
###############################################################################

environmental_permanova <- scaled_metadata[
  ,
  selected_variables,
  drop = FALSE
]

permanova_formula <- stats::reformulate(
  selected_variables,
  response = "community_hellinger"
)

permanova_result <- vegan::adonis2(
  permanova_formula,
  data = environmental_permanova,
  method = "bray",
  permutations = 999
)

cat(
  "\n### PERMANOVA RESULTS — BM AND NR ###\n"
)

print(
  permanova_result
)

writeLines(
  capture.output(
    permanova_result
  ),
  permanova_output
)

###############################################################################
# 15. dbRDA
###############################################################################

dbrda_model <- vegan::capscale(
  community_hellinger ~ .,
  data = scaled_metadata[
    ,
    selected_variables,
    drop = FALSE
  ],
  distance = "bray"
)

constrained_eigenvalues <- dbrda_model$CCA$eig

if (length(constrained_eigenvalues) < 2) {
  stop(
    "The fitted dbRDA contains fewer than two constrained axes."
  )
}

constrained_variation <- constrained_eigenvalues /
  sum(
    constrained_eigenvalues
  ) * 100

dbRDA1_percent <- round(
  constrained_variation[1],
  2
)

dbRDA2_percent <- round(
  constrained_variation[2],
  2
)

cat(
  "\ndbRDA1 explains:",
  dbRDA1_percent,
  "% of constrained variation.\n"
)

cat(
  "dbRDA2 explains:",
  dbRDA2_percent,
  "% of constrained variation.\n"
)

###############################################################################
# 16. EXTRACT SITE SCORES
###############################################################################

site_scores <- as.data.frame(
  vegan::scores(
    dbrda_model,
    display = "sites",
    scaling = 2
  )
)

site_scores$Sample <- rownames(
  site_scores
)

site_scores <- site_scores |>
  dplyr::left_join(
    scaled_metadata |>
      dplyr::select(
        Sample,
        Group
      ),
    by = "Sample"
  )

if (!all(
  c(
    "CAP1",
    "CAP2"
  ) %in% names(site_scores)
)) {
  stop(
    "CAP1 and CAP2 were not found in the dbRDA site scores."
  )
}

###############################################################################
# 17. FIT ENVIRONMENTAL VECTORS
###############################################################################

environmental_fit <- vegan::envfit(
  dbrda_model,
  scaled_metadata[
    ,
    selected_variables,
    drop = FALSE
  ],
  permutations = 999
)

environmental_vectors <- as.data.frame(
  vegan::scores(
    environmental_fit,
    display = "vectors"
  )
)

environmental_vectors$Variable <- rownames(
  environmental_vectors
)

environmental_pvalues <- data.frame(
  Variable = names(
    environmental_fit$vectors$pvals
  ),
  p_value = environmental_fit$vectors$pvals,
  stringsAsFactors = FALSE
)

variable_labels <- c(
  Temperature = "Temperature",
  pH = "pH",
  Conductivity = "Conductivity",
  CO2_CH4 = "CO2:CH4",
  NO3 = "NO3-",
  SO4 = "SO4²-",
  Propionate = "Propionate",
  Acetate = "Acetate",
  total_Mn = "total Mn",
  total_Fe = "total Fe"
)

environmental_vectors <- environmental_vectors |>
  dplyr::left_join(
    environmental_pvalues,
    by = "Variable"
  ) |>
  dplyr::mutate(
    significance = dplyr::case_when(
      .data$p_value < 0.001 ~ "***",
      .data$p_value < 0.01 ~ "**",
      .data$p_value < 0.05 ~ "*",
      TRUE ~ "ns"
    ),
    Variable_label = unname(
      variable_labels[
        .data$Variable
      ]
    ),
    Variable_label = dplyr::if_else(
      is.na(.data$Variable_label),
      .data$Variable,
      .data$Variable_label
    ),
    label = paste0(
      .data$Variable_label,
      " (",
      .data$significance,
      ")"
    )
  )

###############################################################################
# 18. SCALE ENVIRONMENTAL ARROWS
###############################################################################

arrow_scale <- 1.3

environmental_vectors <- environmental_vectors |>
  dplyr::mutate(
    CAP1_plot = .data$CAP1 * arrow_scale,
    CAP2_plot = .data$CAP2 * arrow_scale
  )

###############################################################################
# 19. WRITE FIGURE SOURCE TABLES
###############################################################################

utils::write.table(
  site_scores,
  file = site_scores_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

utils::write.table(
  environmental_vectors,
  file = environmental_vectors_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

samples_used <- selected_metadata |>
  dplyr::select(
    Sample,
    Group,
    dplyr::all_of(
      selected_variables
    )
  )

utils::write.table(
  samples_used,
  file = samples_used_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

###############################################################################
# 20. FIGURE APPEARANCE
###############################################################################

group_colors <- c(
  "BM" = "#3366CC",
  "NR" = "#E6863B"
)

###############################################################################
# 21. GENERATE FIGURE 1C
###############################################################################

p_dbrda <- ggplot2::ggplot(
  site_scores,
  ggplot2::aes(
    x = .data$CAP1,
    y = .data$CAP2,
    color = .data$Group
  )
) +
  ggplot2::stat_ellipse(
    level = 0.95,
    linewidth = 0.9,
    alpha = 0.35
  ) +
  ggplot2::geom_point(
    size = 4.5,
    alpha = 0.9
  ) +
  ggrepel::geom_text_repel(
    ggplot2::aes(
      label = .data$Sample
    ),
    size = 4.2,
    color = "black",
    box.padding = 0.3,
    point.padding = 0.2,
    max.overlaps = 100
  ) +
  ggplot2::geom_segment(
    data = environmental_vectors,
    ggplot2::aes(
      x = 0,
      y = 0,
      xend = .data$CAP1_plot,
      yend = .data$CAP2_plot
    ),
    arrow = grid::arrow(
      length = grid::unit(
        0.22,
        "cm"
      ),
      type = "open"
    ),
    color = scales::alpha(
      "grey20",
      0.65
    ),
    linewidth = 0.9,
    inherit.aes = FALSE
  ) +
  ggrepel::geom_text_repel(
    data = environmental_vectors,
    ggplot2::aes(
      x = .data$CAP1_plot * 1.02,
      y = .data$CAP2_plot * 1.02,
      label = .data$label
    ),
    size = 5,
    color = "black",
    box.padding = 0.45,
    point.padding = 0.3,
    force = 2,
    inherit.aes = FALSE
  ) +
  ggplot2::scale_color_manual(
    values = group_colors
  ) +
  ggplot2::labs(
    title = "dbRDA (BM and NR — full environmental variables)",
    x = paste0(
      "dbRDA1 (",
      dbRDA1_percent,
      "%)"
    ),
    y = paste0(
      "dbRDA2 (",
      dbRDA2_percent,
      "%)"
    ),
    color = "Peatland"
  ) +
  ggplot2::theme_classic(
    base_size = 18
  ) +
  ggplot2::theme(
    panel.grid = ggplot2::element_blank(),
    axis.line = ggplot2::element_line(
      color = "black",
      linewidth = 0.4
    ),
    legend.position = "right",
    plot.title = ggplot2::element_text(
      size = 20,
      face = "bold"
    ),
    axis.title = ggplot2::element_text(
      size = 18
    ),
    axis.text = ggplot2::element_text(
      size = 15
    ),
    legend.title = ggplot2::element_text(
      size = 17
    ),
    legend.text = ggplot2::element_text(
      size = 15
    )
  )

print(
  p_dbrda
)

###############################################################################
# 22. SAVE FIGURE
###############################################################################

ggplot2::ggsave(
  filename = output_svg,
  plot = p_dbrda,
  device = svglite::svglite,
  width = 8,
  height = 8,
  units = "in",
  bg = "white"
)

###############################################################################
# 23. SESSION INFORMATION
###############################################################################

writeLines(
  capture.output(
    sessionInfo()
  ),
  session_info_output
)

###############################################################################
# 24. FINAL SUMMARY
###############################################################################

cat(
  "\nFigure 1C generation completed successfully.\n"
)

cat(
  "Samples used:",
  nrow(selected_metadata),
  "\n"
)

cat(
  "Environmental variables:",
  length(selected_variables),
  "\n"
)

cat(
  "BM.3.10 was intentionally excluded.\n"
)

cat(
  "\nSVG output:\n",
  normalizePath(output_svg),
  "\n",
  sep = ""
)
