#!/usr/bin/env Rscript

###############################################################################
# FIGURE 1D — 16S rRNA TAXONOMIC COMPOSITION, DEEP PROFILING
#
# DESCRIPTION
# Generates the phylum-level 16S rRNA community-composition plot for the
# deep peat profiles.
#
# INPUT
# combined_otu_taxonomy_relative_abundance_2024.no_chloro_mito.xlsx
#
# Generated by:
# scripts/analyses/01_16S_rRNA_analysis/
# 04_prepare_16S_community_table.R
#
# Required columns:
# Sample, Phylum, Abundance
#
# OUTPUT
# Figure1D_16S_deep_composition.svg
#
# USAGE
# Rscript Figure1D_16S_deep_composition.R \
#   microbial_table.xlsx \
#   output_directory
###############################################################################

required_packages <- c(
  "dplyr",
  "ggplot2",
  "readxl",
  "svglite",
  "tidyr"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_packages, collapse = ", ")
  )
}

###############################################################################
# INPUT AND OUTPUT
###############################################################################

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 1 || length(args) > 2) {
  stop(
    paste(
      "Usage:",
      "Rscript Figure1D_16S_deep_composition.R",
      "<microbial_table.xlsx>",
      "[output_directory]"
    )
  )
}

input_file <- args[[1]]

output_dir <- if (length(args) == 2) {
  args[[2]]
} else {
  "."
}

if (!file.exists(input_file)) {
  stop("Input file not found: ", input_file)
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

output_svg <- file.path(
  output_dir,
  "Figure1D_16S_deep_composition.svg"
)

###############################################################################
# SAMPLE ORDER
###############################################################################

samples_deep <- c(
  "BM.0.50",
  "BM.50",
  "BM.100",
  "BM.150",
  "BM.200",
  "BM.250",
  "BM.300",
  "BM.350",
  "BM.400",
  "BM.450",
  "BM.490.540",

  "HV.0.25",
  "HV.50",
  "HV.100",
  "HV.150",
  "HV.200",
  "HV.250",
  "HV.265.280",

  "LM.0.25",
  "LM.50",
  "LM.100",
  "LM.150",
  "LM.200",
  "LM.250",
  "LM.300",
  "LM.350",
  "LM.400",
  "LM.450",
  "LM.550",
  "LM.600",
  "LM.650",
  "LM.675.700",

  "NR.0.25",
  "NR.50",
  "NR.100",
  "NR.150",
  "NR.200",
  "NR.250",
  "NR.300",
  "NR.325.350"
)

###############################################################################
# LOAD INPUT TABLE
###############################################################################

input_data <- readxl::read_excel(
  input_file,
  sheet = "relative_abundance"
)

names(input_data) <- trimws(names(input_data))
names(input_data) <- sub("^\\ufeff", "", names(input_data))

required_columns <- c(
  "Sample",
  "Phylum",
  "Abundance"
)

missing_columns <- setdiff(
  required_columns,
  names(input_data)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing required columns: ",
    paste(missing_columns, collapse = ", ")
  )
}

data_raw <- input_data |>
  dplyr::transmute(
    Sample = trimws(as.character(.data$Sample)),
    Phylum = trimws(
      tidyr::replace_na(
        as.character(.data$Phylum),
        "NA"
      )
    ),
    Abundance = suppressWarnings(
      as.numeric(.data$Abundance)
    )
  ) |>
  dplyr::mutate(
    Abundance = dplyr::if_else(
      is.na(.data$Abundance),
      0,
      .data$Abundance
    )
  ) |>
  dplyr::filter(
    .data$Sample %in% samples_deep
  )

missing_samples <- setdiff(
  samples_deep,
  unique(data_raw$Sample)
)

if (length(missing_samples) > 0) {
  stop(
    "Deep-profile samples missing from the input table: ",
    paste(missing_samples, collapse = ", ")
  )
}

###############################################################################
# PHYLA AND PALETTE
###############################################################################

archaeal_phyla <- c(
  "p__Halobacterota",
  "p__Crenarchaeota"
)

bacterial_phyla <- c(
  "p__Acidobacteriota",
  "p__Proteobacteria",
  "p__Verrucomicrobiota",
  "p__Desulfobacterota"
)

main_phyla <- c(
  archaeal_phyla,
  bacterial_phyla
)

phylum_order <- c(
  archaeal_phyla,
  bacterial_phyla,
  "Others"
)

phylum_colors <- c(
  "p__Halobacterota" = "#2171B5",
  "p__Crenarchaeota" = "#08306B",
  "p__Acidobacteriota" = "#B2182B",
  "p__Proteobacteria" = "#8C510A",
  "p__Verrucomicrobiota" = "#D8B365",
  "p__Desulfobacterota" = "#C77526",
  "Others" = "grey60"
)

###############################################################################
# PREPARE PLOTTING TABLE
###############################################################################

plot_data <- data_raw |>
  dplyr::mutate(
    Phylum_plot = dplyr::if_else(
      .data$Phylum %in% main_phyla,
      .data$Phylum,
      "Others"
    )
  ) |>
  dplyr::group_by(
    .data$Sample,
    .data$Phylum_plot
  ) |>
  dplyr::summarise(
    Abundance = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  tidyr::complete(
    Sample = samples_deep,
    Phylum_plot = phylum_order,
    fill = list(
      Abundance = 0
    )
  ) |>
  dplyr::mutate(
    Phylum_plot = factor(
      .data$Phylum_plot,
      levels = phylum_order
    ),
    Site = factor(
      sub("\\..*$", "", .data$Sample),
      levels = c(
        "BM",
        "HV",
        "LM",
        "NR"
      )
    ),
    Sample = factor(
      .data$Sample,
      levels = rev(samples_deep)
    )
  )

sample_totals <- plot_data |>
  dplyr::group_by(.data$Sample) |>
  dplyr::summarise(
    total = sum(.data$Abundance),
    .groups = "drop"
  )

zero_samples <- sample_totals |>
  dplyr::filter(.data$total <= 0) |>
  dplyr::pull(.data$Sample)

if (length(zero_samples) > 0) {
  stop(
    "Samples with zero total abundance: ",
    paste(zero_samples, collapse = ", ")
  )
}

###############################################################################
# DEPTH LABELS
###############################################################################

deep_depth_label <- function(sample_name) {

  without_site <- sub(
    "^[A-Z]{2}\\.",
    "",
    sample_name
  )

  parts <- strsplit(
    without_site,
    "\\."
  )[[1]]

  if (length(parts) == 1) {
    return(parts[1])
  }

  if (length(parts) == 2 && parts[1] == "0") {
    return(
      paste0(
        "0–",
        parts[2]
      )
    )
  }

  paste0(
    parts[length(parts) - 1],
    "–",
    parts[length(parts)]
  )
}

depth_labels <- stats::setNames(
  vapply(
    samples_deep,
    deep_depth_label,
    character(1)
  ),
  samples_deep
)

###############################################################################
# PLOT
###############################################################################

p_deep <- ggplot2::ggplot(
  plot_data,
  ggplot2::aes(
    x = .data$Abundance,
    y = .data$Sample,
    fill = .data$Phylum_plot
  )
) +
  ggplot2::geom_col(
    width = 0.92,
    colour = "black",
    linewidth = 0.15,
    orientation = "y",
    position = ggplot2::position_fill(
      reverse = TRUE
    )
  ) +
  ggplot2::facet_wrap(
    facets = ggplot2::vars(Site),
    nrow = 1,
    scales = "free_y"
  ) +
  ggplot2::scale_x_continuous(
    breaks = seq(
      0,
      1,
      by = 0.25
    ),
    labels = function(x) {
      x * 100
    },
    limits = c(
      0,
      1
    ),
    expand = ggplot2::expansion(
      mult = c(
        0,
        0
      )
    )
  ) +
  ggplot2::scale_y_discrete(
    labels = depth_labels,
    drop = TRUE
  ) +
  ggplot2::scale_fill_manual(
    values = phylum_colors,
    breaks = phylum_order,
    labels = function(x) {
      gsub(
        "^p__",
        "",
        x
      )
    },
    drop = FALSE
  ) +
  ggplot2::labs(
    x = "Relative abundance (%)",
    y = "Depth (cm)",
    fill = NULL
  ) +
  ggplot2::theme_bw(
    base_size = 10,
    base_family = "Arial"
  ) +
  ggplot2::theme(
    panel.grid.major.x = ggplot2::element_line(
      colour = "grey85",
      linewidth = 0.35
    ),
    panel.grid.minor.x = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_blank(),
    panel.grid.minor.y = ggplot2::element_blank(),
    panel.border = ggplot2::element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.7
    ),
    strip.background = ggplot2::element_rect(
      fill = "grey90",
      colour = "black",
      linewidth = 0.6
    ),
    panel.spacing.x = grid::unit(
      10,
      "pt"
    ),
    strip.text.x = ggplot2::element_text(
      face = "plain",
      size = 10
    ),
    axis.text = ggplot2::element_text(
      size = 8
    ),
    axis.title = ggplot2::element_text(
      size = 9
    ),
    legend.position = "right",
    plot.margin = ggplot2::margin(
      6,
      6,
      6,
      6,
      unit = "pt"
    )
  )

print(p_deep)

ggplot2::ggsave(
  filename = output_svg,
  plot = p_deep,
  device = svglite::svglite,
  width = 12,
  height = 2.6,
  units = "in",
  bg = "white",
  system_fonts = list(
    sans = "Arial"
  )
)

cat(
  "\nFigure 1D saved to:\n",
  output_svg,
  "\n",
  sep = ""
)
