#!/usr/bin/env Rscript

# DESCRIPTION
# Generates Supplementary Figure 2: a bubble plot summarizing the fraction
# of MAGs in each EET group with a positive correlation between EET
# expression and expression of alternative respiratory pathways.
#
# Bubble size is calculated as:
#   MAGs with a positive evaluable correlation /
#   all MAGs represented in the corresponding EET group
#
# INPUT
# 1. Per-MAG pathway-correlation TSV generated by script 04_test_EET_alternative_respiration_correlations.py.
# 2. Output directory.
#
# OUTPUT
# Supplementary Figure 2 as SVG and PDF and the plotted summary as TSV.
#
# USAGE
# Rscript Supplementary_Figure_2.R \
#   23_refined_per_MAG_pathway_correlations.tsv \
#   output_directory

suppressPackageStartupMessages({
  library(tidyverse)
  library(scales)
  library(svglite)
})

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 2) {
  stop(
    paste(
      "Usage: Rscript Supplementary_Figure_2.R",
      "<per_MAG_pathway_correlations.tsv>",
      "<output_directory>"
    ),
    call. = FALSE
  )
}

INPUT_TSV <- args[[1]]
output_dir <- args[[2]]

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

OUT_SUMMARY_TSV <- file.path(
  output_dir,
  "Supplementary_Figure_2_summary.tsv"
)

OUT_SVG <- file.path(
  output_dir,
  "Supplementary_Figure_2.svg"
)

OUT_PDF <- file.path(
  output_dir,
  "Supplementary_Figure_2.pdf"
)

TARGET_OUTCOME <- "pathway_max_MT_coverage_per_cell"


###############################################################################
# PATHWAY METADATA
###############################################################################

pathway_metadata <- tribble(
  ~refined_pathway, ~macro_category, ~display_label, ~pathway_order,
  
  # Oxygen metabolism
  "O2_aa3_cytochrome_c_oxidase",
  "Oxygen metabolism",
  "coxAB",
  1,
  
  "O2_cbb3_cytochrome_c_oxidase",
  "Oxygen metabolism",
  "ccoNOP",
  2,
  
  "O2_cyd_bd_oxidase",
  "Oxygen metabolism",
  "cyoABCD / cydAB",
  3,
  
  # Nitrogen cycling
  "N_nap_periplasmic_nitrate_reduction",
  "Nitrogen cycling",
  "napAB",
  4,
  
  "N_nar_nxr_like_complex",
  "Nitrogen cycling",
  "narGH / nxrAB",
  5,
  
  "N_nrf_DNRA",
  "Nitrogen cycling",
  "nrfAH",
  6,
  
  "N_nirK_nirS_NO_forming_nitrite_reduction",
  "Nitrogen cycling",
  "nirK / nirS",
  7,
  
  "N_nor_nitric_oxide_reduction",
  "Nitrogen cycling",
  "norBC",
  8,
  
  "N_nos_nitrous_oxide_reduction",
  "Nitrogen cycling",
  "nosZ / nosD",
  9,
  
  # Sulfur cycling
  "S_apr_adenylylsulfate_reduction",
  "Sulfur cycling",
  "aprA",
  10,
  
  "S_asr_sulfite_reduction",
  "Sulfur cycling",
  "asrABC",
  11,
  
  "S_dsr_sulfite_reduction",
  "Sulfur cycling",
  "dsrABD",
  12,
  
  "S_dmsA_DMSO_reduction",
  "Sulfur cycling",
  "dmsA",
  13,
  
  "S_phsA_thiosulfate_polysulfide_reduction",
  "Sulfur cycling",
  "phsA",
  14,
  
  # Other terminal electron acceptors
  "Cl_chlorate_reduction",
  "Other terminal electron acceptors",
  "clrB",
  15,
  
  "Se_selenate_reduction",
  "Other terminal electron acceptors",
  "ygfM / xdhD / ygfK",
  16,
  
  "F_fumarate_reduction",
  "Other terminal electron acceptors",
  "frdABCD",
  17,
  
  # Hydrogen metabolism
  "H_hydrogenases",
  "Hydrogen metabolism",
  "Hydrogenases",
  18
)

macro_category_order <- c(
  "Oxygen metabolism",
  "Nitrogen cycling",
  "Sulfur cycling",
  "Other terminal electron acceptors",
  "Hydrogen metabolism"
)

###############################################################################
# COLORS FOR PATHWAY CATEGORIES
###############################################################################

category_colors <- c(
  "Oxygen metabolism" = "#2C3E99",
  "Nitrogen cycling" = "#2CA02C",
  "Sulfur cycling" = "#8E3AAE",
  "Other terminal electron acceptors" = "#B47713",
  "Hydrogen metabolism" = "#666666"
)

###############################################################################
# HELPERS
###############################################################################

parse_logical <- function(x) {
  x_chr <- tolower(trimws(as.character(x)))
  
  case_when(
    x_chr %in% c("true", "t", "1") ~ TRUE,
    x_chr %in% c("false", "f", "0") ~ FALSE,
    TRUE ~ NA
  )
}

###############################################################################
# READ AND VALIDATE DATA
###############################################################################

if (!file.exists(INPUT_TSV)) {
  stop(
    "Input file not found:\n",
    INPUT_TSV
  )
}

corr <- read_tsv(
  INPUT_TSV,
  show_col_types = FALSE
)

required_columns <- c(
  "MAG_name",
  "EET_group",
  "refined_pathway",
  "outcome",
  "rho",
  "eligible_for_heatmap"
)

missing_columns <- setdiff(
  required_columns,
  colnames(corr)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing required columns: ",
    paste(missing_columns, collapse = ", ")
  )
}

###############################################################################
# TOTAL NUMBER OF MAGs IN EACH EET GROUP
###############################################################################

group_totals <- corr %>%
  distinct(
    MAG_name,
    EET_group
  ) %>%
  count(
    EET_group,
    name = "n_MAGs_total_group"
  ) %>%
  arrange(EET_group)

###############################################################################
# FILTER THE QUANTITATIVE CORRELATION OUTCOME
###############################################################################

corr_target <- corr %>%
  mutate(
    rho = as.numeric(rho),
    eligible_for_heatmap = parse_logical(
      eligible_for_heatmap
    )
  ) %>%
  filter(
    outcome == TARGET_OUTCOME,
    refined_pathway %in% pathway_metadata$refined_pathway
  )

if (nrow(corr_target) == 0) {
  stop(
    "No rows remain for outcome: ",
    TARGET_OUTCOME
  )
}

###############################################################################
# SUMMARISE POSITIVE CORRELATIONS
###############################################################################

summary_observed <- corr_target %>%
  group_by(
    EET_group,
    refined_pathway
  ) %>%
  summarise(
    n_MAGs_evaluable = n_distinct(
      MAG_name[
        eligible_for_heatmap &
          is.finite(rho)
      ]
    ),
    
    n_MAGs_positive = n_distinct(
      MAG_name[
        eligible_for_heatmap &
          is.finite(rho) &
          rho > 0
      ]
    ),
    
    .groups = "drop"
  )

full_grid <- crossing(
  EET_group = c(
    "EET1",
    "EET2",
    "EET3",
    "EET4"
  ),
  refined_pathway = pathway_metadata$refined_pathway
)

summary_complete <- full_grid %>%
  left_join(
    summary_observed,
    by = c(
      "EET_group",
      "refined_pathway"
    )
  ) %>%
  left_join(
    group_totals,
    by = "EET_group"
  ) %>%
  left_join(
    pathway_metadata,
    by = "refined_pathway"
  ) %>%
  mutate(
    n_MAGs_evaluable = replace_na(
      n_MAGs_evaluable,
      0L
    ),
    
    n_MAGs_positive = replace_na(
      n_MAGs_positive,
      0L
    ),
    
    # Main plotted metric:
    # positive MAGs divided by all MAGs in that EET group.
    fraction_total_group_positive = (
      n_MAGs_positive /
        n_MAGs_total_group
    ),
    
    # Kept only for QC and interpretation.
    fraction_evaluable_positive = if_else(
      n_MAGs_evaluable > 0,
      n_MAGs_positive /
        n_MAGs_evaluable,
      NA_real_
    )
  )

write_tsv(
  summary_complete,
  OUT_SUMMARY_TSV
)

###############################################################################
# PREPARE DATA FOR PLOTTING
###############################################################################

display_order <- pathway_metadata %>%
  arrange(pathway_order) %>%
  pull(display_label)

plot_data <- summary_complete %>%
  mutate(
    # This gives EET1 at the top and EET4 at the bottom.
    EET_group = factor(
      EET_group,
      levels = c(
        "EET4",
        "EET3",
        "EET2",
        "EET1"
      )
    ),
    
    macro_category = factor(
      macro_category,
      levels = macro_category_order
    ),
    
    display_label = factor(
      display_label,
      levels = display_order
    )
  )

grid_data <- plot_data %>%
  distinct(
    EET_group,
    display_label,
    macro_category
  )

bubble_data <- plot_data %>%
  filter(
    n_MAGs_positive > 0,
    fraction_total_group_positive > 0
  )

###############################################################################
# PLOT
###############################################################################

p <- ggplot() +
  
  geom_tile(
    data = grid_data,
    aes(
      x = display_label,
      y = EET_group
    ),
    fill = "white",
    color = "black",
    linewidth = 0.55,
    width = 0.96,
    height = 0.96
  ) +
  
  geom_point(
    data = bubble_data,
    aes(
      x = display_label,
      y = EET_group,
      size = fraction_total_group_positive,
      fill = macro_category
    ),
    shape = 21,
    color = "black",
    stroke = 0.5
  ) +
  
  facet_grid(
    cols = vars(macro_category),
    scales = "free_x",
    space = "free_x",
    switch = "x"
  ) +
  
  scale_fill_manual(
    values = category_colors,
    name = "Pathway category"
  ) +
  
  # Bubble AREA is proportional to the fraction.
  scale_size_area(
    max_size = 12,
    limits = c(0, 1),
    breaks = c(
      0.10,
      0.25,
      0.50,
      0.75,
      1.00
    ),
    labels = percent_format(
      accuracy = 1
    ),
    name = paste0(
      "Fraction of all MAGs in\n",
      "each EET group with a\n",
      "positive correlation"
    )
  ) +
  
  labs(
    x = NULL,
    y = NULL
  ) +
  
  theme_classic(
    base_size = 10.5
  ) +
  
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1,
      size = 8.5,
      color = "black"
    ),
    
    axis.text.y = element_text(
      size = 10.5,
      face = "bold",
      color = "black"
    ),
    
    strip.placement = "outside",
    
    strip.background.x = element_rect(
      fill = "white",
      color = "black",
      linewidth = 0.5
    ),
    
    strip.text.x = element_text(
      size = 8.5,
      face = "bold",
      color = "black",
      margin = margin(
        4,
        4,
        4,
        4
      )
    ),
    
    panel.spacing.x = unit(
      0.10,
      "cm"
    ),
    
    legend.position = "right",
    
    legend.title = element_text(
      size = 8.5
    ),
    
    legend.text = element_text(
      size = 8.5
    ),
    
    plot.margin = margin(
      8,
      12,
      8,
      8
    )
  ) +
  
  guides(
    fill = guide_legend(
      title.position = "top",
      title.hjust = 0.5,
      override.aes = list(
        size = 5,
        shape = 21,
        color = "black"
      )
    ),
    
    size = guide_legend(
      title.position = "top",
      title.hjust = 0.5,
      override.aes = list(
        fill = "grey70",
        shape = 21,
        color = "black"
      )
    )
  )

###############################################################################
# SAVE
###############################################################################

ggsave(
  OUT_SVG,
  plot = p,
  width = 14,
  height = 5.1,
  units = "in",
  device = svglite::svglite,
  bg = "white"
)

ggsave(
  OUT_PDF,
  plot = p,
  width = 13,
  height = 4.1,
  units = "in",
  device = grDevices::cairo_pdf,
  bg = "white"
)

print(p)
