#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_metaSPAdes
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=50G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

###############################################################################
# DESCRIPTION
# Assembles cleaned paired-end metagenomic reads using metaSPAdes.
#
# INPUT
# Cleaned paired-end reads generated by:
# scripts/analyses/02_metagenome_MAG_processing/
# 03_bbduk_trimming_and_fastqc.sh
#
# OUTPUT
# Per-sample metaSPAdes assembly directory.
#
# USAGE
# sbatch 04_metaspades_assembly.sh \
#   sample_PE1_trim_clean.fq.gz \
#   sample_PE2_trim_clean.fq.gz \
#   output_directory \
#   /path/to/metaspades.py
###############################################################################

if [[ $# -ne 4 ]]; then
    echo "Usage:" >&2
    echo "  sbatch $0 <R1_trimmed> <R2_trimmed> <output_directory> <metaspades.py>" >&2
    exit 1
fi

R1="$1"
R2="$2"
OUTPUT_DIR="$3"
METASPADES_SCRIPT="$4"

THREADS=16
MEMORY_GB=1000
KMER_SIZES="21,33,55,77,99,127"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -f "$R1" ]]; then
    echo "ERROR: Forward-read file not found: $R1" >&2
    exit 1
fi

if [[ ! -f "$R2" ]]; then
    echo "ERROR: Reverse-read file not found: $R2" >&2
    exit 1
fi

if [[ ! -f "$METASPADES_SCRIPT" ]]; then
    echo "ERROR: metaSPAdes script not found: $METASPADES_SCRIPT" >&2
    exit 1
fi

if ! command -v python >/dev/null 2>&1; then
    echo "ERROR: Python was not found in the active environment." >&2
    exit 1
fi

if [[ -e "$OUTPUT_DIR" ]] && [[ -n "$(find "$OUTPUT_DIR" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
    echo "ERROR: Output directory already exists and is not empty: $OUTPUT_DIR" >&2
    echo "Use a new directory or restart the original metaSPAdes run manually." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# METASPADES ASSEMBLY
###############################################################################

echo "Starting metaSPAdes assembly."
echo "Forward reads: $R1"
echo "Reverse reads: $R2"
echo "Output directory: $OUTPUT_DIR"
echo "Threads: $THREADS"
echo "Memory: ${MEMORY_GB} GB"
echo "K-mer sizes: $KMER_SIZES"

python "$METASPADES_SCRIPT" \
    --pe1-1 "$R1" \
    --pe1-2 "$R2" \
    -k "$KMER_SIZES" \
    -o "$OUTPUT_DIR" \
    -m "$MEMORY_GB" \
    -t "$THREADS"

echo "metaSPAdes assembly completed successfully."
echo "Assembly directory: $OUTPUT_DIR"
