#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_BBMap_assembly_QC
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=10G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Calculates assembly statistics for each metaSPAdes scaffolds.fasta file
# using BBMap stats.sh.
#
# INPUT
# Per-sample metaSPAdes assembly directories containing scaffolds.fasta.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/04_metaspades_assembly.sh
#
# OUTPUT
# One BBMap assembly-statistics table per sample.
#
# USAGE
# sbatch 05a_bbmap_assembly_stats.sh assembly_directory output_directory

if [[ $# -ne 2 ]]; then
    echo "Usage: sbatch $0 <assembly_directory> <output_directory>" >&2
    exit 1
fi

BASE_DIR="$1"
OUTPUT_DIR="$2"

BBMAP_MODULE="${BBMAP_MODULE:-bbmap/39.01}"

if [[ ! -d "$BASE_DIR" ]]; then
    echo "ERROR: Assembly directory not found: $BASE_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

module load "$BBMAP_MODULE"

mapfile -d '' ASSEMBLIES < <(
    find "$BASE_DIR" \
        -type f \
        -name "scaffolds.fasta" \
        -print0 |
        sort -z
)

if [[ ${#ASSEMBLIES[@]} -eq 0 ]]; then
    echo "ERROR: No scaffolds.fasta files found in: $BASE_DIR" >&2
    exit 1
fi

for ASSEMBLY in "${ASSEMBLIES[@]}"; do

    SAMPLE_NAME="$(basename "$(dirname "$ASSEMBLY")")"
    OUTPUT_FILE="$OUTPUT_DIR/${SAMPLE_NAME}_bbmap_stats.txt"

    echo "Processing: $SAMPLE_NAME"

    stats.sh \
        in="$ASSEMBLY" \
        > "$OUTPUT_FILE"

done

echo "BBMap assembly statistics completed successfully."
echo "Output directory: $OUTPUT_DIR"
