#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_filter_scaffolds
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=50G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Removes scaffolds shorter than 1,000 nucleotides using BBMap reformat.sh.
#
# INPUT
# Per-sample metaSPAdes directories containing scaffolds.fasta.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/04_metaspades_assembly.sh
#
# OUTPUT
# One <sample>_scaffolds_min1000.fasta file per assembly.
#
# USAGE
# sbatch 06_filter_scaffolds_min1000.sh assembly_directory output_directory

if [[ $# -ne 2 ]]; then
    echo "Usage: sbatch $0 <assembly_directory> <output_directory>" >&2
    exit 1
fi

BASE_DIR="$1"
OUTPUT_DIR="$2"

BBMAP_MODULE="${BBMAP_MODULE:-bbmap/39.01}"
JAVA_MODULE="${JAVA_MODULE:-openjdk/21.0.3_9}"

if [[ ! -d "$BASE_DIR" ]]; then
    echo "ERROR: Assembly directory not found: $BASE_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

module load "$BBMAP_MODULE"
module load "$JAVA_MODULE"

mapfile -d '' ASSEMBLIES < <(
    find "$BASE_DIR" \
        -type f \
        -name "scaffolds.fasta" \
        -print0 |
        sort -z
)

if [[ ${#ASSEMBLIES[@]} -eq 0 ]]; then
    echo "ERROR: No scaffolds.fasta files found in: $BASE_DIR" >&2
    exit 1
fi

for ASSEMBLY in "${ASSEMBLIES[@]}"; do

    SAMPLE_NAME="$(basename "$(dirname "$ASSEMBLY")")"
    OUTPUT_FILE="$OUTPUT_DIR/${SAMPLE_NAME}_scaffolds_min1000.fasta"

    echo "Filtering assembly: $SAMPLE_NAME"

    reformat.sh \
        in="$ASSEMBLY" \
        out="$OUTPUT_FILE" \
        minlength=1000

done

echo "Scaffold filtering completed successfully."
echo "Output directory: $OUTPUT_DIR"
