#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_Prodigal
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=20G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Predicts protein-coding genes from metagenomic scaffolds using Prodigal
# in metagenomic mode.
#
# INPUT
# Files named <sample>_scaffolds_min1000.fasta.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/06_filter_scaffolds_min1000.sh
#
# OUTPUT
# Per-sample GFF annotations, amino-acid sequences and nucleotide sequences.
#
# USAGE
# sbatch 07_predict_genes_with_prodigal.sh \
#   filtered_scaffolds_directory \
#   output_directory

if [[ $# -ne 2 ]]; then
    echo "Usage: sbatch $0 <filtered_scaffolds_directory> <output_directory>" >&2
    exit 1
fi

BASE_DIR="$1"
OUTPUT_DIR="$2"

PRODIGAL_MODULE="${PRODIGAL_MODULE:-prodigal/2.6.3}"

if [[ ! -d "$BASE_DIR" ]]; then
    echo "ERROR: Filtered-scaffold directory not found: $BASE_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

module load "$PRODIGAL_MODULE"

mapfile -d '' SCAFFOLD_FILES < <(
    find "$BASE_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*_scaffolds_min1000.fasta" \
        -print0 |
        sort -z
)

if [[ ${#SCAFFOLD_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No *_scaffolds_min1000.fasta files found in: $BASE_DIR" >&2
    exit 1
fi

for SCAFFOLD_FILE in "${SCAFFOLD_FILES[@]}"; do

    BASENAME="$(basename "$SCAFFOLD_FILE" .fasta)"

    GFF_OUTPUT="$OUTPUT_DIR/${BASENAME}.gff"
    FAA_OUTPUT="$OUTPUT_DIR/${BASENAME}_proteins.faa"
    FNA_OUTPUT="$OUTPUT_DIR/${BASENAME}_proteins.fna"

    echo "Processing: $BASENAME"

    prodigal \
        -i "$SCAFFOLD_FILE" \
        -o "$GFF_OUTPUT" \
        -f gff \
        -a "$FAA_OUTPUT" \
        -d "$FNA_OUTPUT" \
        -p meta

done

echo "Prodigal gene prediction completed successfully."
echo "Output directory: $OUTPUT_DIR"
