#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_differential_coverage
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=20G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Maps selected metagenomic read sets to each assembly to generate differential
# scaffold-coverage profiles for genome binning.
#
# INPUT
# Filtered assemblies, cleaned paired-end reads and
# 08_differential_coverage_mapping_design.tsv.
# Generated by: 03_bbduk_trimming_and_fastqc.sh and
# 06_filter_scaffolds_min1000.sh
#
# OUTPUT
# Sorted and indexed BAM files and BBMap scaffold-coverage tables.
#
# USAGE
# sbatch 08_generate_differential_coverage_profiles.sh \
#   assembly_sample \
#   08_differential_coverage_mapping_design.tsv \
#   filtered_assemblies_directory \
#   cleaned_reads_directory \
#   output_directory

if [[ $# -ne 5 ]]; then
    echo "Usage: sbatch $0 <assembly_sample> <design.tsv> <assemblies_dir> <reads_dir> <output_dir>" >&2
    exit 1
fi

ASSEMBLY_SAMPLE="$1"
DESIGN_FILE="$2"
ASSEMBLY_DIR="$3"
READS_DIR="$4"
BASE_OUTPUT_DIR="$5"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
MEMORY="${BBMAP_MEMORY:-320G}"

BBMAP_MODULE="${BBMAP_MODULE:-bbmap/39.01}"
JAVA_MODULE="${JAVA_MODULE:-openjdk/21.0.3_9}"
SAMTOOLS_MODULE="${SAMTOOLS_MODULE:-samtools/1.17}"

if [[ ! -f "$DESIGN_FILE" ]]; then
    echo "ERROR: Differential-coverage design table not found: $DESIGN_FILE" >&2
    exit 1
fi

if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "ERROR: Filtered-assembly directory not found: $ASSEMBLY_DIR" >&2
    exit 1
fi

if [[ ! -d "$READS_DIR" ]]; then
    echo "ERROR: Cleaned-read directory not found: $READS_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

REFERENCE="${ASSEMBLY_DIR}/${ASSEMBLY_SAMPLE}_scaffolds_min1000.fasta"

if [[ ! -f "$REFERENCE" ]]; then
    echo "ERROR: Assembly reference not found: $REFERENCE" >&2
    exit 1
fi

module load "$BBMAP_MODULE"
module load "$JAVA_MODULE"
module load "$SAMTOOLS_MODULE"

mapfile -t READ_SAMPLES < <(
    awk -F '\t' -v assembly="$ASSEMBLY_SAMPLE" '
        NR == 1 && $1 == "assembly_sample" {
            next
        }

        $1 == assembly && $2 != "" {
            print $2
        }
    ' "$DESIGN_FILE"
)

if [[ ${#READ_SAMPLES[@]} -eq 0 ]]; then
    echo "ERROR: No read samples defined for assembly: $ASSEMBLY_SAMPLE" >&2
    exit 1
fi

OUTPUT_DIR="${BASE_OUTPUT_DIR}/${ASSEMBLY_SAMPLE}_differential_coverage"
mkdir -p "$OUTPUT_DIR"

echo "Assembly: $ASSEMBLY_SAMPLE"
echo "Reference: $REFERENCE"
echo "Read sets selected: ${#READ_SAMPLES[@]}"

for READ_SAMPLE in "${READ_SAMPLES[@]}"; do

    READ1="${READS_DIR}/${READ_SAMPLE}/${READ_SAMPLE}_PE1_trim_clean.fq.gz"
    READ2="${READS_DIR}/${READ_SAMPLE}/${READ_SAMPLE}_PE2_trim_clean.fq.gz"

    if [[ ! -f "$READ1" ]] || [[ ! -f "$READ2" ]]; then
        echo "WARNING: Cleaned reads missing for $READ_SAMPLE; skipping." >&2
        continue
    fi

    OUTPUT_PREFIX="${ASSEMBLY_SAMPLE}_to_${READ_SAMPLE}"

    UNSORTED_BAM="${OUTPUT_DIR}/${OUTPUT_PREFIX}_mapped.bam"
    SORTED_BAM="${OUTPUT_DIR}/${OUTPUT_PREFIX}_mapped_sorted.bam"
    COVERAGE_OUTPUT="${OUTPUT_DIR}/${OUTPUT_PREFIX}_coverage_stats.txt"

    echo "Mapping $READ_SAMPLE reads to $ASSEMBLY_SAMPLE assembly."

    bbmap.sh -Xmx"$MEMORY" nodisk \
        ref="$REFERENCE" \
        in1="$READ1" \
        in2="$READ2" \
        ambiguous=random \
        outm="$UNSORTED_BAM" \
        covstats="$COVERAGE_OUTPUT" \
        threads="$THREADS"

    samtools sort \
        "$UNSORTED_BAM" \
        --output "$SORTED_BAM" \
        --threads "$THREADS"

    samtools index \
        "$SORTED_BAM" \
        --threads "$THREADS"

    rm "$UNSORTED_BAM"

    echo "Completed: $ASSEMBLY_SAMPLE to $READ_SAMPLE"

done

echo "Differential coverage mapping completed for: $ASSEMBLY_SAMPLE"
echo "Output directory: $OUTPUT_DIR"
