#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_multimapping
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=20G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Maps multiple cleaned metagenomic read sets to one filtered assembly using
# BBMap, then sorts and indexes the resulting BAM files with SAMtools.
#
# INPUT
# Filtered assembly:
#   <assembly_sample>_scaffolds_min1000.fasta
# Generated by: scripts/analyses/02_metagenome_MAG_processing/06_filter_scaffolds_min1000.sh
#
# Cleaned paired-end reads:
#   <read_sample>/<read_sample>_PE1_trim_clean.fq.gz
#   <read_sample>/<read_sample>_PE2_trim_clean.fq.gz
# Generated by: scripts/analyses/02_metagenome_MAG_processing/03_bbduk_trimming_and_fastqc.sh
#
# Multimapping design table with two tab-separated columns:
#   assembly_sample    read_sample
#
# OUTPUT
# One sorted and indexed BAM file and one BBMap coverage-statistics table
# for each assembly–read combination.
#
# USAGE
# sbatch 08_multimapping_reads_to_assemblies.sh \
#   assembly_sample \
#   08_multimapping_design.tsv \
#   filtered_assemblies_directory \
#   cleaned_reads_directory \
#   output_directory

if [[ $# -ne 5 ]]; then
    echo "Usage:" >&2
    echo "  sbatch $0 <assembly_sample> <design.tsv> <assemblies_dir> <reads_dir> <output_dir>" >&2
    exit 1
fi

ASSEMBLY_SAMPLE="$1"
DESIGN_FILE="$2"
ASSEMBLY_DIR="$3"
READS_DIR="$4"
BASE_OUTPUT_DIR="$5"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
MEMORY="${BBMAP_MEMORY:-320G}"

BBMAP_MODULE="${BBMAP_MODULE:-bbmap/39.01}"
JAVA_MODULE="${JAVA_MODULE:-openjdk/21.0.3_9}"
SAMTOOLS_MODULE="${SAMTOOLS_MODULE:-samtools/1.17}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -f "$DESIGN_FILE" ]]; then
    echo "ERROR: Multimapping design table not found: $DESIGN_FILE" >&2
    exit 1
fi

if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "ERROR: Filtered-assembly directory not found: $ASSEMBLY_DIR" >&2
    exit 1
fi

if [[ ! -d "$READS_DIR" ]]; then
    echo "ERROR: Cleaned-read directory not found: $READS_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

REFERENCE="${ASSEMBLY_DIR}/${ASSEMBLY_SAMPLE}_scaffolds_min1000.fasta"

if [[ ! -f "$REFERENCE" ]]; then
    echo "ERROR: Assembly reference not found: $REFERENCE" >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

module load "$BBMAP_MODULE"
module load "$JAVA_MODULE"
module load "$SAMTOOLS_MODULE"

###############################################################################
# READ MULTIMAPPING DESIGN
###############################################################################

mapfile -t READ_SAMPLES < <(
    awk -F '\t' -v assembly="$ASSEMBLY_SAMPLE" '
        NR == 1 && $1 == "assembly_sample" {
            next
        }

        $1 == assembly && $2 != "" {
            print $2
        }
    ' "$DESIGN_FILE"
)

if [[ ${#READ_SAMPLES[@]} -eq 0 ]]; then
    echo "ERROR: No read samples found for assembly: $ASSEMBLY_SAMPLE" >&2
    exit 1
fi

OUTPUT_DIR="${BASE_OUTPUT_DIR}/${ASSEMBLY_SAMPLE}_multimapping"
mkdir -p "$OUTPUT_DIR"

###############################################################################
# MULTIMAPPING
###############################################################################

echo "Assembly: $ASSEMBLY_SAMPLE"
echo "Reference: $REFERENCE"
echo "Read sets: ${#READ_SAMPLES[@]}"

for READ_SAMPLE in "${READ_SAMPLES[@]}"; do

    READ1="${READS_DIR}/${READ_SAMPLE}/${READ_SAMPLE}_PE1_trim_clean.fq.gz"
    READ2="${READS_DIR}/${READ_SAMPLE}/${READ_SAMPLE}_PE2_trim_clean.fq.gz"

    if [[ ! -f "$READ1" ]] || [[ ! -f "$READ2" ]]; then
        echo "WARNING: Cleaned reads missing for $READ_SAMPLE; skipping." >&2
        continue
    fi

    BAM_OUTPUT="${OUTPUT_DIR}/${ASSEMBLY_SAMPLE}_to_${READ_SAMPLE}_mapped_sorted.bam"
    TEMP_SORTED_BAM="${BAM_OUTPUT}.tmp"
    COVERAGE_OUTPUT="${OUTPUT_DIR}/${ASSEMBLY_SAMPLE}_to_${READ_SAMPLE}_coverage_stats.txt"

    echo "Mapping $READ_SAMPLE reads to $ASSEMBLY_SAMPLE assembly."

    bbmap.sh -Xmx"$MEMORY" nodisk \
        ref="$REFERENCE" \
        in1="$READ1" \
        in2="$READ2" \
        ambiguous=random \
        outm="$BAM_OUTPUT" \
        covstats="$COVERAGE_OUTPUT" \
        threads="$THREADS"

    samtools sort \
        "$BAM_OUTPUT" \
        --output "$TEMP_SORTED_BAM" \
        --threads "$THREADS"

    mv "$TEMP_SORTED_BAM" "$BAM_OUTPUT"

    samtools index \
        "$BAM_OUTPUT" \
        --threads "$THREADS"

    echo "Completed: $ASSEMBLY_SAMPLE to $READ_SAMPLE"

done

echo "All multimapping analyses completed for: $ASSEMBLY_SAMPLE"
echo "Output directory: $OUTPUT_DIR"
