#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_MaxBin2
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Extracts all sample-specific mean scaffold-coverage profiles from MetaBAT2
# depth tables and performs genome binning with MaxBin2.
#
# INPUT
# Per-assembly depth.txt files.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/09_metabat2_binning.sh
#
# Filtered assemblies.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/06_filter_scaffolds_min1000.sh
#
# OUTPUT
# Per-assembly abundance files, abundance-file lists and MaxBin2 genome bins.
#
# USAGE
# sbatch 10_maxbin2_binning.sh \
#   metabat2_output_directory \
#   filtered_assemblies_directory \
#   output_directory

if [[ $# -ne 3 ]]; then
    echo "Usage: sbatch $0 <metabat2_directory> <assemblies_directory> <output_directory>" >&2
    exit 1
fi

METABAT_DIR="$1"
ASSEMBLY_DIR="$2"
OUTPUT_DIR="$3"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
MAXBIN_ENV="${MAXBIN_ENV:-maxbin2_2.2.7}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$METABAT_DIR" ]]; then
    echo "ERROR: MetaBAT2 output directory not found: $METABAT_DIR" >&2
    exit 1
fi

if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "ERROR: Filtered-assembly directory not found: $ASSEMBLY_DIR" >&2
    exit 1
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$MAXBIN_ENV"

###############################################################################
# LOCATE DEPTH TABLES
###############################################################################

mapfile -d '' DEPTH_FILES < <(
    find "$METABAT_DIR" \
        -mindepth 2 \
        -maxdepth 2 \
        -type f \
        -name "depth.txt" \
        -print0 |
        sort -z
)

if [[ ${#DEPTH_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No per-assembly depth.txt files found in: $METABAT_DIR" >&2
    exit 1
fi

###############################################################################
# MAXBIN2 BINNING
###############################################################################

for DEPTH_FILE in "${DEPTH_FILES[@]}"; do

    SAMPLE_DIR="$(dirname "$DEPTH_FILE")"
    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"

    ASSEMBLY_FASTA="${ASSEMBLY_DIR}/${SAMPLE_NAME}_scaffolds_min1000.fasta"

    if [[ ! -f "$ASSEMBLY_FASTA" ]]; then
        echo "WARNING: Assembly missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    SAMPLE_OUT="${OUTPUT_DIR}/${SAMPLE_NAME}"
    ABUNDANCE_DIR="${SAMPLE_OUT}/abundance_profiles"
    ABUNDANCE_LIST="${SAMPLE_OUT}/abundance_files.txt"

    mkdir -p "$SAMPLE_OUT"
    rm -rf "$ABUNDANCE_DIR"
    mkdir -p "$ABUNDANCE_DIR"

    : > "$ABUNDANCE_LIST"

    IFS=$'\t' read -r -a HEADER < "$DEPTH_FILE"

    COLUMN_COUNT="${#HEADER[@]}"

    if [[ "$COLUMN_COUNT" -lt 4 ]]; then
        echo "WARNING: No sample-specific coverage profiles found for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    echo "Processing: $SAMPLE_NAME"

    PROFILE_COUNT=0

    # jgi_summarize_bam_contig_depths output:
    #   column 1: contigName
    #   column 2: contigLen
    #   column 3: totalAvgDepth
    #   columns 4, 6, 8, ...: sample-specific mean coverage
    #   columns 5, 7, 9, ...: sample-specific coverage variance

    for ((COLUMN_NUMBER = 4; COLUMN_NUMBER <= COLUMN_COUNT; COLUMN_NUMBER += 2)); do

        HEADER_INDEX=$((COLUMN_NUMBER - 1))
        PROFILE_HEADER="${HEADER[$HEADER_INDEX]}"
        PROFILE_HEADER="${PROFILE_HEADER//$'\r'/}"

        PROFILE_NAME="$(basename "$PROFILE_HEADER")"
        PROFILE_NAME="${PROFILE_NAME%.bam}"

        PROFILE_NAME="$(
            printf '%s' "$PROFILE_NAME" |
                sed 's/[^A-Za-z0-9._-]/_/g'
        )"

        ABUNDANCE_FILE="${ABUNDANCE_DIR}/${PROFILE_NAME}_abundance.tsv"

        if [[ -e "$ABUNDANCE_FILE" ]]; then
            ABUNDANCE_FILE="${ABUNDANCE_DIR}/${PROFILE_NAME}_column${COLUMN_NUMBER}_abundance.tsv"
        fi

        # MaxBin2 abundance files must not contain a header.
        awk \
            -F '\t' \
            -v OFS='\t' \
            -v column="$COLUMN_NUMBER" \
            '
            NR > 1 {
                print $1, $column
            }
            ' \
            "$DEPTH_FILE" \
            > "$ABUNDANCE_FILE"

        if [[ ! -s "$ABUNDANCE_FILE" ]]; then
            echo "ERROR: Empty abundance file generated: $ABUNDANCE_FILE" >&2
            exit 1
        fi

        printf '%s\n' "$ABUNDANCE_FILE" >> "$ABUNDANCE_LIST"

        PROFILE_COUNT=$((PROFILE_COUNT + 1))

    done

    if [[ "$PROFILE_COUNT" -eq 0 ]]; then
        echo "WARNING: No abundance profiles extracted for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    echo "Running MaxBin2 with $PROFILE_COUNT abundance profiles."

    run_MaxBin.pl \
        -contig "$ASSEMBLY_FASTA" \
        -abund_list "$ABUNDANCE_LIST" \
        -out "$SAMPLE_OUT/maxbin2" \
        -thread "$THREADS"

    echo "MaxBin2 completed: $SAMPLE_NAME"

done

echo "All MaxBin2 binning analyses completed."
echo "Output directory: $OUTPUT_DIR"
