#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_MaxBin2
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Extracts all individual scaffold-coverage profiles from MetaBAT2 depth
# tables and performs genome binning with MaxBin2.
# INPUT
# Per-assembly depth.txt files and filtered assemblies.
# Generated by: 09_metabat2_binning.sh and
# 06_filter_scaffolds_min1000.sh
# OUTPUT
# Individual abundance profiles, abundance-file lists and MaxBin2 genome bins.
# USAGE
# sbatch 10_maxbin2_binning.sh \
#   metabat2_output_directory \
#   filtered_assemblies_directory \
#   output_directory

if [[ $# -ne 3 ]]; then
    echo "Usage: sbatch $0 <metabat2_directory> <assemblies_directory> <output_directory>" >&2
    exit 1
fi

METABAT_DIR="$1"
ASSEMBLY_DIR="$2"
OUTPUT_DIR="$3"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
MAXBIN_ENV="${MAXBIN_ENV:-maxbin2_2.2.7}"

if [[ ! -d "$METABAT_DIR" ]]; then
    echo "ERROR: MetaBAT2 directory not found: $METABAT_DIR" >&2
    exit 1
fi

if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "ERROR: Assembly directory not found: $ASSEMBLY_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$MAXBIN_ENV"

mapfile -d '' SAMPLE_DIRS < <(
    find "$METABAT_DIR" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -print0 |
        sort -z
)

if [[ ${#SAMPLE_DIRS[@]} -eq 0 ]]; then
    echo "ERROR: No sample directories found in: $METABAT_DIR" >&2
    exit 1
fi

for SAMPLE_DIR in "${SAMPLE_DIRS[@]}"; do

    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"

    ASSEMBLY_FASTA="${ASSEMBLY_DIR}/${SAMPLE_NAME}_scaffolds_min1000.fasta"
    DEPTH_FILE="${SAMPLE_DIR}/depth.txt"

    if [[ ! -f "$ASSEMBLY_FASTA" ]]; then
        echo "WARNING: Assembly missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    if [[ ! -f "$DEPTH_FILE" ]]; then
        echo "WARNING: depth.txt missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    SAMPLE_OUT="${OUTPUT_DIR}/${SAMPLE_NAME}"
    ABUNDANCE_DIR="${SAMPLE_OUT}/abundance_profiles"
    ABUNDANCE_LIST="${SAMPLE_OUT}/abundance_files.txt"

    mkdir -p "$ABUNDANCE_DIR"
    : > "$ABUNDANCE_LIST"

    IFS=$'\t' read -r -a HEADER < "$DEPTH_FILE"

    if [[ ${#HEADER[@]} -lt 4 ]]; then
        echo "WARNING: No sample-specific coverage columns in $DEPTH_FILE; skipping." >&2
        continue
    fi

    echo "Extracting abundance profiles: $SAMPLE_NAME"

    PROFILE_COUNT=0

    # depth.txt structure:
    # 1: contigName
    # 2: contigLen
    # 3: totalAvgDepth
    # 4: sample1 depth
    # 5: sample1 variance
    # 6: sample2 depth
    # 7: sample2 variance
    # ...

    for ((INDEX = 3; INDEX < ${#HEADER[@]}; INDEX += 2)); do

        COLUMN_NUMBER=$((INDEX + 1))
        PROFILE_HEADER="${HEADER[$INDEX]}"

        PROFILE_NAME="$(basename "$PROFILE_HEADER")"
        PROFILE_NAME="${PROFILE_NAME%.bam}"
        PROFILE_NAME="$(printf '%s' "$PROFILE_NAME" | tr -cs 'A-Za-z0-9._-' '_')"

        ABUNDANCE_FILE="${ABUNDANCE_DIR}/${PROFILE_NAME}_abundance.tsv"

        awk \
            -F '\t' \
            -v OFS='\t' \
            -v column="$COLUMN_NUMBER" \
            '
            NR == 1 {
                print $1, $column
                next
            }

            {
                print $1, $column
            }
            ' \
            "$DEPTH_FILE" \
            > "$ABUNDANCE_FILE"

        printf '%s\n' "$ABUNDANCE_FILE" >> "$ABUNDANCE_LIST"

        PROFILE_COUNT=$((PROFILE_COUNT + 1))

    done

    if [[ $PROFILE_COUNT -eq 0 ]]; then
        echo "WARNING: No abundance profiles extracted for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    echo "Running MaxBin2 with $PROFILE_COUNT abundance profiles: $SAMPLE_NAME"

    run_MaxBin.pl \
        -contig "$ASSEMBLY_FASTA" \
        -abund_list "$ABUNDANCE_LIST" \
        -out "$SAMPLE_OUT/maxbin2" \
        -thread "$THREADS"

    echo "MaxBin2 completed: $SAMPLE_NAME"

done

echo "All MaxBin2 analyses completed."
