#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_CONCOCT
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Generates differential scaffold-coverage tables and performs genome binning
# with CONCOCT using 10-kb subcontigs.
# INPUT
# Filtered assemblies and sorted BAM files from differential-coverage mapping.
# Generated by: 06_filter_scaffolds_min1000.sh and
# 08_generate_differential_coverage_profiles.sh
# OUTPUT
# Per-assembly CONCOCT coverage tables, clustering files and genome-bin FASTAs.
# USAGE
# sbatch 11_concoct_binning.sh \
#   differential_coverage_directory \
#   filtered_assemblies_directory \
#   output_directory

if [[ $# -ne 3 ]]; then
    echo "Usage: sbatch $0 <coverage_directory> <assemblies_directory> <output_directory>" >&2
    exit 1
fi

COVERAGE_DIR="$1"
ASSEMBLY_DIR="$2"
OUTPUT_DIR="$3"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
CONCOCT_ENV="${CONCOCT_ENV:-concoct_1.1.0}"

if [[ ! -d "$COVERAGE_DIR" ]]; then
    echo "ERROR: Coverage directory not found: $COVERAGE_DIR" >&2
    exit 1
fi

if [[ ! -d "$ASSEMBLY_DIR" ]]; then
    echo "ERROR: Assembly directory not found: $ASSEMBLY_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONCOCT_ENV"

mapfile -d '' SAMPLE_DIRS < <(
    find "$COVERAGE_DIR" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -name "*_differential_coverage" \
        -print0 |
        sort -z
)

if [[ ${#SAMPLE_DIRS[@]} -eq 0 ]]; then
    echo "ERROR: No differential-coverage directories found." >&2
    exit 1
fi

for SAMPLE_DIR in "${SAMPLE_DIRS[@]}"; do

    SAMPLE_NAME="$(
        basename "$SAMPLE_DIR" |
            sed 's/_differential_coverage$//'
    )"

    ASSEMBLY_FASTA="${ASSEMBLY_DIR}/${SAMPLE_NAME}_scaffolds_min1000.fasta"
    SAMPLE_OUT="${OUTPUT_DIR}/${SAMPLE_NAME}"

    if [[ ! -f "$ASSEMBLY_FASTA" ]]; then
        echo "WARNING: Assembly missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    mapfile -d '' BAM_FILES < <(
        find "$SAMPLE_DIR" \
            -maxdepth 1 \
            -type f \
            -name "*_mapped_sorted.bam" \
            -print0 |
            sort -z
    )

    if [[ ${#BAM_FILES[@]} -eq 0 ]]; then
        echo "WARNING: No BAM files found for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    mkdir -p "$SAMPLE_OUT/fasta_bins"

    CUT_FASTA="${SAMPLE_OUT}/scaffolds_10K.fa"
    BED_FILE="${SAMPLE_OUT}/scaffolds_10K.bed"
    COVERAGE_TABLE="${SAMPLE_OUT}/coverage_table.tsv"
    MERGED_CLUSTERING="${SAMPLE_OUT}/clustering_merged.csv"

    echo "Processing: $SAMPLE_NAME"
    echo "BAM profiles: ${#BAM_FILES[@]}"

    cut_up_fasta.py \
        "$ASSEMBLY_FASTA" \
        -c 10000 \
        -o 0 \
        --merge_last \
        -b "$BED_FILE" \
        > "$CUT_FASTA"

    concoct_coverage_table.py \
        "$BED_FILE" \
        "${BAM_FILES[@]}" \
        > "$COVERAGE_TABLE"

    concoct \
        --composition_file "$CUT_FASTA" \
        --coverage_file "$COVERAGE_TABLE" \
        -b "$SAMPLE_OUT/" \
        -t "$THREADS"

    merge_cutup_clustering.py \
        "${SAMPLE_OUT}/clustering_gt1000.csv" \
        > "$MERGED_CLUSTERING"

    extract_fasta_bins.py \
        "$ASSEMBLY_FASTA" \
        "$MERGED_CLUSTERING" \
        --output_path "$SAMPLE_OUT/fasta_bins"

    echo "CONCOCT completed: $SAMPLE_NAME"

done

echo "All CONCOCT analyses completed."
