#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_prepare_DASTool
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail
shopt -s nullglob

# DESCRIPTION
# Standardizes bin names from MetaBAT2, MaxBin2 and CONCOCT and generates
# the corresponding contig-to-bin tables required by DAS Tool.
# INPUT
# Per-sample binning output directories from MetaBAT2, MaxBin2 and CONCOCT.
# Generated by: 09_metabat2_binning.sh, 10_maxbin2_binning.sh and 11_concoct_binning.sh
# OUTPUT
# Standardized bin FASTA names and one contig-to-bin table per binner and sample.
# USAGE
# sbatch 12_prepare_bins_for_das_tool.sh \
#   metabat2_output_directory \
#   maxbin2_output_directory \
#   concoct_output_directory

if [[ $# -ne 3 ]]; then
    echo "Usage: sbatch $0 <metabat2_dir> <maxbin2_dir> <concoct_dir>" >&2
    exit 1
fi

METABAT2_DIR="$1"
MAXBIN2_DIR="$2"
CONCOCT_DIR="$3"

DASTOOL_ENV="${DASTOOL_ENV:-das_tool_1.1.7}"

for DIRECTORY in "$METABAT2_DIR" "$MAXBIN2_DIR" "$CONCOCT_DIR"; do
    if [[ ! -d "$DIRECTORY" ]]; then
        echo "ERROR: Directory not found: $DIRECTORY" >&2
        exit 1
    fi
done

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$DASTOOL_ENV"

if ! command -v Fasta_to_Contig2Bin.sh >/dev/null 2>&1; then
    echo "ERROR: Fasta_to_Contig2Bin.sh was not found." >&2
    exit 1
fi

###############################################################################
# METABAT2
###############################################################################

for SAMPLE_DIR in "$METABAT2_DIR"/*; do

    [[ -d "$SAMPLE_DIR" ]] || continue

    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"

    echo "Preparing MetaBAT2 bins: $SAMPLE_NAME"

    for BIN_FILE in "$SAMPLE_DIR"/bin.*.fa; do

        BIN_NAME="$(basename "$BIN_FILE")"
        NEW_NAME="${BIN_NAME/bin./metabat2_bin.}"

        mv "$BIN_FILE" "$SAMPLE_DIR/$NEW_NAME"

    done

    METABAT_BINS=("$SAMPLE_DIR"/metabat2_bin.*.fa)

    if [[ ${#METABAT_BINS[@]} -eq 0 ]]; then
        echo "WARNING: No MetaBAT2 bins found for $SAMPLE_NAME." >&2
        continue
    fi

    Fasta_to_Contig2Bin.sh \
        -i "$SAMPLE_DIR" \
        -e fa \
        > "$SAMPLE_DIR/metabat2_c2b.txt"

done

###############################################################################
# MAXBIN2
###############################################################################

for SAMPLE_DIR in "$MAXBIN2_DIR"/*; do

    [[ -d "$SAMPLE_DIR" ]] || continue

    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"

    echo "Preparing MaxBin2 bins: $SAMPLE_NAME"

    for BIN_FILE in "$SAMPLE_DIR"/maxbin2.*.fasta; do

        BIN_NAME="$(basename "$BIN_FILE")"
        BIN_SUFFIX="${BIN_NAME#maxbin2.}"
        BIN_SUFFIX="${BIN_SUFFIX%.fasta}"

        mv \
            "$BIN_FILE" \
            "$SAMPLE_DIR/maxbin2_bin.${BIN_SUFFIX}.fa"

    done

    MAXBIN_BINS=("$SAMPLE_DIR"/maxbin2_bin.*.fa)

    if [[ ${#MAXBIN_BINS[@]} -eq 0 ]]; then
        echo "WARNING: No MaxBin2 bins found for $SAMPLE_NAME." >&2
        continue
    fi

    Fasta_to_Contig2Bin.sh \
        -i "$SAMPLE_DIR" \
        -e fa \
        > "$SAMPLE_DIR/maxbin2_c2b.txt"

done

###############################################################################
# CONCOCT
###############################################################################

for SAMPLE_DIR in "$CONCOCT_DIR"/*; do

    [[ -d "$SAMPLE_DIR" ]] || continue

    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"
    CONCOCT_BIN_DIR="$SAMPLE_DIR/fasta_bins"

    if [[ ! -d "$CONCOCT_BIN_DIR" ]]; then
        echo "WARNING: CONCOCT fasta_bins directory missing for $SAMPLE_NAME." >&2
        continue
    fi

    echo "Preparing CONCOCT bins: $SAMPLE_NAME"

    for BIN_FILE in "$CONCOCT_BIN_DIR"/*.fa; do

        BIN_NAME="$(basename "$BIN_FILE")"

        if [[ "$BIN_NAME" == concoct_bin.* ]]; then
            continue
        fi

        mv \
            "$BIN_FILE" \
            "$CONCOCT_BIN_DIR/concoct_bin.${BIN_NAME}"

    done

    CONCOCT_BINS=("$CONCOCT_BIN_DIR"/concoct_bin.*.fa)

    if [[ ${#CONCOCT_BINS[@]} -eq 0 ]]; then
        echo "WARNING: No CONCOCT bins found for $SAMPLE_NAME." >&2
        continue
    fi

    Fasta_to_Contig2Bin.sh \
        -i "$CONCOCT_BIN_DIR" \
        -e fa \
        > "$CONCOCT_BIN_DIR/concoct_c2b.txt"

done

echo "Preparation of binning outputs for DAS Tool completed successfully."
