#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_DASTool
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Integrates the MetaBAT2, MaxBin2 and CONCOCT binning results and selects
# non-redundant genome bins using DAS Tool.
#
# INPUT
# Filtered assemblies and per-sample contig-to-bin tables for the three binners.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/12_prepare_bins_for_das_tool.sh
#
# OUTPUT
# Per-sample DAS Tool bin evaluations, selected genome bins and unbinned
# scaffold FASTA files.
#
# USAGE
# sbatch 13_das_tool_bin_selection.sh \
#   filtered_assemblies_directory \
#   metabat2_output_directory \
#   maxbin2_output_directory \
#   concoct_output_directory \
#   output_directory

if [[ $# -ne 5 ]]; then
    echo "Usage: sbatch $0 <assemblies_dir> <metabat2_dir> <maxbin2_dir> <concoct_dir> <output_dir>" >&2
    exit 1
fi

ASSEMBLY_DIR="$1"
METABAT2_DIR="$2"
MAXBIN2_DIR="$3"
CONCOCT_DIR="$4"
OUTPUT_DIR="$5"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
DASTOOL_ENV="${DASTOOL_ENV:-das_tool_1.1.7}"

###############################################################################
# INPUT VALIDATION
###############################################################################

for DIRECTORY in \
    "$ASSEMBLY_DIR" \
    "$METABAT2_DIR" \
    "$MAXBIN2_DIR" \
    "$CONCOCT_DIR"
do
    if [[ ! -d "$DIRECTORY" ]]; then
        echo "ERROR: Directory not found: $DIRECTORY" >&2
        exit 1
    fi
done

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$DASTOOL_ENV"

###############################################################################
# LOCATE ASSEMBLIES
###############################################################################

mapfile -d '' ASSEMBLY_FILES < <(
    find "$ASSEMBLY_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*_scaffolds_min1000.fasta" \
        -print0 |
        sort -z
)

if [[ ${#ASSEMBLY_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No *_scaffolds_min1000.fasta files found in: $ASSEMBLY_DIR" >&2
    exit 1
fi

###############################################################################
# DAS TOOL
###############################################################################

for ASSEMBLY_FASTA in "${ASSEMBLY_FILES[@]}"; do

    ASSEMBLY_BASENAME="$(basename "$ASSEMBLY_FASTA")"
    SAMPLE_NAME="${ASSEMBLY_BASENAME%_scaffolds_min1000.fasta}"

    METABAT2_C2B="${METABAT2_DIR}/${SAMPLE_NAME}/metabat2_c2b.txt"
    MAXBIN2_C2B="${MAXBIN2_DIR}/${SAMPLE_NAME}/maxbin2_c2b.txt"
    CONCOCT_C2B="${CONCOCT_DIR}/${SAMPLE_NAME}/fasta_bins/concoct_c2b.txt"

    if [[ ! -s "$METABAT2_C2B" ]]; then
        echo "WARNING: MetaBAT2 contig-to-bin table missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    if [[ ! -s "$MAXBIN2_C2B" ]]; then
        echo "WARNING: MaxBin2 contig-to-bin table missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    if [[ ! -s "$CONCOCT_C2B" ]]; then
        echo "WARNING: CONCOCT contig-to-bin table missing for $SAMPLE_NAME; skipping." >&2
        continue
    fi

    SAMPLE_OUTPUT="${OUTPUT_DIR}/${SAMPLE_NAME}"
    OUTPUT_PREFIX="${SAMPLE_OUTPUT}/${SAMPLE_NAME}"

    mkdir -p "$SAMPLE_OUTPUT"

    cp "$METABAT2_C2B" "$SAMPLE_OUTPUT/metabat2_c2b.txt"
    cp "$MAXBIN2_C2B" "$SAMPLE_OUTPUT/maxbin2_c2b.txt"
    cp "$CONCOCT_C2B" "$SAMPLE_OUTPUT/concoct_c2b.txt"

    echo "Running DAS Tool: $SAMPLE_NAME"

    DAS_Tool \
        -i "${SAMPLE_OUTPUT}/metabat2_c2b.txt,${SAMPLE_OUTPUT}/maxbin2_c2b.txt,${SAMPLE_OUTPUT}/concoct_c2b.txt" \
        -c "$ASSEMBLY_FASTA" \
        -o "$OUTPUT_PREFIX" \
        -l metabat2,maxbin2,concoct \
        --write_bins \
        --write_bin_evals \
        --write_unbinned \
        -t "$THREADS" \
        --debug

    echo "DAS Tool completed: $SAMPLE_NAME"

done

echo "All DAS Tool analyses completed."
echo "Output directory: $OUTPUT_DIR"
