#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_dRep_species_level
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail
shopt -s nullglob

# DESCRIPTION
# Collects DAS Tool-selected bins and performs species-level dereplication
# using dRep with a secondary ANI threshold of 95%.
#
# INPUT
# Per-sample directories containing <sample>_DASTool_bins.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/13_das_tool_bin_selection.sh
#
# OUTPUT
# Uniquely named input bins and the complete dRep dereplication directory.
#
# USAGE
# sbatch 14_drep_species_level_dereplication.sh \
#   das_tool_output_directory \
#   working_directory

if [[ $# -ne 2 ]]; then
    echo "Usage: sbatch $0 <das_tool_output_directory> <working_directory>" >&2
    exit 1
fi

DAS_TOOL_DIR="$1"
WORK_DIR="$2"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
DREP_ENV="${DREP_ENV:-drep_3.4.5}"

ALL_BINS_DIR="${WORK_DIR}/all_das_tool_bins"
DREP_OUTPUT="${WORK_DIR}/drep_species_level"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$DAS_TOOL_DIR" ]]; then
    echo "ERROR: DAS Tool output directory not found: $DAS_TOOL_DIR" >&2
    exit 1
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

if [[ -e "$DREP_OUTPUT" ]]; then
    echo "ERROR: dRep output directory already exists: $DREP_OUTPUT" >&2
    echo "Remove it or provide a different working directory." >&2
    exit 1
fi

mkdir -p "$ALL_BINS_DIR"

# Remove bins from an incomplete previous collection step.
rm -f "$ALL_BINS_DIR"/*.fa

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$DREP_ENV"

###############################################################################
# COLLECT DAS TOOL-SELECTED BINS
###############################################################################

mapfile -d '' BIN_DIRECTORIES < <(
    find "$DAS_TOOL_DIR" \
        -mindepth 2 \
        -maxdepth 2 \
        -type d \
        -name "*_DASTool_bins" \
        -print0 |
        sort -z
)

if [[ ${#BIN_DIRECTORIES[@]} -eq 0 ]]; then
    echo "ERROR: No *_DASTool_bins directories found in: $DAS_TOOL_DIR" >&2
    exit 1
fi

BIN_COUNT=0

for BIN_DIRECTORY in "${BIN_DIRECTORIES[@]}"; do

    SAMPLE_NAME="$(basename "$(dirname "$BIN_DIRECTORY")")"

    echo "Collecting bins: $SAMPLE_NAME"

    BIN_FILES=("$BIN_DIRECTORY"/*.fa)

    if [[ ${#BIN_FILES[@]} -eq 0 ]]; then
        echo "WARNING: No FASTA bins found for $SAMPLE_NAME." >&2
        continue
    fi

    for BIN_FILE in "${BIN_FILES[@]}"; do

        BIN_NAME="$(basename "$BIN_FILE")"

        if [[ "$BIN_NAME" == "unbinned.fa" ]]; then
            continue
        fi

        OUTPUT_BIN="${ALL_BINS_DIR}/${SAMPLE_NAME}_${BIN_NAME}"

        if [[ -e "$OUTPUT_BIN" ]]; then
            echo "ERROR: Duplicate output bin name: $OUTPUT_BIN" >&2
            exit 1
        fi

        cp "$BIN_FILE" "$OUTPUT_BIN"

        BIN_COUNT=$((BIN_COUNT + 1))

    done

done

if [[ "$BIN_COUNT" -eq 0 ]]; then
    echo "ERROR: No DAS Tool-selected bins were collected." >&2
    exit 1
fi

echo "DAS Tool-selected bins collected: $BIN_COUNT"

###############################################################################
# DREP SPECIES-LEVEL DEREPLICATION
###############################################################################

BIN_FILES=("$ALL_BINS_DIR"/*.fa)

echo "Starting dRep species-level dereplication."

dRep dereplicate \
    "$DREP_OUTPUT" \
    -g "${BIN_FILES[@]}" \
    -p "$THREADS" \
    -pa 0.95 \
    -sa 0.95 \
    -comp 50 \
    -con 10

echo "dRep dereplication completed successfully."
echo "Collected bins: $ALL_BINS_DIR"
echo "dRep output: $DREP_OUTPUT"
echo "Representative MAGs: $DREP_OUTPUT/dereplicated_genomes"
