#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_CheckM2
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=24G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Estimates completeness and contamination of species-level dereplicated MAGs
# using CheckM2.
# INPUT
# Directory containing species-level representative MAGs in FASTA format.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/14_drep_species_level_dereplication.sh
# OUTPUT
# CheckM2 output directory containing quality_report.tsv.
# USAGE
# sbatch 15_checkm2_quality_assessment.sh \
#   dereplicated_genomes_directory \
#   output_directory \
#   [expected_number_of_genomes]

if [[ $# -lt 2 || $# -gt 3 ]]; then
    echo "Usage: sbatch $0 <dereplicated_genomes_directory> <output_directory> [expected_genomes]" >&2
    exit 1
fi

INPUT_DIR="$1"
OUTPUT_DIR="$2"
EXPECTED_GENOMES="${3:-1081}"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
CHECKM2_ENV="${CHECKM2_ENV:-checkM2_1.0.2}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$INPUT_DIR" ]]; then
    echo "ERROR: Input directory does not exist: $INPUT_DIR" >&2
    exit 1
fi

if ! [[ "$EXPECTED_GENOMES" =~ ^[0-9]+$ ]]; then
    echo "ERROR: Expected genome count must be a non-negative integer." >&2
    exit 1
fi

mapfile -d '' GENOME_FILES < <(
    find "$INPUT_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.fa" \
        -print0 |
        sort -z
)

N_GENOMES="${#GENOME_FILES[@]}"

if [[ "$N_GENOMES" -eq 0 ]]; then
    echo "ERROR: No .fa genome files found in: $INPUT_DIR" >&2
    exit 1
fi

if [[ "$N_GENOMES" -ne "$EXPECTED_GENOMES" ]]; then
    echo "WARNING: Expected $EXPECTED_GENOMES genomes, but found $N_GENOMES." >&2
fi

if [[ -e "$OUTPUT_DIR" ]]; then
    echo "ERROR: Output directory already exists: $OUTPUT_DIR" >&2
    echo "Remove it or provide a new output directory." >&2
    exit 1
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CHECKM2_ENV"

###############################################################################
# CHECKM2 QUALITY ASSESSMENT
###############################################################################

echo "============================================================"
echo "Starting CheckM2"
echo "Date: $(date)"
echo "Host: $(hostname)"
echo "Input directory: $INPUT_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "Input genomes: $N_GENOMES"
echo "Threads: $THREADS"
echo "============================================================"

checkm2 predict \
    --threads "$THREADS" \
    --input "$INPUT_DIR" \
    --output-directory "$OUTPUT_DIR" \
    -x fa

###############################################################################
# OUTPUT VALIDATION
###############################################################################

QUALITY_REPORT="${OUTPUT_DIR}/quality_report.tsv"

if [[ ! -s "$QUALITY_REPORT" ]]; then
    echo "ERROR: quality_report.tsv was not created or is empty." >&2
    exit 1
fi

N_RESULTS="$(
    awk '
        NR > 1 {
            count++
        }

        END {
            print count + 0
        }
    ' "$QUALITY_REPORT"
)"

if [[ "$N_RESULTS" -ne "$N_GENOMES" ]]; then
    echo "WARNING: CheckM2 received $N_GENOMES genomes but reported $N_RESULTS results." >&2
fi

echo "============================================================"
echo "CheckM2 completed successfully."
echo "Date: $(date)"
echo "Input genomes: $N_GENOMES"
echo "Genomes in quality report: $N_RESULTS"
echo "Quality report: $QUALITY_REPORT"
echo "============================================================"
