#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_GTDBTk_R232
#SBATCH --cpus-per-task=25
#SBATCH --mem-per-cpu=30G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Assigns bacterial and archaeal taxonomy to species-level dereplicated MAGs
# using GTDB-Tk v2.7.2 and GTDB release R232.
#
# INPUT
# Species-level representative MAGs in FASTA format and the GTDB R232 database.
# Generated by: scripts/analyses/02_metagenome_MAG_processing/14_drep_species_level_dereplication.sh
#
# OUTPUT
# GTDB-Tk R232 classification directory, including bacterial and archaeal
# summary tables.
#
# USAGE
# sbatch 16b_gtdbtk_R232_taxonomic_classification.sh \
#   dereplicated_genomes_directory \
#   output_directory \
#   GTDB_R232_database_directory \
#   [expected_number_of_genomes]

if [[ $# -lt 3 || $# -gt 4 ]]; then
    echo "Usage: sbatch $0 <genome_dir> <output_dir> <GTDB_database_dir> [expected_genomes]" >&2
    exit 1
fi

GENOME_DIR="$1"
OUTPUT_DIR="$2"
GTDB_DATABASE="$3"
EXPECTED_GENOMES="${4:-1081}"

THREADS="${SLURM_CPUS_PER_TASK:-25}"
GTDBTK_ENV="${GTDBTK_ENV:-gtdbtk-2.7.2_py311}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$GENOME_DIR" ]]; then
    echo "ERROR: Genome directory not found: $GENOME_DIR" >&2
    exit 1
fi

if [[ ! -d "$GTDB_DATABASE" ]]; then
    echo "ERROR: GTDB R232 database directory not found: $GTDB_DATABASE" >&2
    exit 1
fi

if ! [[ "$EXPECTED_GENOMES" =~ ^[0-9]+$ ]]; then
    echo "ERROR: Expected genome count must be a non-negative integer." >&2
    exit 1
fi

mapfile -d '' GENOME_FILES < <(
    find "$GENOME_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.fa" \
        -print0 |
        sort -z
)

N_GENOMES="${#GENOME_FILES[@]}"

if [[ "$N_GENOMES" -eq 0 ]]; then
    echo "ERROR: No .fa genome files found in: $GENOME_DIR" >&2
    exit 1
fi

if [[ "$N_GENOMES" -ne "$EXPECTED_GENOMES" ]]; then
    echo "WARNING: Expected $EXPECTED_GENOMES genomes, but found $N_GENOMES." >&2
fi

if [[ -e "$OUTPUT_DIR" ]]; then
    echo "ERROR: Output directory already exists: $OUTPUT_DIR" >&2
    exit 1
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$GTDBTK_ENV"

export GTDBTK_DATA_PATH="$GTDB_DATABASE"

###############################################################################
# VERIFY DATABASE
###############################################################################

echo "Checking GTDB-Tk installation and GTDB R232 database."

gtdbtk check_install \
    --db_version 232

###############################################################################
# GTDB-TK CLASSIFICATION
###############################################################################

echo "============================================================"
echo "Starting GTDB-Tk R232 classification"
echo "Date: $(date)"
echo "Input genomes: $N_GENOMES"
echo "Database: $GTDBTK_DATA_PATH"
echo "Threads: $THREADS"
echo "============================================================"

gtdbtk classify_wf \
    --genome_dir "$GENOME_DIR" \
    --extension fa \
    --out_dir "$OUTPUT_DIR" \
    --cpus "$THREADS"

###############################################################################
# OUTPUT VALIDATION
###############################################################################

BAC_REPORT="${OUTPUT_DIR}/gtdbtk.bac120.summary.tsv"
ARC_REPORT="${OUTPUT_DIR}/gtdbtk.ar53.summary.tsv"

if [[ -s "$BAC_REPORT" ]]; then
    N_BACTERIA="$(awk 'NR > 1 {count++} END {print count + 0}' "$BAC_REPORT")"
else
    N_BACTERIA=0
fi

if [[ -s "$ARC_REPORT" ]]; then
    N_ARCHAEA="$(awk 'NR > 1 {count++} END {print count + 0}' "$ARC_REPORT")"
else
    N_ARCHAEA=0
fi

N_CLASSIFIED=$((N_BACTERIA + N_ARCHAEA))

if [[ "$N_CLASSIFIED" -ne "$N_GENOMES" ]]; then
    echo "WARNING: $N_GENOMES genomes were supplied, but $N_CLASSIFIED occur in the summary tables." >&2
fi

echo "============================================================"
echo "GTDB-Tk R232 completed successfully."
echo "Bacterial genomes: $N_BACTERIA"
echo "Archaeal genomes: $N_ARCHAEA"
echo "Total classified genomes: $N_CLASSIFIED"
echo "Output directory: $OUTPUT_DIR"
echo "============================================================"
