# DESCRIPTION
# Compares the high-quality MAG subset selected using the CheckM quality
# estimates generated by dRep against GTDB representative genomes using
# GTDB-Tk ani_rep with GTDB releases R220 and R232.
#
# INPUT
# GTDB-Tk batch file containing 472 high-quality MAGs selected from the
# dRep CheckM quality estimates.
#
# Generated from:
# scripts/analyses/02_metagenome_MAG_processing/
# 14_drep_species_level_dereplication.sh
#
# The underlying dRep quality estimates are stored in:
# data_tables/Widb.csv
#
# OUTPUT
# Separate GTDB-Tk ani_rep result directories for GTDB releases R220 and R232.
#
# USAGE
# sbatch 17_gtdbtk_ani_rep_HQ_MAGs_R220_R232.sh \
#   HQ_MAGs_CheckM_batchfile.tsv \
#   output_directory \
#   GTDB_R220_database_directory \
#   GTDB_R232_database_directory \
#   [expected_number_of_HQ_MAGs]
###############################################################################
# ARGUMENTS
###############################################################################

if [[ $# -lt 4 || $# -gt 5 ]]; then
    echo "Usage:" >&2
    echo "  sbatch $0 <batchfile.tsv> <output_dir> <R220_db> <R232_db> [expected_genomes]" >&2
    exit 1
fi

BATCH_FILE="$1"
OUTPUT_BASE="$2"
GTDB_R220_DATABASE="$3"
GTDB_R232_DATABASE="$4"
EXPECTED_GENOMES="${5:-472}"

THREADS="${SLURM_CPUS_PER_TASK:-4}"

GTDB_R220_ENV="${GTDB_R220_ENV:-gtdb-tk_2.4.0}"
GTDB_R232_ENV="${GTDB_R232_ENV:-gtdbtk-2.7.2_py311}"

R220_OUTPUT="${OUTPUT_BASE}/ani_rep_GTDB_R220_HQ_MAGs"
R232_OUTPUT="${OUTPUT_BASE}/ani_rep_GTDB_R232_HQ_MAGs"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -s "$BATCH_FILE" ]]; then
    echo "ERROR: GTDB-Tk batch file not found or empty: $BATCH_FILE" >&2
    exit 1
fi

if [[ ! -d "$GTDB_R220_DATABASE" ]]; then
    echo "ERROR: GTDB R220 database directory not found: $GTDB_R220_DATABASE" >&2
    exit 1
fi

if [[ ! -d "$GTDB_R232_DATABASE" ]]; then
    echo "ERROR: GTDB R232 database directory not found: $GTDB_R232_DATABASE" >&2
    exit 1
fi

if ! [[ "$EXPECTED_GENOMES" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: Expected genome count must be a positive integer." >&2
    exit 1
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

N_GENOMES="$(
    awk '
        NF > 0 && $1 !~ /^#/ {
            count++
        }

        END {
            print count + 0
        }
    ' "$BATCH_FILE"
)"

if [[ "$N_GENOMES" -eq 0 ]]; then
    echo "ERROR: No genomes were found in the batch file." >&2
    exit 1
fi

if [[ "$N_GENOMES" -ne "$EXPECTED_GENOMES" ]]; then
    echo "WARNING: Expected $EXPECTED_GENOMES HQ MAGs, but the batch file contains $N_GENOMES." >&2
fi

###############################################################################
# CHECK GENOME PATHS IN BATCH FILE
###############################################################################

MISSING_GENOMES=0

while IFS=$'\t' read -r GENOME_PATH GENOME_ID TRANSLATION_TABLE; do

    [[ -n "$GENOME_PATH" ]] || continue
    [[ "$GENOME_PATH" == \#* ]] && continue

    if [[ ! -f "$GENOME_PATH" ]]; then
        echo "ERROR: Genome listed in batch file was not found: $GENOME_PATH" >&2
        MISSING_GENOMES=$((MISSING_GENOMES + 1))
    fi

done < "$BATCH_FILE"

if [[ "$MISSING_GENOMES" -gt 0 ]]; then
    echo "ERROR: $MISSING_GENOMES genome files listed in the batch file are missing." >&2
    exit 1
fi

###############################################################################
# OUTPUT VALIDATION
###############################################################################

mkdir -p "$OUTPUT_BASE"

for OUTPUT_DIR in "$R220_OUTPUT" "$R232_OUTPUT"; do

    if [[ -e "$OUTPUT_DIR" ]]; then
        echo "ERROR: Output directory already exists: $OUTPUT_DIR" >&2
        echo "Remove it or choose a different output directory." >&2
        exit 1
    fi

done

###############################################################################
# CONDA INITIALIZATION
###############################################################################

CONDA_SH="$(conda info --base)/etc/profile.d/conda.sh"

if [[ ! -f "$CONDA_SH" ]]; then
    echo "ERROR: Conda initialization script not found: $CONDA_SH" >&2
    exit 1
fi

source "$CONDA_SH"

###############################################################################
# FUNCTION: RUN ANI_REP
###############################################################################

run_ani_rep() {

    local environment_name="$1"
    local database_directory="$2"
    local database_release="$3"
    local output_directory="$4"

    echo "============================================================"
    echo "Starting GTDB-Tk ani_rep with GTDB ${database_release}"
    echo "Date: $(date)"
    echo "Environment: ${environment_name}"
    echo "Database: ${database_directory}"
    echo "Input genomes: ${N_GENOMES}"
    echo "Output: ${output_directory}"
    echo "Threads: ${THREADS}"
    echo "============================================================"

    conda activate "$environment_name"

    export GTDBTK_DATA_PATH="$database_directory"

    echo "GTDB-Tk version:"
    gtdbtk --version

    if ! gtdbtk ani_rep --help 2>&1 | grep -q -- "--batchfile"; then
        echo "ERROR: ani_rep in $environment_name does not support --batchfile." >&2
        exit 1
    fi

    gtdbtk check_install \
        --db_version "$database_release"

    gtdbtk ani_rep \
        --batchfile "$BATCH_FILE" \
        --out_dir "$output_directory" \
        --cpus "$THREADS"

    local closest_report="${output_directory}/gtdbtk.ani_closest.tsv"
    local summary_report="${output_directory}/gtdbtk.ani_summary.tsv"

    if [[ ! -s "$closest_report" ]]; then
        echo "ERROR: ani_rep closest-representative report was not generated:" >&2
        echo "$closest_report" >&2
        exit 1
    fi

    if [[ ! -s "$summary_report" ]]; then
        echo "ERROR: ani_rep summary report was not generated:" >&2
        echo "$summary_report" >&2
        exit 1
    fi

    local n_closest

    n_closest="$(
        awk '
            NR > 1 {
                count++
            }

            END {
                print count + 0
            }
        ' "$closest_report"
    )"

    if [[ "$n_closest" -ne "$N_GENOMES" ]]; then
        echo "WARNING: $N_GENOMES genomes were supplied, but $n_closest rows occur in gtdbtk.ani_closest.tsv." >&2
    fi

    echo "GTDB ${database_release} ani_rep completed."
    echo "Closest-representative report: $closest_report"
    echo "ANI summary report: $summary_report"

    conda deactivate
}

###############################################################################
# RUN GTDB R220 AND R232
###############################################################################

run_ani_rep \
    "$GTDB_R220_ENV" \
    "$GTDB_R220_DATABASE" \
    "220" \
    "$R220_OUTPUT"

run_ani_rep \
    "$GTDB_R232_ENV" \
    "$GTDB_R232_DATABASE" \
    "232" \
    "$R232_OUTPUT"

###############################################################################
# FINAL SUMMARY
###############################################################################

echo "============================================================"
echo "Both ani_rep analyses completed successfully."
echo "Input HQ MAGs: $N_GENOMES"
echo "GTDB R220 results: $R220_OUTPUT"
echo "GTDB R232 results: $R232_OUTPUT"
echo "============================================================"
