#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_CoverM_MAGs
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Estimates the abundance of all species-level dereplicated MAGs in each
# metagenomic sample using CoverM.
#
# INPUT
# Cleaned paired-end metagenomic reads.
# Generated by:
# scripts/analyses/02_metagenome_MAG_processing/03_bbduk_trimming_and_fastqc.sh
#
# Species-level dereplicated MAGs.
# Generated by:
# scripts/analyses/02_metagenome_MAG_processing/14_drep_species_level_dereplication.sh
#
# OUTPUT
# Per-sample CoverM genome-abundance tables, cached BAM files and error logs.
#
# USAGE
# sbatch 18_coverm_mag_abundance.sh \
#   cleaned_reads_directory \
#   dereplicated_MAGs_directory \
#   output_directory \
#   [expected_number_of_MAGs]

###############################################################################
# ARGUMENTS
###############################################################################

if [[ $# -lt 3 || $# -gt 4 ]]; then
    echo "Usage: sbatch $0 <reads_dir> <MAG_dir> <output_dir> [expected_MAGs]" >&2
    exit 1
fi

READS_DIR="$1"
MAG_DIR="$2"
OUTPUT_DIR="$3"
EXPECTED_MAGS="${4:-1081}"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
COVERM_ENV="${COVERM_ENV:-coverm_0.6.1}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$READS_DIR" ]]; then
    echo "ERROR: Cleaned-read directory not found: $READS_DIR" >&2
    exit 1
fi

if [[ ! -d "$MAG_DIR" ]]; then
    echo "ERROR: Dereplicated-MAG directory not found: $MAG_DIR" >&2
    exit 1
fi

if ! [[ "$EXPECTED_MAGS" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: Expected MAG count must be a positive integer." >&2
    exit 1
fi

mapfile -d '' MAG_FILES < <(
    find "$MAG_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.fa" \
        -print0 |
        sort -z
)

N_MAGS="${#MAG_FILES[@]}"

if [[ "$N_MAGS" -eq 0 ]]; then
    echo "ERROR: No .fa MAG files found in: $MAG_DIR" >&2
    exit 1
fi

if [[ "$N_MAGS" -ne "$EXPECTED_MAGS" ]]; then
    echo "WARNING: Expected $EXPECTED_MAGS MAGs, but found $N_MAGS." >&2
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$COVERM_ENV"

###############################################################################
# LOCATE METAGENOMIC SAMPLES
###############################################################################

mapfile -d '' SAMPLE_DIRS < <(
    find "$READS_DIR" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -print0 |
        sort -z
)

if [[ ${#SAMPLE_DIRS[@]} -eq 0 ]]; then
    echo "ERROR: No sample directories found in: $READS_DIR" >&2
    exit 1
fi

###############################################################################
# COVERM GENOME ABUNDANCE
###############################################################################

PROCESSED_SAMPLES=0
SKIPPED_SAMPLES=0

for SAMPLE_DIR in "${SAMPLE_DIRS[@]}"; do

    SAMPLE_NAME="$(basename "$SAMPLE_DIR")"

    PE1="${SAMPLE_DIR}/${SAMPLE_NAME}_PE1_trim_clean.fq.gz"
    PE2="${SAMPLE_DIR}/${SAMPLE_NAME}_PE2_trim_clean.fq.gz"

    if [[ ! -f "$PE1" ]] || [[ ! -f "$PE2" ]]; then
        echo "WARNING: Cleaned paired-end reads missing for $SAMPLE_NAME; skipping." >&2
        SKIPPED_SAMPLES=$((SKIPPED_SAMPLES + 1))
        continue
    fi

    SAMPLE_OUTPUT="${OUTPUT_DIR}/${SAMPLE_NAME}"
    CACHE_DIR="${SAMPLE_OUTPUT}/cache"
    COVERM_OUTPUT="${SAMPLE_OUTPUT}/${SAMPLE_NAME}_coverm_raw_output.tsv"
    ERROR_LOG="${SAMPLE_OUTPUT}/${SAMPLE_NAME}_coverm_error.log"

    mkdir -p "$CACHE_DIR"

    if [[ -s "$COVERM_OUTPUT" ]]; then
        echo "ERROR: CoverM output already exists: $COVERM_OUTPUT" >&2
        exit 1
    fi

    echo "============================================================"
    echo "Processing sample: $SAMPLE_NAME"
    echo "MAGs: $N_MAGS"
    echo "Threads: $THREADS"
    echo "============================================================"

    coverm genome \
        --coupled "$PE1" "$PE2" \
        --genome-fasta-directory "$MAG_DIR" \
        --genome-fasta-extension fa \
        --discard-unmapped \
        --output-file "$COVERM_OUTPUT" \
        --bam-file-cache-directory "$CACHE_DIR" \
        --threads "$THREADS" \
        2> "$ERROR_LOG"

    if [[ ! -s "$COVERM_OUTPUT" ]]; then
        echo "ERROR: CoverM output was not generated for $SAMPLE_NAME." >&2
        exit 1
    fi

    PROCESSED_SAMPLES=$((PROCESSED_SAMPLES + 1))

    echo "CoverM completed: $SAMPLE_NAME"

done

echo "============================================================"
echo "CoverM analyses completed."
echo "Processed samples: $PROCESSED_SAMPLES"
echo "Skipped samples: $SKIPPED_SAMPLES"
echo "MAGs profiled per sample: $N_MAGS"
echo "Output directory: $OUTPUT_DIR"
echo "============================================================"
