#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_DRAM
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Performs functional annotation and metabolic distillation of dereplicated
# MAGs using DRAM, GTDB-Tk taxonomy and dRep/CheckM quality estimates.
#
# INPUT
# Directory containing MAGs in FASTA format, GTDB-Tk taxonomy table and
# dRep CheckM quality table.
# Generated by: 14_drep_species_level_dereplication.sh and
# 16_gtdbtk_taxonomic_classification.sh
#
# OUTPUT
# DRAM annotations, predicted genes, annotation summaries and distilled
# metabolic information.
#
# USAGE
# sbatch 19_dram_mag_annotation.sh \
#   MAG_directory \
#   output_directory \
#   GTDB_taxonomy.tsv \
#   dRep_CheckM_quality.csv \
#   [expected_number_of_MAGs]

if [[ $# -lt 4 || $# -gt 5 ]]; then
    echo "Usage: sbatch $0 <MAG_dir> <output_dir> <taxonomy.tsv> <quality.csv> [expected_MAGs]" >&2
    exit 1
fi

MAG_DIR="$1"
OUTPUT_DIR="$2"
TAXONOMY_TSV="$3"
CHECKM_QUALITY="$4"
EXPECTED_MAGS="${5:-}"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
DRAM_ENV="${DRAM_ENV:-dram_1.5.0}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$MAG_DIR" ]]; then
    echo "ERROR: MAG directory not found: $MAG_DIR" >&2
    exit 1
fi

if [[ ! -s "$TAXONOMY_TSV" ]]; then
    echo "ERROR: GTDB-Tk taxonomy table not found or empty: $TAXONOMY_TSV" >&2
    exit 1
fi

if [[ ! -s "$CHECKM_QUALITY" ]]; then
    echo "ERROR: dRep CheckM quality table not found or empty: $CHECKM_QUALITY" >&2
    exit 1
fi

if [[ -e "$OUTPUT_DIR" ]]; then
    echo "ERROR: Output directory already exists: $OUTPUT_DIR" >&2
    exit 1
fi

mapfile -d '' MAG_FILES < <(
    find "$MAG_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.fa" \
        -print0 |
        sort -z
)

N_MAGS="${#MAG_FILES[@]}"

if [[ "$N_MAGS" -eq 0 ]]; then
    echo "ERROR: No .fa MAG files found in: $MAG_DIR" >&2
    exit 1
fi

if [[ -n "$EXPECTED_MAGS" ]]; then

    if ! [[ "$EXPECTED_MAGS" =~ ^[1-9][0-9]*$ ]]; then
        echo "ERROR: Expected MAG count must be a positive integer." >&2
        exit 1
    fi

    if [[ "$N_MAGS" -ne "$EXPECTED_MAGS" ]]; then
        echo "WARNING: Expected $EXPECTED_MAGS MAGs, but found $N_MAGS." >&2
    fi

fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$DRAM_ENV"

###############################################################################
# DRAM ANNOTATION
###############################################################################

echo "============================================================"
echo "Starting DRAM annotation"
echo "Input MAGs: $N_MAGS"
echo "Input directory: $MAG_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "Threads: $THREADS"
echo "============================================================"

DRAM.py annotate \
    -i "${MAG_DIR}/*.fa" \
    -o "$OUTPUT_DIR" \
    --gtdb_taxonomy "$TAXONOMY_TSV" \
    --checkm_quality "$CHECKM_QUALITY" \
    --keep_tmp_dir \
    --use_uniref \
    --threads "$THREADS"

ANNOTATIONS="${OUTPUT_DIR}/annotations.tsv"
TRNA_TABLE="${OUTPUT_DIR}/trnas.tsv"
RRNA_TABLE="${OUTPUT_DIR}/rrnas.tsv"

if [[ ! -s "$ANNOTATIONS" ]]; then
    echo "ERROR: DRAM annotations.tsv was not generated." >&2
    exit 1
fi

###############################################################################
# DRAM DISTILLATION
###############################################################################

DRAM.py distill \
    -i "$ANNOTATIONS" \
    -o "${OUTPUT_DIR}/summary" \
    --trna_path "$TRNA_TABLE" \
    --rrna_path "$RRNA_TABLE"

echo "DRAM annotation completed successfully."
echo "Annotations: $ANNOTATIONS"
echo "Summary: ${OUTPUT_DIR}/summary"
