#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_METABOLIC
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=300:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Predicts metabolic functions and biogeochemical-cycle traits in
# species-level dereplicated MAGs using METABOLIC-G.
#
# INPUT
# Directory containing species-level dereplicated MAGs in FASTA format.
# Generated by: 14_drep_species_level_dereplication.sh
#
# OUTPUT
# METABOLIC-G annotation and metabolic-trait output directory.
#
# USAGE
# sbatch 20_metabolic_mag_annotation.sh \
#   MAG_directory \
#   output_directory \
#   METABOLIC_installation_directory \
#   [expected_number_of_MAGs]

if [[ $# -lt 3 || $# -gt 4 ]]; then
    echo "Usage: sbatch $0 <MAG_dir> <output_dir> <METABOLIC_dir> [expected_MAGs]" >&2
    exit 1
fi

MAG_DIR="$1"
OUTPUT_DIR="$2"
METABOLIC_DIR="$3"
EXPECTED_MAGS="${4:-1081}"

METABOLIC_ENV="${METABOLIC_ENV:-METABOLIC_4.0}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$MAG_DIR" ]]; then
    echo "ERROR: MAG directory not found: $MAG_DIR" >&2
    exit 1
fi

if [[ ! -d "$METABOLIC_DIR" ]]; then
    echo "ERROR: METABOLIC installation directory not found: $METABOLIC_DIR" >&2
    exit 1
fi

METABOLIC_SCRIPT="${METABOLIC_DIR}/METABOLIC-G.pl"

if [[ ! -f "$METABOLIC_SCRIPT" ]]; then
    echo "ERROR: METABOLIC-G.pl not found: $METABOLIC_SCRIPT" >&2
    exit 1
fi

if [[ -e "$OUTPUT_DIR" ]]; then
    echo "ERROR: Output directory already exists: $OUTPUT_DIR" >&2
    exit 1
fi

if ! [[ "$EXPECTED_MAGS" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: Expected MAG count must be a positive integer." >&2
    exit 1
fi

mapfile -d '' MAG_FILES < <(
    find "$MAG_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.fa" \
        -print0 |
        sort -z
)

N_MAGS="${#MAG_FILES[@]}"

if [[ "$N_MAGS" -eq 0 ]]; then
    echo "ERROR: No .fa MAG files found in: $MAG_DIR" >&2
    exit 1
fi

if [[ "$N_MAGS" -ne "$EXPECTED_MAGS" ]]; then
    echo "WARNING: Expected $EXPECTED_MAGS MAGs, but found $N_MAGS." >&2
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$METABOLIC_ENV"

###############################################################################
# METABOLIC-G
###############################################################################

echo "============================================================"
echo "Starting METABOLIC-G"
echo "Input MAGs: $N_MAGS"
echo "Input directory: $MAG_DIR"
echo "Output directory: $OUTPUT_DIR"
echo "============================================================"

perl "$METABOLIC_SCRIPT" \
    -in-gn "$MAG_DIR" \
    -o "$OUTPUT_DIR"

if [[ ! -d "$OUTPUT_DIR" ]]; then
    echo "ERROR: METABOLIC output directory was not generated." >&2
    exit 1
fi

echo "METABOLIC-G completed successfully."
echo "Output directory: $OUTPUT_DIR"
