#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMG_InterProScan
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=40G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail
shopt -s nullglob

# DESCRIPTION
# Runs InterProScan on DRAM-predicted proteins from selected MAGs and combines
# the resulting annotations with GTDB-Tk taxonomy.
#
# INPUT
# MAG identifier list, DRAM output directory, taxonomy table and
# InterProScan installation directory.
# Generated by: 19_dram_mag_annotation.sh and
# 16_gtdbtk_taxonomic_classification.sh
#
# OUTPUT
# Per-MAG InterProScan TSV files and one combined annotation table containing
# MAG identifiers and taxonomic ranks.
#
# USAGE
# sbatch 21_interproscan_mag_annotations.sh \
#   MAG_list.txt \
#   DRAM_output_base_directory \
#   taxonomy.tsv \
#   output_directory \
#   InterProScan_installation_directory

if [[ $# -ne 5 ]]; then
    echo "Usage: sbatch $0 <MAG_list> <DRAM_dir> <taxonomy.tsv> <output_dir> <InterProScan_dir>" >&2
    exit 1
fi

MAG_LIST="$1"
DRAM_BASE="$2"
TAXONOMY_TSV="$3"
OUTPUT_DIR="$4"
INTERPROSCAN_DIR="$5"

THREADS="${SLURM_CPUS_PER_TASK:-16}"
JAVA_MODULE="${JAVA_MODULE:-openjdk/17.0.8.1_1}"

COMBINED_OUTPUT="${OUTPUT_DIR}/MAG_interproscan_annotations.tsv"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -s "$MAG_LIST" ]]; then
    echo "ERROR: MAG list not found or empty: $MAG_LIST" >&2
    exit 1
fi

if [[ ! -d "$DRAM_BASE" ]]; then
    echo "ERROR: DRAM output directory not found: $DRAM_BASE" >&2
    exit 1
fi

if [[ ! -s "$TAXONOMY_TSV" ]]; then
    echo "ERROR: Taxonomy table not found or empty: $TAXONOMY_TSV" >&2
    exit 1
fi

if [[ ! -x "${INTERPROSCAN_DIR}/interproscan.sh" ]]; then
    echo "ERROR: interproscan.sh not found or not executable in: $INTERPROSCAN_DIR" >&2
    exit 1
fi

if ! command -v module >/dev/null 2>&1; then
    echo "ERROR: The environment-module command was not found." >&2
    exit 1
fi

mkdir -p \
    "$OUTPUT_DIR" \
    "$OUTPUT_DIR/clean_faa" \
    "$OUTPUT_DIR/logs"

module load "$JAVA_MODULE"

###############################################################################
# LOCATE DRAM PROTEINS AND RUN INTERPROSCAN
###############################################################################

find_dram_faa() {

    local mag="$1"
    local matches=()

    mapfile -t matches < <(
        find "$DRAM_BASE" \
            -type f \
            -path "*/${mag}/genes.annotated.faa" \
            -print |
            sort
    )

    if [[ ${#matches[@]} -eq 0 ]]; then
        return 1
    fi

    if [[ ${#matches[@]} -gt 1 ]]; then
        echo "ERROR: Multiple genes.annotated.faa files found for $mag:" >&2
        printf '  %s\n' "${matches[@]}" >&2
        return 2
    fi

    printf '%s\n' "${matches[0]}"
}

PROCESSED_MAGS=0
SKIPPED_MAGS=0

while IFS=$'\t' read -r MAG_ID REST; do

    MAG_ID="${MAG_ID//$'\r'/}"

    [[ -n "$MAG_ID" ]] || continue
    [[ "$MAG_ID" == \#* ]] && continue

    case "$MAG_ID" in
        MAG | mag | genome | Genome)
            continue
            ;;
    esac

    FAA_FILE="$(find_dram_faa "$MAG_ID" || true)"

    if [[ -z "$FAA_FILE" ]]; then
        echo "WARNING: genes.annotated.faa not found for $MAG_ID." >&2
        SKIPPED_MAGS=$((SKIPPED_MAGS + 1))
        continue
    fi

    CLEAN_FASTA="${OUTPUT_DIR}/clean_faa/${MAG_ID}.clean.faa"
    OUTPUT_PREFIX="${OUTPUT_DIR}/${MAG_ID}"
    TSV_OUTPUT="${OUTPUT_PREFIX}.tsv"
    LOG_FILE="${OUTPUT_DIR}/logs/${MAG_ID}.log"

    sed 's/\*//g' "$FAA_FILE" > "$CLEAN_FASTA"

    if [[ ! -s "$CLEAN_FASTA" ]]; then
        echo "WARNING: Empty cleaned protein FASTA for $MAG_ID." >&2
        SKIPPED_MAGS=$((SKIPPED_MAGS + 1))
        continue
    fi

    if [[ -s "$TSV_OUTPUT" ]]; then
        echo "Existing InterProScan output found; skipping: $MAG_ID"
        PROCESSED_MAGS=$((PROCESSED_MAGS + 1))
        continue
    fi

    echo "Running InterProScan: $MAG_ID"

    (
        cd "$INTERPROSCAN_DIR"

        ./interproscan.sh \
            -dp \
            -f tsv \
            -cpu "$THREADS" \
            -i "$CLEAN_FASTA" \
            -b "$OUTPUT_PREFIX"
    ) > "$LOG_FILE" 2>&1

    if [[ ! -s "$TSV_OUTPUT" ]]; then
        echo "ERROR: InterProScan output not generated for $MAG_ID." >&2
        exit 1
    fi

    PROCESSED_MAGS=$((PROCESSED_MAGS + 1))

done < "$MAG_LIST"

###############################################################################
# LOAD TAXONOMY TABLE
###############################################################################

declare -A TAX_DOMAIN
declare -A TAX_PHYLUM
declare -A TAX_CLASS
declare -A TAX_ORDER
declare -A TAX_FAMILY
declare -A TAX_GENUS
declare -A TAX_SPECIES

{
    IFS=$'\t' read -r -a HEADER

    declare -A COLUMN_INDEX

    for INDEX in "${!HEADER[@]}"; do
        COLUMN_NAME="${HEADER[$INDEX]//$'\r'/}"
        COLUMN_INDEX["$COLUMN_NAME"]="$INDEX"
    done

    for REQUIRED_COLUMN in \
        genome \
        Domain \
        Phylum \
        Class \
        Order \
        Family \
        Genus \
        Species
    do
        if [[ -z "${COLUMN_INDEX[$REQUIRED_COLUMN]+x}" ]]; then
            echo "ERROR: Column '$REQUIRED_COLUMN' not found in $TAXONOMY_TSV." >&2
            exit 1
        fi
    done

    while IFS=$'\t' read -r -a ROW; do

        GENOME="${ROW[${COLUMN_INDEX[genome]}]:-}"
        GENOME="${GENOME//$'\r'/}"

        [[ -n "$GENOME" ]] || continue

        TAX_DOMAIN["$GENOME"]="${ROW[${COLUMN_INDEX[Domain]}]:-NA}"
        TAX_PHYLUM["$GENOME"]="${ROW[${COLUMN_INDEX[Phylum]}]:-NA}"
        TAX_CLASS["$GENOME"]="${ROW[${COLUMN_INDEX[Class]}]:-NA}"
        TAX_ORDER["$GENOME"]="${ROW[${COLUMN_INDEX[Order]}]:-NA}"
        TAX_FAMILY["$GENOME"]="${ROW[${COLUMN_INDEX[Family]}]:-NA}"
        TAX_GENUS["$GENOME"]="${ROW[${COLUMN_INDEX[Genus]}]:-NA}"
        TAX_SPECIES["$GENOME"]="${ROW[${COLUMN_INDEX[Species]}]:-NA}"

    done

} < "$TAXONOMY_TSV"

###############################################################################
# COMBINE INTERPROSCAN ANNOTATIONS WITH TAXONOMY
###############################################################################

printf '%s\n' \
"MAG	Domain	Phylum	Class	Order	Family	Genus	Species	Protein Accession	Sequence MD5	Sequence length	Analysis	Signature Accession	Signature Description	Start	Stop	Score	Status	Date	InterPro Accession	InterPro Description	GO terms	Pathways" \
> "$COMBINED_OUTPUT"

INTERPROSCAN_FILES=("$OUTPUT_DIR"/*.tsv)

for TSV_FILE in "${INTERPROSCAN_FILES[@]}"; do

    [[ "$TSV_FILE" == "$COMBINED_OUTPUT" ]] && continue

    MAG_ID="$(basename "$TSV_FILE" .tsv)"

    DOMAIN="${TAX_DOMAIN[$MAG_ID]:-NA}"
    PHYLUM="${TAX_PHYLUM[$MAG_ID]:-NA}"
    CLASS="${TAX_CLASS[$MAG_ID]:-NA}"
    ORDER="${TAX_ORDER[$MAG_ID]:-NA}"
    FAMILY="${TAX_FAMILY[$MAG_ID]:-NA}"
    GENUS="${TAX_GENUS[$MAG_ID]:-NA}"
    SPECIES="${TAX_SPECIES[$MAG_ID]:-NA}"

    awk \
        -v OFS='\t' \
        -v MAG="$MAG_ID" \
        -v D="$DOMAIN" \
        -v P="$PHYLUM" \
        -v C="$CLASS" \
        -v O="$ORDER" \
        -v F="$FAMILY" \
        -v G="$GENUS" \
        -v S="$SPECIES" \
        '
        BEGIN {
            FS = OFS
        }

        !/^#/ {
            print MAG, D, P, C, O, F, G, S, $0
        }
        ' \
        "$TSV_FILE" \
        >> "$COMBINED_OUTPUT"

done

echo "============================================================"
echo "InterProScan completed."
echo "Processed MAGs: $PROCESSED_MAGS"
echo "Skipped MAGs: $SKIPPED_MAGS"
echo "Combined annotations: $COMBINED_OUTPUT"
echo "============================================================"
