#!/usr/bin/env python3

# DESCRIPTION
# Exports one continuous nucleotide FASTA for each selected MHC genomic
# context. The extracted interval spans the leftmost to the rightmost context
# gene and therefore retains all intervening intergenic sequence.
#
# INPUT
# 1. A context TSV containing, at minimum:
#      genome, target_MHC, gene_id, relative_position
# 2. A genome manifest supplied either as:
#      a) a TSV with columns genome and fasta; or
#      b) one genome FASTA path per line.
# 3. A directory containing <genome>_proteins.faa files generated by Prodigal.
#
# OUTPUT
# One nucleotide FASTA per MHC context, a combined FASTA, a context manifest,
# and a JSON summary.
#
# USAGE
# python3 02_export_MHC_context_nucleotide_FASTAs.py \
#   --context-table MHC_genomic_contexts.tsv \
#   --genome-manifest genome_manifest.tsv \
#   --prodigal-dir prodigal_prediction \
#   --output-dir MHC_context_FASTAs \
#   --flank-genes 5

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


###############################################################################
# DATA STRUCTURES
###############################################################################

@dataclass(frozen=True)
class ProdigalGene:
    protein_id: str
    contig_id: str
    gene_number: int
    start: int
    end: int
    strand: int

    @property
    def left(self) -> int:
        return min(self.start, self.end)

    @property
    def right(self) -> int:
        return max(self.start, self.end)


@dataclass(frozen=True)
class ContextGene:
    genome: str
    target_id: str
    gene_id: str
    relative_position: int


###############################################################################
# ARGUMENTS
###############################################################################

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export one continuous nucleotide FASTA for each selected "
            "MHC genomic context."
        )
    )

    parser.add_argument(
        "--context-table",
        required=True,
        type=Path,
        help=(
            "TSV containing genome, target_MHC, gene_id and "
            "relative_position columns."
        ),
    )

    parser.add_argument(
        "--genome-manifest",
        required=True,
        type=Path,
        help=(
            "Genome manifest: either a TSV with genome and fasta columns "
            "or one genome FASTA path per line."
        ),
    )

    parser.add_argument(
        "--prodigal-dir",
        required=True,
        type=Path,
        help="Directory containing <genome>_proteins.faa files.",
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Directory receiving the extracted context FASTA files.",
    )

    parser.add_argument(
        "--flank-genes",
        type=int,
        default=5,
        help=(
            "Expected maximum number of neighboring genes on each side "
            "of the target MHC. Default: 5."
        ),
    )

    parser.add_argument(
        "--allow-truncated-contexts",
        action="store_true",
        help=(
            "Allow contexts shorter than the complete -N..+N window, "
            "for example at contig boundaries."
        ),
    )

    parser.add_argument(
        "--genome-column",
        default="genome",
        help="Genome column in the context table. Default: genome.",
    )

    parser.add_argument(
        "--target-column",
        default="target_MHC",
        help="Target MHC column in the context table. Default: target_MHC.",
    )

    parser.add_argument(
        "--gene-column",
        default="gene_id",
        help="Context-gene column in the context table. Default: gene_id.",
    )

    parser.add_argument(
        "--relative-position-column",
        default="relative_position",
        help=(
            "Relative-position column in the context table. "
            "Default: relative_position."
        ),
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an existing non-empty output directory.",
    )

    return parser.parse_args()


###############################################################################
# GENERAL HELPERS
###############################################################################

def require_nonempty_file(path: Path, label: str) -> None:
    if not path.is_file() or path.stat().st_size == 0:
        raise FileNotFoundError(f"{label} is missing or empty: {path}")


def clean_identifier(value: object) -> str:
    text = "" if value is None else str(value).strip()

    if text.startswith(">"):
        text = text[1:]

    return text.split()[0] if text else ""


def protein_id_for_genome(
    value: object,
    genome: str,
    label: str,
) -> str:
    """
    Accept either protein_id or genome|protein_id and return protein_id.
    """

    identifier = clean_identifier(value)

    if not identifier:
        raise ValueError(f"Empty {label} for genome {genome}.")

    if "|" not in identifier:
        return identifier

    id_genome, protein_id = identifier.split("|", 1)

    if id_genome != genome:
        raise ValueError(
            f"{label} genome mismatch: row genome={genome!r}, "
            f"identifier={identifier!r}"
        )

    if not protein_id:
        raise ValueError(f"Missing protein part in {label}: {identifier!r}")

    return protein_id


def sanitize_filename_part(value: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._")

    if not sanitized:
        raise ValueError(f"Cannot create a safe filename from {value!r}")

    return sanitized


def wrap_sequence(sequence: str, width: int = 80) -> str:
    return "\n".join(
        sequence[start : start + width]
        for start in range(0, len(sequence), width)
    )


###############################################################################
# PRODIGAL COORDINATES
###############################################################################

def split_prodigal_id(protein_id: str) -> tuple[str, int]:
    match = re.fullmatch(r"(.+)_([0-9]+)", protein_id)

    if match is None:
        raise ValueError(
            "Protein ID does not end in a numeric Prodigal gene suffix: "
            f"{protein_id}"
        )

    return match.group(1), int(match.group(2))


def parse_prodigal_coordinates(
    header: str,
    protein_id: str,
) -> tuple[int, int, int]:
    fields = [field.strip() for field in header.split("#")]

    if len(fields) < 4:
        raise ValueError(
            f"Prodigal coordinates are absent from FASTA header: {header}"
        )

    try:
        start = int(fields[1])
        end = int(fields[2])
        strand = int(fields[3])
    except ValueError as exc:
        raise ValueError(
            f"Invalid Prodigal coordinates for {protein_id}: {header}"
        ) from exc

    if start <= 0 or end <= 0:
        raise ValueError(
            f"Non-positive Prodigal coordinate for {protein_id}: {header}"
        )

    if strand not in {-1, 1}:
        raise ValueError(
            f"Prodigal strand must be -1 or 1 for {protein_id}: {header}"
        )

    return start, end, strand


def read_prodigal_gene_coordinates(
    path: Path,
) -> dict[str, ProdigalGene]:
    require_nonempty_file(path, "Prodigal protein FASTA")

    genes: dict[str, ProdigalGene] = {}

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if not line or not line.startswith(">"):
                continue

            header = line[1:]
            protein_id = clean_identifier(header)

            if not protein_id:
                raise ValueError(f"Blank FASTA identifier in {path}")

            if protein_id in genes:
                raise ValueError(
                    f"Duplicate protein ID {protein_id!r} in {path}"
                )

            contig_id, gene_number = split_prodigal_id(protein_id)
            start, end, strand = parse_prodigal_coordinates(
                header,
                protein_id,
            )

            genes[protein_id] = ProdigalGene(
                protein_id=protein_id,
                contig_id=contig_id,
                gene_number=gene_number,
                start=start,
                end=end,
                strand=strand,
            )

    if not genes:
        raise ValueError(f"No Prodigal records found in {path}")

    return genes


###############################################################################
# GENOME MANIFEST AND FASTA
###############################################################################

def resolve_manifest_path(value: str, manifest_path: Path) -> Path:
    path = Path(value)

    if not path.is_absolute():
        path = manifest_path.parent / path

    return path.resolve()


def read_genome_manifest(path: Path) -> dict[str, Path]:
    require_nonempty_file(path, "Genome manifest")

    first_nonempty = ""

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            if raw_line.strip():
                first_nonempty = raw_line.rstrip("\n")
                break

    if not first_nonempty:
        raise ValueError(f"No genome entries found in {path}")

    genome_paths: dict[str, Path] = {}

    header_fields = first_nonempty.split("\t")
    is_tsv_manifest = {"genome", "fasta"}.issubset(header_fields)

    if is_tsv_manifest:
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle, delimiter="\t")

            for line_number, row in enumerate(reader, start=2):
                genome = clean_identifier(row.get("genome", ""))
                fasta_value = str(row.get("fasta", "")).strip()

                if not genome or not fasta_value:
                    raise ValueError(
                        f"Empty genome or fasta at {path}:{line_number}"
                    )

                if genome in genome_paths:
                    raise ValueError(
                        f"Duplicate genome {genome!r} in {path}"
                    )

                genome_path = resolve_manifest_path(fasta_value, path)
                require_nonempty_file(
                    genome_path,
                    f"Genome FASTA for {genome}",
                )
                genome_paths[genome] = genome_path

    else:
        with path.open("r", encoding="utf-8") as handle:
            for line_number, raw_line in enumerate(handle, start=1):
                entry = raw_line.strip()

                if not entry:
                    continue

                genome_path = resolve_manifest_path(entry, path)
                require_nonempty_file(
                    genome_path,
                    f"Genome FASTA at manifest line {line_number}",
                )

                genome = genome_path.name

                for suffix in (
                    ".fna.gz",
                    ".fa.gz",
                    ".fasta.gz",
                    ".fna",
                    ".fa",
                    ".fasta",
                ):
                    if genome.endswith(suffix):
                        genome = genome[: -len(suffix)]
                        break

                if genome in genome_paths:
                    raise ValueError(
                        f"Duplicate genome {genome!r} in {path}"
                    )

                genome_paths[genome] = genome_path

    if not genome_paths:
        raise ValueError(f"No genome paths found in {path}")

    return genome_paths


def read_nucleotide_fasta(path: Path) -> dict[str, str]:
    require_nonempty_file(path, "Original genome FASTA")

    if path.name.endswith(".gz"):
        import gzip
        opener = gzip.open
    else:
        opener = Path.open

    sequences: dict[str, str] = {}
    header: str | None = None
    sequence_lines: list[str] = []

    def finish_record() -> None:
        nonlocal header, sequence_lines

        if header is None:
            return

        sequence_id = clean_identifier(header)

        if not sequence_id:
            raise ValueError(f"Blank FASTA identifier in {path}")

        if sequence_id in sequences:
            raise ValueError(
                f"Duplicate sequence ID {sequence_id!r} in {path}"
            )

        sequence = re.sub(
            r"\s+",
            "",
            "".join(sequence_lines),
        ).upper().replace("U", "T")

        if not sequence:
            raise ValueError(
                f"Empty nucleotide sequence {sequence_id!r} in {path}"
            )

        invalid = re.search(r"[^ACGTRYSWKMBDHVN]", sequence)

        if invalid:
            raise ValueError(
                f"Invalid nucleotide {invalid.group(0)!r} in "
                f"{sequence_id!r} from {path}"
            )

        sequences[sequence_id] = sequence

    with opener(path, "rt", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if not line:
                continue

            if line.startswith(">"):
                finish_record()
                header = line[1:]
                sequence_lines = []
            else:
                if header is None:
                    raise ValueError(
                        f"Sequence precedes the first FASTA header in {path}"
                    )

                sequence_lines.append(line)

        finish_record()

    if not sequences:
        raise ValueError(f"No nucleotide records found in {path}")

    return sequences


###############################################################################
# CONTEXT TABLE
###############################################################################

def read_contexts(
    path: Path,
    genome_column: str,
    target_column: str,
    gene_column: str,
    relative_position_column: str,
    flank_genes: int,
    allow_truncated: bool,
) -> dict[tuple[str, str], list[ContextGene]]:
    require_nonempty_file(path, "MHC genomic-context table")

    grouped: dict[tuple[str, str], list[ContextGene]] = defaultdict(list)

    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        fieldnames = reader.fieldnames or []

        required = {
            genome_column,
            target_column,
            gene_column,
            relative_position_column,
        }

        missing = required - set(fieldnames)

        if missing:
            raise ValueError(
                "Context table is missing required columns: "
                + ", ".join(sorted(missing))
            )

        for line_number, row in enumerate(reader, start=2):
            genome = clean_identifier(row[genome_column])

            if not genome:
                raise ValueError(
                    f"Empty genome at {path}:{line_number}"
                )

            target_id = protein_id_for_genome(
                row[target_column],
                genome,
                target_column,
            )

            gene_id = protein_id_for_genome(
                row[gene_column],
                genome,
                gene_column,
            )

            try:
                relative_position = int(
                    str(row[relative_position_column]).strip()
                )
            except ValueError as exc:
                raise ValueError(
                    f"{relative_position_column} must be an integer at "
                    f"{path}:{line_number}"
                ) from exc

            if not -flank_genes <= relative_position <= flank_genes:
                raise ValueError(
                    f"Relative position {relative_position} is outside "
                    f"-{flank_genes}..+{flank_genes} at "
                    f"{path}:{line_number}"
                )

            grouped[(genome, target_id)].append(
                ContextGene(
                    genome=genome,
                    target_id=target_id,
                    gene_id=gene_id,
                    relative_position=relative_position,
                )
            )

    if not grouped:
        raise ValueError(f"No genomic contexts found in {path}")

    expected_positions = list(range(-flank_genes, flank_genes + 1))

    for (genome, target_id), genes in grouped.items():
        genes.sort(key=lambda gene: gene.relative_position)

        positions = [gene.relative_position for gene in genes]

        if len(positions) != len(set(positions)):
            raise ValueError(
                f"Duplicate relative positions in {genome}|{target_id}: "
                f"{positions}"
            )

        if 0 not in positions:
            raise ValueError(
                f"Target position 0 is absent from {genome}|{target_id}"
            )

        central = next(
            gene
            for gene in genes
            if gene.relative_position == 0
        )

        if central.gene_id != target_id:
            raise ValueError(
                f"The gene at position 0 is not the target MHC in "
                f"{genome}|{target_id}: {central.gene_id}"
            )

        if not allow_truncated and positions != expected_positions:
            raise ValueError(
                f"Expected a complete -{flank_genes}..+{flank_genes} "
                f"context for {genome}|{target_id}, but found: {positions}"
            )

        if allow_truncated:
            if positions != list(range(min(positions), max(positions) + 1)):
                raise ValueError(
                    f"Non-contiguous relative positions in "
                    f"{genome}|{target_id}: {positions}"
                )

        gene_ids = [gene.gene_id for gene in genes]

        if len(gene_ids) != len(set(gene_ids)):
            raise ValueError(
                f"Duplicate gene IDs in context {genome}|{target_id}"
            )

    return dict(grouped)


###############################################################################
# FASTA EXPORT
###############################################################################

def render_context(
    genome: str,
    target_id: str,
    genes: list[ContextGene],
    prodigal_genes: dict[str, ProdigalGene],
    contig_sequences: dict[str, str],
    flank_genes: int,
) -> tuple[str, str, dict[str, object]]:
    resolved: list[tuple[ContextGene, ProdigalGene]] = []

    for context_gene in genes:
        prodigal_gene = prodigal_genes.get(context_gene.gene_id)

        if prodigal_gene is None:
            raise ValueError(
                f"Gene absent from {genome}_proteins.faa: "
                f"{genome}|{context_gene.gene_id}"
            )

        resolved.append((context_gene, prodigal_gene))

    contig_ids = {
        prodigal_gene.contig_id
        for _, prodigal_gene in resolved
    }

    if len(contig_ids) != 1:
        raise ValueError(
            f"Context spans multiple contigs for {genome}|{target_id}: "
            f"{sorted(contig_ids)}"
        )

    contig_id = next(iter(contig_ids))
    contig_sequence = contig_sequences.get(contig_id)

    if contig_sequence is None:
        raise ValueError(
            f"Prodigal contig {contig_id!r} for {genome}|{target_id} "
            "is absent from the original genome FASTA."
        )

    genomic_order = [
        (
            prodigal_gene.left,
            prodigal_gene.right,
            prodigal_gene.gene_number,
        )
        for _, prodigal_gene in resolved
    ]

    if genomic_order != sorted(genomic_order):
        raise ValueError(
            "Context-table relative positions do not follow ascending "
            f"genomic coordinates for {genome}|{target_id}"
        )

    region_start = min(
        prodigal_gene.left
        for _, prodigal_gene in resolved
    )

    region_end = max(
        prodigal_gene.right
        for _, prodigal_gene in resolved
    )

    if region_end > len(contig_sequence):
        raise ValueError(
            f"Requested coordinates {region_start}-{region_end} exceed "
            f"contig {contig_id!r} length {len(contig_sequence)} for "
            f"{genome}|{target_id}"
        )

    region_sequence = contig_sequence[
        region_start - 1 : region_end
    ]

    expected_length = region_end - region_start + 1

    if len(region_sequence) != expected_length:
        raise RuntimeError(
            f"Extracted length disagreement for {genome}|{target_id}"
        )

    relative_min = min(gene.relative_position for gene in genes)
    relative_max = max(gene.relative_position for gene in genes)

    sequence_id = (
        f"{genome}|{contig_id}:{region_start}-{region_end}"
    )

    header = (
        f"{sequence_id} "
        f"target_MHC={genome}|{target_id} "
        f"n_genes={len(genes)} "
        f"relative_positions={relative_min}..{relative_max} "
        "orientation=original_contig_forward "
        f"gene_ids={','.join(gene.gene_id for gene in genes)}"
    )

    metadata = {
        "genome": genome,
        "target_MHC": target_id,
        "contig_id": contig_id,
        "region_start": region_start,
        "region_end": region_end,
        "region_length": len(region_sequence),
        "target_strand": prodigal_genes[target_id].strand,
        "n_context_genes": len(genes),
        "relative_position_min": relative_min,
        "relative_position_max": relative_max,
        "complete_window": (
            relative_min == -flank_genes
            and relative_max == flank_genes
            and len(genes) == 2 * flank_genes + 1
        ),
        "orientation": "original_contig_forward",
    }

    return header, region_sequence, metadata


def main() -> None:
    args = parse_args()

    if args.flank_genes < 0:
        raise ValueError("--flank-genes must be zero or greater.")

    context_table = args.context_table.resolve()
    genome_manifest = args.genome_manifest.resolve()
    prodigal_dir = args.prodigal_dir.resolve()
    output_dir = args.output_dir.resolve()

    if not prodigal_dir.is_dir():
        raise FileNotFoundError(
            f"Prodigal directory does not exist: {prodigal_dir}"
        )

    contexts = read_contexts(
        path=context_table,
        genome_column=args.genome_column,
        target_column=args.target_column,
        gene_column=args.gene_column,
        relative_position_column=args.relative_position_column,
        flank_genes=args.flank_genes,
        allow_truncated=args.allow_truncated_contexts,
    )

    genome_paths = read_genome_manifest(genome_manifest)

    observed_genomes = {
        genome
        for genome, _ in contexts
    }

    missing_genomes = sorted(
        observed_genomes - set(genome_paths)
    )

    if missing_genomes:
        raise ValueError(
            "Context genomes absent from genome manifest: "
            + ", ".join(missing_genomes)
        )

    if output_dir.exists() and any(output_dir.iterdir()):
        if not args.overwrite:
            raise FileExistsError(
                f"Output directory exists and is not empty: {output_dir}"
            )

        shutil.rmtree(output_dir)

    per_context_dir = output_dir / "per_context"
    per_context_dir.mkdir(parents=True, exist_ok=True)

    prodigal_by_genome: dict[
        str,
        dict[str, ProdigalGene],
    ] = {}

    contigs_by_genome: dict[
        str,
        dict[str, str],
    ] = {}

    combined_records: list[tuple[str, str]] = []
    manifest_rows: list[dict[str, object]] = []
    output_names: set[str] = set()

    for (genome, target_id), genes in sorted(contexts.items()):
        if genome not in prodigal_by_genome:
            prodigal_path = (
                prodigal_dir
                / f"{genome}_proteins.faa"
            )

            prodigal_by_genome[genome] = (
                read_prodigal_gene_coordinates(prodigal_path)
            )

            contigs_by_genome[genome] = (
                read_nucleotide_fasta(genome_paths[genome])
            )

        header, sequence, metadata = render_context(
            genome=genome,
            target_id=target_id,
            genes=genes,
            prodigal_genes=prodigal_by_genome[genome],
            contig_sequences=contigs_by_genome[genome],
            flank_genes=args.flank_genes,
        )

        filename = (
            f"{sanitize_filename_part(genome)}"
            f"__target_MHC__"
            f"{sanitize_filename_part(target_id)}"
            "__genomic_context.fna"
        )

        if filename in output_names:
            raise ValueError(
                f"Duplicate sanitized output filename: {filename}"
            )

        output_names.add(filename)
        output_path = per_context_dir / filename

        with output_path.open("w", encoding="utf-8") as handle:
            handle.write(f">{header}\n")
            handle.write(wrap_sequence(sequence))
            handle.write("\n")

        metadata["output_fasta"] = str(output_path)
        manifest_rows.append(metadata)
        combined_records.append((header, sequence))

    combined_fasta = output_dir / "all_MHC_genomic_contexts.fna"

    with combined_fasta.open("w", encoding="utf-8") as handle:
        for header, sequence in combined_records:
            handle.write(f">{header}\n")
            handle.write(wrap_sequence(sequence))
            handle.write("\n")

    manifest_path = output_dir / "MHC_context_FASTA_manifest.tsv"
    manifest_fields = [
        "genome",
        "target_MHC",
        "contig_id",
        "region_start",
        "region_end",
        "region_length",
        "target_strand",
        "n_context_genes",
        "relative_position_min",
        "relative_position_max",
        "complete_window",
        "orientation",
        "output_fasta",
    ]

    with manifest_path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=manifest_fields,
            delimiter="\t",
            lineterminator="\n",
        )

        writer.writeheader()
        writer.writerows(manifest_rows)

    complete_contexts = sum(
        bool(row["complete_window"])
        for row in manifest_rows
    )

    summary = {
        "input_context_table": str(context_table),
        "genome_manifest": str(genome_manifest),
        "prodigal_directory": str(prodigal_dir),
        "flank_genes_each_side": args.flank_genes,
        "contexts_exported": len(manifest_rows),
        "complete_contexts": complete_contexts,
        "truncated_contexts": len(manifest_rows) - complete_contexts,
        "orientation": "original_contig_forward",
        "per_context_FASTA_directory": str(per_context_dir),
        "combined_FASTA": str(combined_fasta),
        "manifest": str(manifest_path),
    }

    summary_path = output_dir / "MHC_context_FASTA_summary.json"

    with summary_path.open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)
        handle.write("\n")

    print("MHC context FASTA export completed successfully.")
    print(f"Contexts exported: {len(manifest_rows)}")
    print(f"Complete contexts: {complete_contexts}")
    print(
        "Truncated contexts: "
        f"{len(manifest_rows) - complete_contexts}"
    )
    print(f"Per-context FASTAs: {per_context_dir}")
    print(f"Combined FASTA: {combined_fasta}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
