#!/bin/bash
#SBATCH -n 1
#SBATCH --job-name=iMT_TranscriptM
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=25G
#SBATCH --time=350:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

set -euo pipefail

# DESCRIPTION
# Processes raw paired-end metatranscriptomic reads and calculates gene-level
# read counts and coverage against the MAG collection using TranscriptM.
#
# INPUT
# Raw paired-end metatranscriptomic reads stored in per-sample directories,
# the renamed MAG reference directory and the TranscriptM database.
#
# MAGs generated by:
# scripts/analyses/02_metagenome_MAG_processing/
# 14_drep_species_level_dereplication.sh
#
# OUTPUT
# One TranscriptM output directory per metatranscriptomic sample.
#
# USAGE
# sbatch 01_transcriptm_metatranscriptome_processing.sh \
#   raw_metatranscriptome_directory \
#   renamed_MAG_directory \
#   TranscriptM_database_directory \
#   output_directory \
#   [MAG_file_extension] \
#   [expected_number_of_samples]

###############################################################################
# ARGUMENTS
###############################################################################

if [[ $# -lt 4 || $# -gt 6 ]]; then
    echo "Usage:" >&2
    echo "  sbatch $0 <reads_dir> <MAG_dir> <database_dir> <output_dir> [MAG_extension] [expected_samples]" >&2
    exit 1
fi

READS_DIR="$1"
MAG_DIR="$2"
TRANSCRIPTM_DATABASE="$3"
OUTPUT_DIR="$4"

MAG_EXTENSION="${5:-fasta}"
EXPECTED_SAMPLES="${6:-20}"

TRANSCRIPTM_ENV="${TRANSCRIPTM_ENV:-transcriptm_v0.3.1}"

###############################################################################
# INPUT VALIDATION
###############################################################################

if [[ ! -d "$READS_DIR" ]]; then
    echo "ERROR: Raw-read directory not found: $READS_DIR" >&2
    exit 1
fi

if [[ ! -d "$MAG_DIR" ]]; then
    echo "ERROR: MAG reference directory not found: $MAG_DIR" >&2
    exit 1
fi

if [[ ! -d "$TRANSCRIPTM_DATABASE" ]]; then
    echo "ERROR: TranscriptM database directory not found: $TRANSCRIPTM_DATABASE" >&2
    exit 1
fi

if ! [[ "$EXPECTED_SAMPLES" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: Expected sample count must be a positive integer." >&2
    exit 1
fi

mapfile -d '' MAG_FILES < <(
    find "$MAG_DIR" \
        -maxdepth 1 \
        -type f \
        -name "*.${MAG_EXTENSION}" \
        -print0 |
        sort -z
)

N_MAGS="${#MAG_FILES[@]}"

if [[ "$N_MAGS" -eq 0 ]]; then
    echo "ERROR: No *.${MAG_EXTENSION} MAG files found in: $MAG_DIR" >&2
    exit 1
fi

mapfile -d '' R1_FILES < <(
    find "$READS_DIR" \
        -type f \
        -name "*_PE1.fq.gz" \
        -print0 |
        sort -z
)

N_SAMPLES="${#R1_FILES[@]}"

if [[ "$N_SAMPLES" -eq 0 ]]; then
    echo "ERROR: No *_PE1.fq.gz files found in: $READS_DIR" >&2
    exit 1
fi

if [[ "$N_SAMPLES" -ne "$EXPECTED_SAMPLES" ]]; then
    echo "WARNING: Expected $EXPECTED_SAMPLES metaT samples, but found $N_SAMPLES." >&2
fi

if ! command -v conda >/dev/null 2>&1; then
    echo "ERROR: Conda was not found." >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

###############################################################################
# SOFTWARE
###############################################################################

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$TRANSCRIPTM_ENV"

if ! command -v transcriptm >/dev/null 2>&1; then
    echo "ERROR: transcriptm was not found in environment: $TRANSCRIPTM_ENV" >&2
    exit 1
fi

VERSION_FILE="${OUTPUT_DIR}/software_versions.txt"

{
    echo "TranscriptM environment: $TRANSCRIPTM_ENV"
    echo
    echo "TranscriptM executable:"
    command -v transcriptm
    echo
    echo "TranscriptM version command:"
    transcriptm --version 2>&1 || true
    echo
    echo "Conda package information:"
    conda list | grep -i -E \
        'transcriptm|trimmomatic|fastqc|fxtract|sortmerna|bamm' \
        || true
} > "$VERSION_FILE"

###############################################################################
# PROCESS METATRANSCRIPTOMIC SAMPLES
###############################################################################

PROCESSED_SAMPLES=0

for R1 in "${R1_FILES[@]}"; do

    SAMPLE_DIR="$(dirname "$R1")"
    R1_NAME="$(basename "$R1")"
    SAMPLE_NAME="${R1_NAME%_PE1.fq.gz}"

    R2="${SAMPLE_DIR}/${SAMPLE_NAME}_PE2.fq.gz"
    SAMPLE_OUTPUT="${OUTPUT_DIR}/TranscriptM_${SAMPLE_NAME}"

    if [[ ! -f "$R2" ]]; then
        echo "ERROR: Read 2 is missing for sample: $SAMPLE_NAME" >&2
        echo "Expected file: $R2" >&2
        exit 1
    fi

    if [[ -e "$SAMPLE_OUTPUT" ]]; then
        echo "ERROR: Sample output directory already exists:" >&2
        echo "$SAMPLE_OUTPUT" >&2
        exit 1
    fi

    echo "============================================================"
    echo "Starting TranscriptM"
    echo "Sample: $SAMPLE_NAME"
    echo "Read 1: $R1"
    echo "Read 2: $R2"
    echo "Reference MAGs: $N_MAGS"
    echo "MAG extension: $MAG_EXTENSION"
    echo "Output: $SAMPLE_OUTPUT"
    echo "============================================================"

    transcriptm count \
        -1 "$R1" \
        -2 "$R2" \
        -g "$MAG_DIR" \
        -x "$MAG_EXTENSION" \
        -o "$SAMPLE_OUTPUT" \
        -db "$TRANSCRIPTM_DATABASE"

    if [[ ! -d "$SAMPLE_OUTPUT" ]]; then
        echo "ERROR: TranscriptM output directory was not generated for $SAMPLE_NAME." >&2
        exit 1
    fi

    if [[ -z "$(find "$SAMPLE_OUTPUT" -mindepth 1 -print -quit)" ]]; then
        echo "ERROR: TranscriptM output directory is empty for $SAMPLE_NAME." >&2
        exit 1
    fi

    PROCESSED_SAMPLES=$((PROCESSED_SAMPLES + 1))

    echo "TranscriptM completed: $SAMPLE_NAME"

done

###############################################################################
# FINAL SUMMARY
###############################################################################

echo "============================================================"
echo "TranscriptM processing completed successfully."
echo "Samples detected: $N_SAMPLES"
echo "Samples processed: $PROCESSED_SAMPLES"
echo "Reference MAGs: $N_MAGS"
echo "Output directory: $OUTPUT_DIR"
echo "Software versions: $VERSION_FILE"
echo "============================================================"
