#!/usr/bin/env Rscript

###############################################################################
# EXTENDED DATA FIGURE 1C — ALPHA AND BETA DIVERSITY
#
# DESCRIPTION
# Generates richness, evenness, Shannon, Bray-Curtis and Jaccard profiles.
#
# INPUT
# alpha_diversity_analysis_objects.rds
#
# Generated by:
# scripts/analyses/01_16S_rRNA_analysis/
# 02_alpha_diversity_analysis.R
#
# OUTPUT
# EDFigure1C_alpha_beta_diversity.svg
#
# USAGE
# Rscript EDFigure1C_alpha_beta_diversity.R \
#   alpha_diversity_analysis_objects.rds \
#   output_directory
###############################################################################

required_packages <- c(
  "dplyr",
  "ggplot2",
  "ggh4x",
  "patchwork",
  "purrr",
  "svglite",
  "tibble",
  "tidyr",
  "vegan"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_packages, collapse = ", ")
  )
}

###############################################################################
# INPUT AND OUTPUT
###############################################################################

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 1 || length(args) > 2) {
  stop(
    paste(
      "Usage:",
      "Rscript EDFigure1C_alpha_beta_diversity.R",
      "<alpha_diversity_analysis_objects.rds>",
      "[output_directory]"
    )
  )
}

input_file <- args[[1]]
output_dir <- if (length(args) == 2) args[[2]] else "."

if (!file.exists(input_file)) {
  stop("Input file not found: ", input_file)
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

output_svg <- file.path(
  output_dir,
  "EDFigure1C_alpha_beta_diversity.svg"
)

###############################################################################
# LOAD ANALYSIS OBJECTS
###############################################################################

analysis_objects <- readRDS(input_file)

required_objects <- c(
  "alpha_diversity_with_design",
  "rarefied_otu_tables"
)

missing_objects <- setdiff(
  required_objects,
  names(analysis_objects)
)

if (length(missing_objects) > 0) {
  stop(
    "Missing objects in the input RDS: ",
    paste(missing_objects, collapse = ", ")
  )
}

alpha_data <- analysis_objects$alpha_diversity_with_design
rarefied_otu_tables <- analysis_objects$rarefied_otu_tables

required_columns <- c(
  "Sample",
  "treatment",
  "system",
  "sobs",
  "shannon",
  "evenness"
)

missing_columns <- setdiff(
  required_columns,
  names(alpha_data)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing alpha-diversity columns: ",
    paste(missing_columns, collapse = ", ")
  )
}

###############################################################################
# SAMPLE INFORMATION
###############################################################################

peatland_levels <- c(
  "BM",
  "HV",
  "LM",
  "NR"
)

metric_levels <- c(
  "Richness",
  "Evenness",
  "Shannon",
  "Bray-Curtis",
  "Jaccard"
)

beta_metrics <- c(
  "Bray-Curtis",
  "Jaccard"
)

alpha_data <- alpha_data |>
  dplyr::mutate(
    Sample = trimws(as.character(.data$Sample)),
    treatment = trimws(as.character(.data$treatment)),
    system = trimws(as.character(.data$system)),
    profile_label = dplyr::case_when(
      .data$treatment %in% c(
        "Spatial",
        "Spatial profiling"
      ) ~ "Spatial profiling",
      .data$treatment %in% c(
        "Depth",
        "Deep",
        "Deep profiling"
      ) ~ "Deep profiling",
      TRUE ~ NA_character_
    ),
    system = factor(
      .data$system,
      levels = peatland_levels
    )
  )

if (anyNA(alpha_data$profile_label)) {
  stop("Unexpected values found in the treatment column.")
}

if (anyNA(alpha_data$system)) {
  stop("Unexpected values found in the system column.")
}

parse_sample <- function(
    Sample,
    profile_label,
    system
) {

  tail_part <- sub(
    paste0(
      "^",
      system,
      "\\."
    ),
    "",
    Sample
  )

  parts <- strsplit(
    tail_part,
    "\\."
  )[[1]]

  if (profile_label == "Spatial profiling") {

    site_id <- parts[[1]]
    depth_values <- as.numeric(parts[-1])

  } else {

    site_id <- "deep_profile"

    if (Sample == "BM.0.50") {
      depth_values <- c(0, 25)
    } else {
      depth_values <- as.numeric(parts)
    }
  }

  if (anyNA(depth_values)) {
    stop("Could not parse sample depth for: ", Sample)
  }

  tibble::tibble(
    Sample = Sample,
    site_id = site_id,
    depth_label = paste(
      depth_values,
      collapse = "–"
    ),
    depth_mid = mean(depth_values)
  )
}

parsed_samples <- purrr::pmap_dfr(
  list(
    alpha_data$Sample,
    alpha_data$profile_label,
    as.character(alpha_data$system)
  ),
  parse_sample
)

sample_info <- alpha_data |>
  dplyr::select(
    Sample,
    profile_label,
    system,
    sobs,
    shannon,
    evenness
  ) |>
  dplyr::left_join(
    parsed_samples,
    by = "Sample"
  ) |>
  dplyr::mutate(
    profile_label = factor(
      .data$profile_label,
      levels = c(
        "Spatial profiling",
        "Deep profiling"
      )
    )
  )

###############################################################################
# ALPHA-DIVERSITY SUMMARY
###############################################################################

alpha_plot <- sample_info |>
  dplyr::select(
    Sample,
    profile_label,
    system,
    site_id,
    depth_label,
    depth_mid,
    sobs,
    evenness,
    shannon
  ) |>
  tidyr::pivot_longer(
    cols = c(
      sobs,
      evenness,
      shannon
    ),
    names_to = "metric",
    values_to = "value"
  ) |>
  dplyr::mutate(
    metric = dplyr::recode(
      .data$metric,
      sobs = "Richness",
      evenness = "Evenness",
      shannon = "Shannon"
    )
  ) |>
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$depth_label,
    .data$depth_mid,
    .data$metric
  ) |>
  dplyr::summarise(
    n = sum(!is.na(.data$value)),
    mean = mean(
      .data$value,
      na.rm = TRUE
    ),
    sd = ifelse(
      .data$n > 1,
      stats::sd(
        .data$value,
        na.rm = TRUE
      ),
      NA_real_
    ),
    se = ifelse(
      .data$n > 1,
      .data$sd / sqrt(.data$n),
      NA_real_
    ),
    .groups = "drop"
  )

###############################################################################
# CONSECUTIVE SAMPLE PAIRS
###############################################################################

sample_pairs <- sample_info |>
  dplyr::select(
    Sample,
    profile_label,
    system,
    site_id,
    depth_label,
    depth_mid
  ) |>
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$site_id
  ) |>
  dplyr::arrange(
    .data$depth_mid,
    .by_group = TRUE
  ) |>
  dplyr::mutate(
    previous_sample = dplyr::lag(.data$Sample)
  ) |>
  dplyr::ungroup() |>
  dplyr::filter(
    !is.na(.data$previous_sample)
  )

###############################################################################
# BETA-DIVERSITY DISTANCES
###############################################################################

prepare_otu_table <- function(
    otu_table,
    required_samples
) {

  otu_table <- as.matrix(otu_table)
  storage.mode(otu_table) <- "numeric"

  row_matches <- if (!is.null(rownames(otu_table))) {
    sum(rownames(otu_table) %in% required_samples)
  } else {
    0
  }

  column_matches <- if (!is.null(colnames(otu_table))) {
    sum(colnames(otu_table) %in% required_samples)
  } else {
    0
  }

  if (column_matches > row_matches) {
    otu_table <- t(otu_table)
  }

  retained_samples <- required_samples[
    required_samples %in% rownames(otu_table)
  ]

  otu_table[
    match(
      retained_samples,
      rownames(otu_table)
    ),
    ,
    drop = FALSE
  ]
}

calculate_beta_distances <- function(
    otu_table,
    sample_pairs,
    required_samples
) {

  otu_table <- prepare_otu_table(
    otu_table,
    required_samples
  )

  valid_pairs <- sample_pairs |>
    dplyr::filter(
      .data$Sample %in% rownames(otu_table),
      .data$previous_sample %in% rownames(otu_table)
    )

  if (nrow(valid_pairs) == 0) {
    return(tibble::tibble())
  }

  bray_matrix <- as.matrix(
    vegan::vegdist(
      otu_table,
      method = "bray"
    )
  )

  jaccard_matrix <- as.matrix(
    vegan::vegdist(
      otu_table,
      method = "jaccard",
      binary = TRUE
    )
  )

  valid_pairs |>
    dplyr::mutate(
      `Bray-Curtis` = purrr::map2_dbl(
        .data$previous_sample,
        .data$Sample,
        ~ bray_matrix[.x, .y]
      ),
      Jaccard = purrr::map2_dbl(
        .data$previous_sample,
        .data$Sample,
        ~ jaccard_matrix[.x, .y]
      )
    ) |>
    tidyr::pivot_longer(
      cols = c(
        `Bray-Curtis`,
        Jaccard
      ),
      names_to = "metric",
      values_to = "value"
    )
}

beta_long <- purrr::map_dfr(
  rarefied_otu_tables,
  calculate_beta_distances,
  sample_pairs = sample_pairs,
  required_samples = sample_info$Sample,
  .id = "rarefaction"
)

beta_plot <- beta_long |>
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$site_id,
    .data$depth_label,
    .data$depth_mid,
    .data$Sample,
    .data$previous_sample,
    .data$metric
  ) |>
  dplyr::summarise(
    value = mean(
      .data$value,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$depth_label,
    .data$depth_mid,
    .data$metric
  ) |>
  dplyr::summarise(
    n = sum(!is.na(.data$value)),
    mean = mean(
      .data$value,
      na.rm = TRUE
    ),
    sd = ifelse(
      .data$n > 1,
      stats::sd(
        .data$value,
        na.rm = TRUE
      ),
      NA_real_
    ),
    se = ifelse(
      .data$n > 1,
      .data$sd / sqrt(.data$n),
      NA_real_
    ),
    .groups = "drop"
  )

###############################################################################
# COMBINE METRICS
###############################################################################

plot_data <- dplyr::bind_rows(
  alpha_plot,
  beta_plot
) |>
  dplyr::mutate(
    metric = factor(
      .data$metric,
      levels = metric_levels
    ),
    system = factor(
      as.character(.data$system),
      levels = peatland_levels
    ),
    profile_label = factor(
      as.character(.data$profile_label),
      levels = c(
        "Spatial profiling",
        "Deep profiling"
      )
    )
  )

###############################################################################
# AXIS SETTINGS
###############################################################################

metric_limits <- tibble::tibble(
  metric = factor(
    metric_levels,
    levels = metric_levels
  ),
  xmin = c(
    200,
    0.20,
    1.5,
    0.00,
    0.40
  ),
  xmax = c(
    1200,
    0.80,
    4.5,
    1.00,
    0.80
  )
)

metric_labels <- c(
  "Richness" = "Observed\nrichness",
  "Evenness" = "Pielou\nevenness",
  "Shannon" = "Shannon\ndiversity",
  "Bray-Curtis" = "Bray-Curtis\ndistance",
  "Jaccard" = "Jaccard\ndistance"
)

x_scales <- ggh4x::facetted_pos_scales(
  x = list(
    metric == "Richness" ~ ggplot2::scale_x_continuous(
      limits = c(200, 1200),
      breaks = seq(200, 1200, 200),
      expand = ggplot2::expansion(mult = c(0, 0))
    ),
    metric == "Evenness" ~ ggplot2::scale_x_continuous(
      limits = c(0.20, 0.80),
      breaks = seq(0.20, 0.80, 0.20),
      expand = ggplot2::expansion(mult = c(0, 0))
    ),
    metric == "Shannon" ~ ggplot2::scale_x_continuous(
      limits = c(1.5, 4.5),
      breaks = seq(1.5, 4.5, 0.5),
      expand = ggplot2::expansion(mult = c(0, 0))
    ),
    metric == "Bray-Curtis" ~ ggplot2::scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, 0.2),
      expand = ggplot2::expansion(mult = c(0, 0))
    ),
    metric == "Jaccard" ~ ggplot2::scale_x_continuous(
      limits = c(0.40, 0.80),
      breaks = seq(0.40, 0.80, 0.10),
      expand = ggplot2::expansion(mult = c(0, 0))
    )
  )
)

###############################################################################
# PLOTTING DATA
###############################################################################

spatial_data <- plot_data |>
  dplyr::filter(
    .data$profile_label == "Spatial profiling"
  ) |>
  dplyr::mutate(
    depth_plot = factor(
      .data$depth_label,
      levels = c(
        "60",
        "30",
        "10"
      )
    )
  ) |>
  dplyr::arrange(
    .data$metric,
    .data$system,
    .data$depth_mid
  )

spatial_reference <- metric_limits |>
  tidyr::crossing(
    depth_plot = factor(
      c(
        "60",
        "30",
        "10"
      ),
      levels = c(
        "60",
        "30",
        "10"
      )
    )
  ) |>
  tidyr::pivot_longer(
    cols = c(
      xmin,
      xmax
    ),
    values_to = "x"
  )

deep_data <- plot_data |>
  dplyr::filter(
    .data$profile_label == "Deep profiling"
  ) |>
  dplyr::mutate(
    depth_id = paste(
      .data$system,
      .data$depth_label,
      sep = "__"
    )
  )

deep_levels <- deep_data |>
  dplyr::distinct(
    .data$system,
    .data$depth_label,
    .data$depth_mid,
    .data$depth_id
  ) |>
  dplyr::arrange(
    .data$system,
    dplyr::desc(.data$depth_mid)
  ) |>
  dplyr::pull(
    .data$depth_id
  )

deep_data <- deep_data |>
  dplyr::mutate(
    depth_plot = factor(
      .data$depth_id,
      levels = unique(deep_levels)
    )
  ) |>
  dplyr::arrange(
    .data$system,
    .data$metric,
    .data$depth_mid
  )

deep_reference <- metric_limits |>
  tidyr::crossing(
    deep_data |>
      dplyr::distinct(
        .data$system,
        .data$depth_plot
      )
  ) |>
  tidyr::pivot_longer(
    cols = c(
      xmin,
      xmax
    ),
    values_to = "x"
  )

###############################################################################
# PLOT
###############################################################################

peatland_colors <- c(
  "BM" = "#3366CC",
  "HV" = "#D4A017",
  "LM" = "#1B7741",
  "NR" = "#E6863B"
)

theme_diversity <- ggplot2::theme_classic(
  base_size = 11
) +
  ggplot2::theme(
    panel.border = ggplot2::element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.4
    ),
    panel.spacing = grid::unit(
      0.25,
      "lines"
    ),
    strip.background = ggplot2::element_blank(),
    strip.text.x = ggplot2::element_text(
      size = 12,
      face = "bold"
    ),
    strip.text.y = ggplot2::element_text(
      size = 11,
      face = "bold"
    ),
    axis.title = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_text(
      size = 9
    ),
    axis.text.x = ggplot2::element_text(
      size = 8
    ),
    legend.position = "bottom",
    legend.title = ggplot2::element_blank()
  )

p_spatial <- ggplot2::ggplot(
  spatial_data,
  ggplot2::aes(
    x = .data$mean,
    y = .data$depth_plot
  )
) +
  ggplot2::geom_blank(
    data = spatial_reference,
    ggplot2::aes(
      x = .data$x,
      y = .data$depth_plot
    ),
    inherit.aes = FALSE
  ) +
  ggplot2::geom_path(
    ggplot2::aes(
      group = .data$system,
      colour = .data$system
    ),
    linewidth = 0.65,
    na.rm = TRUE
  ) +
  ggplot2::geom_segment(
    ggplot2::aes(
      x = .data$mean - .data$se,
      xend = .data$mean + .data$se,
      yend = .data$depth_plot,
      colour = .data$system
    ),
    linewidth = 0.8,
    na.rm = TRUE
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      fill = .data$system
    ),
    shape = 21,
    size = 2.9,
    colour = "black",
    stroke = 0.35,
    na.rm = TRUE
  ) +
  ggplot2::facet_grid(
    . ~ metric,
    scales = "free_x",
    labeller = ggplot2::labeller(
      metric = metric_labels
    )
  ) +
  x_scales +
  ggplot2::scale_fill_manual(
    values = peatland_colors
  ) +
  ggplot2::scale_colour_manual(
    values = peatland_colors
  ) +
  ggplot2::labs(
    title = "Spatial profiling"
  ) +
  ggplot2::guides(
    fill = "none",
    colour = "none"
  ) +
  theme_diversity

p_deep <- ggplot2::ggplot(
  deep_data,
  ggplot2::aes(
    x = .data$mean,
    y = .data$depth_plot
  )
) +
  ggplot2::geom_blank(
    data = deep_reference,
    ggplot2::aes(
      x = .data$x,
      y = .data$depth_plot
    ),
    inherit.aes = FALSE
  ) +
  ggplot2::geom_path(
    ggplot2::aes(
      group = 1,
      colour = .data$system
    ),
    linewidth = 0.65,
    na.rm = TRUE
  ) +
  ggplot2::geom_point(
    ggplot2::aes(
      fill = .data$system
    ),
    shape = 21,
    size = 2.9,
    colour = "black",
    stroke = 0.35,
    na.rm = TRUE
  ) +
  ggplot2::facet_grid(
    system ~ metric,
    scales = "free",
    space = "free_y",
    labeller = ggplot2::labeller(
      metric = metric_labels
    )
  ) +
  x_scales +
  ggplot2::scale_y_discrete(
    labels = function(x) {
      sub(
        "^.*__",
        "",
        x
      )
    }
  ) +
  ggplot2::scale_fill_manual(
    values = peatland_colors,
    breaks = peatland_levels,
    drop = FALSE
  ) +
  ggplot2::scale_colour_manual(
    values = peatland_colors,
    breaks = peatland_levels,
    drop = FALSE
  ) +
  ggplot2::guides(
    colour = "none",
    fill = ggplot2::guide_legend(
      override.aes = list(
        shape = 21,
        size = 3.2,
        colour = "black"
      )
    )
  ) +
  ggplot2::labs(
    title = "Deep profiling"
  ) +
  theme_diversity

final_plot <- patchwork::wrap_plots(
  p_spatial,
  p_deep,
  ncol = 1,
  heights = c(
    1.15,
    4.4
  ),
  guides = "collect"
)

print(final_plot)

ggplot2::ggsave(
  filename = output_svg,
  plot = final_plot,
  device = svglite::svglite,
  width = 10,
  height = 12,
  units = "in",
  bg = "white"
)

cat(
  "\nExtended Data Figure 1C saved to:\n",
  output_svg,
  "\n",
  sep = ""
)
