#!/usr/bin/env Rscript

###############################################################################
# 16S rRNA BETA DIVERSITY ANALYSIS
#
# This script:
#   1. Loads the rarefied OTU tables generated by
#      02_alpha_diversity_analysis.R
#   2. Orders samples by depth within each peatland and sampling profile
#   3. Defines consecutive-depth sample pairs
#   4. Calculates Bray-Curtis dissimilarity and binary Jaccard dissimilarity
#      for every pair in each of the 100 rarefied OTU tables
#   5. Averages dissimilarities across rarefaction iterations
#   6. Summarizes spatial values across replicate sites
#
# Spatial profiling:
#   - samples are paired within each peatland and sampling site
#   - 10 cm has no preceding depth
#   - 30 cm represents the 10 -> 30 cm comparison
#   - 60 cm represents the 30 -> 60 cm comparison
#
# Deep profiling:
#   - samples are paired separately within each peatland
#   - the shallowest sample has no preceding depth
#   - no comparison is made between spatial and deep profiles
#
# Input:
#   alpha_diversity_results/alpha_diversity_analysis_objects.rds
#
# This RDS file is generated by:
#   02_alpha_diversity_analysis.R
###############################################################################

###############################################################################
# 1. PACKAGES
###############################################################################

library(dplyr)
library(purrr)
library(readr)
library(tibble)
library(tidyr)
library(vegan)

###############################################################################
# 2. INPUT AND OUTPUT PATHS
###############################################################################

analysis_dir <- "."

alpha_objects_file <- file.path(
  analysis_dir,
  "alpha_diversity_results",
  "alpha_diversity_analysis_objects.rds"
)

output_dir <- file.path(
  analysis_dir,
  "beta_diversity_results"
)

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

###############################################################################
# 3. CHECK AND LOAD INPUT
###############################################################################

if (!file.exists(alpha_objects_file)) {
  stop(
    paste0(
      "Input file not found:\n",
      alpha_objects_file,
      "\n\nRun 02_alpha_diversity_analysis.R before this script."
    )
  )
}

analysis_objects <- readRDS(alpha_objects_file)

required_objects <- c(
  "rarefied_otu_tables",
  "alpha_diversity_with_design"
)

missing_objects <- setdiff(
  required_objects,
  names(analysis_objects)
)

if (length(missing_objects) > 0) {
  stop(
    paste(
      "The input RDS file is missing the following objects:",
      paste(missing_objects, collapse = ", ")
    )
  )
}

som.select.sub <- analysis_objects$rarefied_otu_tables
df2 <- analysis_objects$alpha_diversity_with_design

if (!is.list(som.select.sub) || length(som.select.sub) == 0) {
  stop(
    "The object 'rarefied_otu_tables' must be a non-empty list."
  )
}

if (length(som.select.sub) != 100) {
  stop(
    paste0(
      "Expected 100 rarefied OTU tables, but found ",
      length(som.select.sub),
      "."
    )
  )
}

if (!is.data.frame(df2)) {
  stop(
    "The object 'alpha_diversity_with_design' must be a data frame."
  )
}

required_metadata_columns <- c(
  "Sample",
  "treatment",
  "system",
  "sobs",
  "shannon",
  "evenness"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  names(df2)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    paste(
      "Missing columns in alpha_diversity_with_design:",
      paste(missing_metadata_columns, collapse = ", ")
    )
  )
}

if (anyDuplicated(df2$Sample)) {
  stop(
    "Duplicated sample identifiers were found in the alpha-diversity table."
  )
}

###############################################################################
# 4. PEATLAND ORDER
###############################################################################

peatland_levels <- c(
  "BM",
  "HV",
  "LM",
  "NR"
)

###############################################################################
# 5. PARSE SAMPLE INFORMATION
###############################################################################

parse_sample_info <- function(Sample, treatment, system) {

  Sample <- as.character(Sample)
  treatment <- as.character(treatment)
  system <- as.character(system)

  if (!treatment %in% c("Spatial", "Depth")) {
    stop(
      paste0(
        "Unexpected treatment value for sample ",
        Sample,
        ": ",
        treatment
      )
    )
  }

  if (!system %in% peatland_levels) {
    stop(
      paste0(
        "Unexpected peatland code for sample ",
        Sample,
        ": ",
        system
      )
    )
  }

  expected_prefix <- paste0(system, ".")

  if (!startsWith(Sample, expected_prefix)) {
    stop(
      paste0(
        "Sample name and peatland code do not match: ",
        Sample,
        " / ",
        system
      )
    )
  }

  tail_part <- sub(
    paste0("^", system, "\\."),
    "",
    Sample
  )

  parts <- strsplit(
    tail_part,
    "\\."
  )[[1]]

  if (treatment == "Spatial") {

    if (length(parts) < 2) {
      stop(
        paste0(
          "Could not parse spatial sample name: ",
          Sample
        )
      )
    }

    site_id <- parts[1]

    depth_values <- suppressWarnings(
      as.numeric(parts[-1])
    )

    if (anyNA(depth_values)) {
      stop(
        paste0(
          "Could not parse spatial depth for sample: ",
          Sample
        )
      )
    }

    depth_label <- paste(
      depth_values,
      collapse = "–"
    )

    depth_mid <- mean(
      depth_values
    )

    profile_label <- "Spatial profiling"

  } else {

    site_id <- "deep_profile"

    # BM.0.50 represents the 0–25 cm section in the original analysis.
    if (Sample == "BM.0.50") {

      depth_values <- c(
        0,
        25
      )

      depth_label <- "0–25"
      depth_mid <- 12.5

    } else {

      depth_values <- suppressWarnings(
        as.numeric(parts)
      )

      if (anyNA(depth_values)) {
        stop(
          paste0(
            "Could not parse deep-profile depth for sample: ",
            Sample
          )
        )
      }

      depth_label <- paste(
        depth_values,
        collapse = "–"
      )

      depth_mid <- mean(
        depth_values
      )
    }

    profile_label <- "Deep profiling"
  }

  tibble::tibble(
    Sample = Sample,
    profile_label = profile_label,
    site_id = site_id,
    depth_label = depth_label,
    depth_mid = depth_mid
  )
}

parsed_samples <- purrr::pmap_dfr(
  list(
    df2$Sample,
    df2$treatment,
    df2$system
  ),
  parse_sample_info
)

if (anyDuplicated(parsed_samples$Sample)) {
  stop(
    "Duplicated samples were generated while parsing sample information."
  )
}

sample_info <- df2 %>%
  dplyr::select(
    Sample,
    treatment,
    system,
    sobs,
    shannon,
    evenness
  ) %>%
  dplyr::left_join(
    parsed_samples,
    by = "Sample"
  ) %>%
  dplyr::mutate(
    system = factor(
      as.character(.data$system),
      levels = peatland_levels
    ),
    profile_label = factor(
      .data$profile_label,
      levels = c(
        "Spatial profiling",
        "Deep profiling"
      )
    )
  )

if (anyNA(sample_info$profile_label) ||
    anyNA(sample_info$site_id) ||
    anyNA(sample_info$depth_mid)) {
  stop(
    "Missing values were generated while parsing sample information."
  )
}

###############################################################################
# 6. DEFINE CONSECUTIVE-DEPTH SAMPLE PAIRS
###############################################################################

pairs_tbl <- sample_info %>%
  dplyr::select(
    Sample,
    profile_label,
    system,
    site_id,
    depth_label,
    depth_mid
  ) %>%
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$site_id
  ) %>%
  dplyr::arrange(
    .data$depth_mid,
    .by_group = TRUE
  ) %>%
  dplyr::mutate(
    prev_Sample = dplyr::lag(.data$Sample),
    prev_depth_label = dplyr::lag(.data$depth_label),
    prev_depth_mid = dplyr::lag(.data$depth_mid)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::filter(
    !is.na(.data$prev_Sample)
  )

if (nrow(pairs_tbl) == 0) {
  stop(
    "No consecutive-depth sample pairs were generated."
  )
}

if (any(pairs_tbl$depth_mid <= pairs_tbl$prev_depth_mid)) {
  stop(
    "At least one sample pair is not ordered from shallower to deeper depth."
  )
}

if (any(pairs_tbl$Sample == pairs_tbl$prev_Sample)) {
  stop(
    "At least one sample was paired with itself."
  )
}

###############################################################################
# 7. VERIFY SPATIAL PAIRS
###############################################################################

spatial_pairs <- pairs_tbl %>%
  dplyr::filter(
    .data$profile_label == "Spatial profiling"
  )

invalid_spatial_pairs <- spatial_pairs %>%
  dplyr::filter(
    !(
      (.data$prev_depth_mid == 10 & .data$depth_mid == 30) |
        (.data$prev_depth_mid == 30 & .data$depth_mid == 60)
    )
  )

if (nrow(invalid_spatial_pairs) > 0) {

  print(invalid_spatial_pairs)

  stop(
    paste(
      "Unexpected spatial sample pairs were generated.",
      "Expected only 10 -> 30 cm and 30 -> 60 cm."
    )
  )
}

###############################################################################
# 8. OTU TABLE PREPARATION
###############################################################################

prepare_otu_table <- function(
    otu_table,
    wanted_samples
) {

  otu_table <- as.matrix(
    otu_table
  )

  storage.mode(otu_table) <- "numeric"

  row_matches <- if (!is.null(rownames(otu_table))) {
    sum(
      rownames(otu_table) %in% wanted_samples
    )
  } else {
    0
  }

  column_matches <- if (!is.null(colnames(otu_table))) {
    sum(
      colnames(otu_table) %in% wanted_samples
    )
  } else {
    0
  }

  # vegan expects samples in rows.
  if (column_matches > row_matches) {
    otu_table <- t(
      otu_table
    )
  }

  missing_samples <- setdiff(
    wanted_samples,
    rownames(otu_table)
  )

  if (length(missing_samples) > 0) {
    stop(
      paste(
        "Samples missing from a rarefied OTU table:",
        paste(missing_samples, collapse = ", ")
      )
    )
  }

  otu_table <- otu_table[
    match(
      wanted_samples,
      rownames(otu_table)
    ),
    ,
    drop = FALSE
  ]

  if (anyNA(otu_table)) {
    stop(
      "NA values were found in a rarefied OTU table."
    )
  }

  if (any(otu_table < 0)) {
    stop(
      "Negative values were found in a rarefied OTU table."
    )
  }

  otu_table
}

###############################################################################
# 9. CALCULATE BETA DIVERSITY FOR ONE RAREFACTION
###############################################################################

calculate_beta_one <- function(
    otu_table,
    pairs_tbl,
    wanted_samples
) {

  otu_table <- prepare_otu_table(
    otu_table = otu_table,
    wanted_samples = wanted_samples
  )

  valid_pairs <- pairs_tbl %>%
    dplyr::filter(
      .data$Sample %in% rownames(otu_table),
      .data$prev_Sample %in% rownames(otu_table)
    )

  if (nrow(valid_pairs) != nrow(pairs_tbl)) {
    stop(
      "Not all consecutive-depth pairs were found in a rarefied OTU table."
    )
  }

  bray_matrix <- as.matrix(
    vegan::vegdist(
      otu_table,
      method = "bray"
    )
  )

  jaccard_matrix <- as.matrix(
    vegan::vegdist(
      otu_table,
      method = "jaccard",
      binary = TRUE
    )
  )

  valid_pairs %>%
    dplyr::mutate(
      Bray_Curtis = purrr::map2_dbl(
        .data$prev_Sample,
        .data$Sample,
        ~ bray_matrix[.x, .y]
      ),
      Jaccard = purrr::map2_dbl(
        .data$prev_Sample,
        .data$Sample,
        ~ jaccard_matrix[.x, .y]
      )
    ) %>%
    tidyr::pivot_longer(
      cols = c(
        Bray_Curtis,
        Jaccard
      ),
      names_to = "metric",
      values_to = "value"
    ) %>%
    dplyr::mutate(
      metric = dplyr::recode(
        .data$metric,
        Bray_Curtis = "Bray-Curtis"
      )
    )
}

###############################################################################
# 10. CALCULATE BETA DIVERSITY ACROSS 100 RAREFACTIONS
###############################################################################

cat(
  "Calculating Bray-Curtis and Jaccard dissimilarities across",
  length(som.select.sub),
  "rarefactions.\n"
)

beta_long <- purrr::map_dfr(
  som.select.sub,
  calculate_beta_one,
  pairs_tbl = pairs_tbl,
  wanted_samples = sample_info$Sample,
  .id = "raref_id"
)

beta_long <- beta_long %>%
  dplyr::mutate(
    raref_id = as.integer(.data$raref_id)
  )

expected_beta_rows <- (
  length(som.select.sub) *
    nrow(pairs_tbl) *
    2
)

if (nrow(beta_long) != expected_beta_rows) {
  stop(
    paste0(
      "Unexpected number of beta-diversity rows. Expected ",
      expected_beta_rows,
      " but obtained ",
      nrow(beta_long),
      "."
    )
  )
}

if (anyNA(beta_long$value)) {
  stop(
    "NA beta-diversity values were generated."
  )
}

if (any(beta_long$value < 0 | beta_long$value > 1)) {
  stop(
    "Beta-diversity values outside the expected 0–1 range were generated."
  )
}

###############################################################################
# 11. MEAN DISSIMILARITY FOR EACH CONSECUTIVE SAMPLE PAIR
###############################################################################

beta_pair_mean <- beta_long %>%
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$site_id,
    .data$depth_label,
    .data$depth_mid,
    .data$Sample,
    .data$prev_Sample,
    .data$prev_depth_label,
    .data$prev_depth_mid,
    .data$metric
  ) %>%
  dplyr::summarise(
    value = mean(
      .data$value,
      na.rm = TRUE
    ),
    sd_across_rarefactions = stats::sd(
      .data$value,
      na.rm = TRUE
    ),
    min_across_rarefactions = min(
      .data$value,
      na.rm = TRUE
    ),
    max_across_rarefactions = max(
      .data$value,
      na.rm = TRUE
    ),
    n_rarefactions = dplyr::n(),
    .groups = "drop"
  )

if (any(beta_pair_mean$n_rarefactions != length(som.select.sub))) {
  stop(
    "At least one sample pair does not contain all rarefaction iterations."
  )
}

###############################################################################
# 12. SUMMARY BY PEATLAND AND DEPTH
###############################################################################

# For spatial profiling, this calculates mean ± SE across replicate sites.
#
# For deep profiling, each peatland has one profile; therefore n is normally 1
# at each target depth and SE is reported as NA.

beta_summary_by_depth <- beta_pair_mean %>%
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$depth_label,
    .data$depth_mid,
    .data$metric
  ) %>%
  dplyr::summarise(
    n = sum(
      !is.na(.data$value)
    ),
    mean = mean(
      .data$value,
      na.rm = TRUE
    ),
    sd = ifelse(
      n > 1,
      stats::sd(
        .data$value,
        na.rm = TRUE
      ),
      NA_real_
    ),
    se = ifelse(
      n > 1,
      sd / sqrt(n),
      NA_real_
    ),
    .groups = "drop"
  )

###############################################################################
# 13. ALPHA-DIVERSITY SUMMARY USED BY THE COMBINED FIGURE
###############################################################################

alpha_summary_by_depth <- sample_info %>%
  dplyr::select(
    Sample,
    profile_label,
    system,
    site_id,
    depth_label,
    depth_mid,
    sobs,
    shannon,
    evenness
  ) %>%
  tidyr::pivot_longer(
    cols = c(
      sobs,
      evenness,
      shannon
    ),
    names_to = "metric",
    values_to = "value"
  ) %>%
  dplyr::mutate(
    metric = dplyr::case_when(
      .data$metric == "sobs" ~ "Richness",
      .data$metric == "evenness" ~ "Evenness",
      .data$metric == "shannon" ~ "Shannon",
      TRUE ~ .data$metric
    )
  ) %>%
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$depth_label,
    .data$depth_mid,
    .data$metric
  ) %>%
  dplyr::summarise(
    n = sum(
      !is.na(.data$value)
    ),
    mean = mean(
      .data$value,
      na.rm = TRUE
    ),
    sd = ifelse(
      n > 1,
      stats::sd(
        .data$value,
        na.rm = TRUE
      ),
      NA_real_
    ),
    se = ifelse(
      n > 1,
      sd / sqrt(n),
      NA_real_
    ),
    .groups = "drop"
  )

alpha_beta_summary <- dplyr::bind_rows(
  alpha_summary_by_depth,
  beta_summary_by_depth
) %>%
  dplyr::mutate(
    metric = factor(
      .data$metric,
      levels = c(
        "Richness",
        "Evenness",
        "Shannon",
        "Bray-Curtis",
        "Jaccard"
      )
    ),
    system = factor(
      as.character(.data$system),
      levels = peatland_levels
    ),
    profile_label = factor(
      .data$profile_label,
      levels = c(
        "Spatial profiling",
        "Deep profiling"
      )
    )
  ) %>%
  dplyr::arrange(
    .data$profile_label,
    .data$system,
    .data$metric,
    .data$depth_mid
  )

###############################################################################
# 14. FINAL CHECKS
###############################################################################

spatial_beta_depths <- beta_summary_by_depth %>%
  dplyr::filter(
    .data$profile_label == "Spatial profiling"
  ) %>%
  dplyr::distinct(
    .data$depth_mid
  ) %>%
  dplyr::arrange(
    .data$depth_mid
  ) %>%
  dplyr::pull(
    .data$depth_mid
  )

if (!identical(
  spatial_beta_depths,
  c(30, 60)
)) {
  stop(
    paste0(
      "Unexpected spatial beta-diversity target depths: ",
      paste(spatial_beta_depths, collapse = ", "),
      ". Expected 30 and 60 cm."
    )
  )
}

first_depth_check <- pairs_tbl %>%
  dplyr::group_by(
    .data$profile_label,
    .data$system,
    .data$site_id
  ) %>%
  dplyr::summarise(
    first_target_depth = min(
      .data$depth_mid
    ),
    .groups = "drop"
  )

cat(
  "\nConsecutive-depth pairs:",
  nrow(pairs_tbl),
  "\n"
)

cat(
  "Rarefaction iterations:",
  length(som.select.sub),
  "\n"
)

cat(
  "Pair-by-metric combinations:",
  nrow(beta_pair_mean),
  "\n"
)

cat(
  "Beta-diversity rows across all rarefactions:",
  nrow(beta_long),
  "\n"
)

cat(
  "\nPairs by sampling profile and peatland:\n"
)

print(
  pairs_tbl %>%
    dplyr::count(
      .data$profile_label,
      .data$system,
      name = "number_of_pairs"
    )
)

###############################################################################
# 15. WRITE OUTPUT TABLES
###############################################################################

readr::write_tsv(
  pairs_tbl,
  file.path(
    output_dir,
    "consecutive_depth_sample_pairs.tsv"
  )
)

readr::write_tsv(
  beta_long,
  file.path(
    output_dir,
    "beta_diversity_all_rarefactions.tsv"
  )
)

readr::write_tsv(
  beta_pair_mean,
  file.path(
    output_dir,
    "beta_diversity_mean_by_sample_pair.tsv"
  )
)

readr::write_tsv(
  beta_summary_by_depth,
  file.path(
    output_dir,
    "beta_diversity_summary_by_depth.tsv"
  )
)

readr::write_tsv(
  alpha_beta_summary,
  file.path(
    output_dir,
    "alpha_beta_diversity_summary_for_figures.tsv"
  )
)

###############################################################################
# 16. SAVE ANALYSIS OBJECTS
###############################################################################

saveRDS(
  list(
    sample_information = sample_info,
    consecutive_depth_pairs = pairs_tbl,
    beta_diversity_all_rarefactions = beta_long,
    beta_diversity_by_sample_pair = beta_pair_mean,
    beta_diversity_summary_by_depth = beta_summary_by_depth,
    alpha_diversity_summary_by_depth = alpha_summary_by_depth,
    alpha_beta_summary = alpha_beta_summary
  ),
  file.path(
    output_dir,
    "beta_diversity_analysis_objects.rds"
  )
)

writeLines(
  capture.output(
    sessionInfo()
  ),
  file.path(
    output_dir,
    "sessionInfo.txt"
  )
)

cat(
  "\nBeta-diversity analysis completed successfully.\n"
)

cat(
  "Results written to:",
  normalizePath(output_dir),
  "\n"
)
