#!/usr/bin/env Rscript

###############################################################################
# 16S rRNA COMMUNITY-TABLE PREPARATION
#
# DESCRIPTION
#
# Combines the filtered 16S rRNA OTU count and taxonomy tables, removes
# non-bacterial and non-archaeal OTUs, removes chloroplast and mitochondrial
# sequences, and calculates OTU relative abundance within each sample.
#
# The resulting table is used to generate the phylum-level community-
# composition plots shown in Figure 1B and Figure 1D.
#
# INPUT
#
# Input files:
#   9.all.OTU_map.txt
#   9.all.OTU_tax.sintax.rf.txt
#
# Generated by:
#   scripts/analyses/01_16S_rRNA_analysis/
#   01_process_16S_amplicon_reads.sh
#
# The OTU count table must contain:
#   - OTU identifiers in the first column
#   - sample identifiers in the remaining columns
#
# The taxonomy table must contain:
#   - OTU identifiers in the first column
#   - taxonomy assignments containing the prefixes:
#       d:, p:, c:, o:, f:, g: and s:
#
# OUTPUT
#
# Primary output:
#   combined_otu_taxonomy_relative_abundance_2024.no_chloro_mito.xlsx
#
# Additional outputs:
#   combined_otu_taxonomy_relative_abundance_2024.with_chloro_mito.xlsx
#   chloroplast_mitochondria_removed_report.tsv
#   OTUs_removed_chloroplast_mitochondria_taxonomy.tsv
#   relative_abundance_sum_check.tsv
#   04_prepare_16S_community_table_sessionInfo.txt
#
# Both Excel files contain a worksheet named:
#   relative_abundance
#
# SAMPLE SELECTION
#
# The samples included in the final Figure 1B and Figure 1D community tables
# are listed explicitly below.
#
# BM.3.10 is intentionally excluded because it was not included in the final
# Figure 1B.
#
# USAGE
#
# Run from the directory containing the two input files:
#
# Rscript 04_prepare_16S_community_table.R
#
# Optional input and output directories:
#
# Rscript 04_prepare_16S_community_table.R \
#   path/to/input_directory \
#   path/to/output_directory
###############################################################################

###############################################################################
# 1. REQUIRED PACKAGES
###############################################################################

required_packages <- c(
  "dplyr",
  "gtools",
  "stringr",
  "tibble",
  "tidyr",
  "writexl"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste(
      "Missing required R packages:",
      paste(missing_packages, collapse = ", ")
    )
  )
}

###############################################################################
# 2. INPUT AND OUTPUT DIRECTORIES
###############################################################################

args <- commandArgs(
  trailingOnly = TRUE
)

if (length(args) > 2) {
  stop(
    paste(
      "Usage:",
      "Rscript 04_prepare_16S_community_table.R",
      "[input_directory]",
      "[output_directory]"
    )
  )
}

input_dir <- if (length(args) >= 1) {
  args[[1]]
} else {
  "."
}

output_dir <- if (length(args) == 2) {
  args[[2]]
} else {
  file.path(
    ".",
    "16S_community_table_results"
  )
}

otu_counts_file <- file.path(
  input_dir,
  "9.all.OTU_map.txt"
)

otu_taxonomy_file <- file.path(
  input_dir,
  "9.all.OTU_tax.sintax.rf.txt"
)

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!dir.exists(output_dir)) {
  stop(
    paste(
      "Could not create output directory:",
      output_dir
    )
  )
}

###############################################################################
# 3. OUTPUT FILES
###############################################################################

with_organelles_file <- file.path(
  output_dir,
  paste0(
    "combined_otu_taxonomy_relative_abundance_2024.",
    "with_chloro_mito.xlsx"
  )
)

clean_output_file <- file.path(
  output_dir,
  paste0(
    "combined_otu_taxonomy_relative_abundance_2024.",
    "no_chloro_mito.xlsx"
  )
)

removed_report_file <- file.path(
  output_dir,
  "chloroplast_mitochondria_removed_report.tsv"
)

removed_taxonomy_file <- file.path(
  output_dir,
  "OTUs_removed_chloroplast_mitochondria_taxonomy.tsv"
)

abundance_check_file <- file.path(
  output_dir,
  "relative_abundance_sum_check.tsv"
)

session_info_file <- file.path(
  output_dir,
  "04_prepare_16S_community_table_sessionInfo.txt"
)

###############################################################################
# 4. CHECK INPUT FILES
###############################################################################

input_files <- c(
  otu_counts_file,
  otu_taxonomy_file
)

missing_files <- input_files[
  !file.exists(input_files)
]

if (length(missing_files) > 0) {
  stop(
    paste(
      "The following input files were not found:",
      paste(
        missing_files,
        collapse = "\n"
      ),
      sep = "\n"
    )
  )
}

###############################################################################
# 5. SAMPLE ORDER
###############################################################################

samples_spatial <- c(
  "BM.1.10",
  "BM.1.30",
  "BM.1.60",
  "BM.2.10",
  "BM.2.30",
  "BM.2.60",

  # BM.3.10 is intentionally excluded.
  "BM.3.30",
  "BM.3.60",

  "NR.1.10",
  "NR.1.30",
  "NR.1.60",
  "NR.2.10",
  "NR.2.30",
  "NR.2.60",
  "NR.3.10",
  "NR.3.30",
  "NR.3.60",

  "LM.1.10",
  "LM.1.30",
  "LM.1.60",
  "LM.2.10",
  "LM.2.30",
  "LM.2.60",
  "LM.3.10",
  "LM.3.30",
  "LM.3.60"
)

samples_deep <- c(
  "BM.0.50",
  "BM.50",
  "BM.100",
  "BM.150",
  "BM.200",
  "BM.250",
  "BM.300",
  "BM.350",
  "BM.400",
  "BM.450",
  "BM.490.540",

  "HV.0.25",
  "HV.50",
  "HV.100",
  "HV.150",
  "HV.200",
  "HV.250",
  "HV.265.280",

  "LM.0.25",
  "LM.50",
  "LM.100",
  "LM.150",
  "LM.200",
  "LM.250",
  "LM.300",
  "LM.350",
  "LM.400",
  "LM.450",
  "LM.550",
  "LM.600",
  "LM.650",
  "LM.675.700",

  "NR.0.25",
  "NR.50",
  "NR.100",
  "NR.150",
  "NR.200",
  "NR.250",
  "NR.300",
  "NR.325.350"
)

samples_all <- c(
  samples_spatial,
  samples_deep
)

if (anyDuplicated(samples_all)) {
  stop(
    "The sample-order vectors contain duplicated sample identifiers."
  )
}

###############################################################################
# 6. LOAD OTU COUNT TABLE
###############################################################################

otu_counts <- read.table(
  file = otu_counts_file,
  sep = "\t",
  header = TRUE,
  row.names = 1,
  comment.char = "",
  check.names = FALSE,
  stringsAsFactors = FALSE,
  quote = ""
)

if (nrow(otu_counts) == 0 || ncol(otu_counts) == 0) {
  stop(
    "The OTU count table is empty."
  )
}

if (anyDuplicated(rownames(otu_counts))) {
  stop(
    "Duplicated OTU identifiers were found in the OTU count table."
  )
}

missing_samples <- setdiff(
  samples_all,
  colnames(otu_counts)
)

if (length(missing_samples) > 0) {
  stop(
    paste(
      "Samples missing from the OTU count table:",
      paste(
        missing_samples,
        collapse = ", "
      )
    )
  )
}

otu_counts <- otu_counts[
  ,
  samples_all,
  drop = FALSE
]

otu_counts_numeric <- lapply(
  otu_counts,
  function(x) {
    suppressWarnings(
      as.numeric(
        as.character(x)
      )
    )
  }
)

otu_counts_numeric <- as.data.frame(
  otu_counts_numeric,
  row.names = rownames(otu_counts),
  check.names = FALSE
)

if (anyNA(otu_counts_numeric)) {
  stop(
    "Non-numeric or missing values were found in the OTU count table."
  )
}

if (any(
  as.matrix(otu_counts_numeric) < 0
)) {
  stop(
    "Negative values were found in the OTU count table."
  )
}

otu_counts <- otu_counts_numeric

otu_counts <- otu_counts[
  gtools::mixedorder(
    rownames(otu_counts)
  ),
  ,
  drop = FALSE
]

cat(
  "\nOTU count table loaded.\n"
)

cat(
  "OTUs:",
  nrow(otu_counts),
  "\n"
)

cat(
  "Selected samples:",
  ncol(otu_counts),
  "\n"
)

cat(
  "Total reads across selected samples:",
  sum(
    as.matrix(otu_counts)
  ),
  "\n"
)

###############################################################################
# 7. LOAD TAXONOMY TABLE
###############################################################################

taxonomy_raw <- read.table(
  file = otu_taxonomy_file,
  sep = "\t",
  header = TRUE,
  row.names = 1,
  fill = TRUE,
  stringsAsFactors = FALSE,
  check.names = FALSE,
  quote = "",
  comment.char = ""
)

if (nrow(taxonomy_raw) == 0) {
  stop(
    "The taxonomy table is empty."
  )
}

if (anyDuplicated(rownames(taxonomy_raw))) {
  stop(
    "Duplicated OTU identifiers were found in the taxonomy table."
  )
}

taxonomy_otu_ids <- rownames(
  taxonomy_raw
)

taxonomy_raw <- data.frame(
  lapply(
    taxonomy_raw,
    function(x) {

      x <- trimws(
        as.character(x)
      )

      x[
        is.na(x) |
          x == ""
      ] <- NA_character_

      x
    }
  ),
  row.names = taxonomy_otu_ids,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

taxonomy_raw <- taxonomy_raw[
  gtools::mixedorder(
    rownames(taxonomy_raw)
  ),
  ,
  drop = FALSE
]

###############################################################################
# 8. CHECK OTU IDENTIFIERS
###############################################################################

otus_missing_taxonomy <- setdiff(
  rownames(otu_counts),
  rownames(taxonomy_raw)
)

otus_missing_counts <- setdiff(
  rownames(taxonomy_raw),
  rownames(otu_counts)
)

if (length(otus_missing_taxonomy) > 0) {
  stop(
    paste(
      "OTUs present in the count table but absent from taxonomy:",
      paste(
        head(
          otus_missing_taxonomy,
          20
        ),
        collapse = ", "
      )
    )
  )
}

if (length(otus_missing_counts) > 0) {
  stop(
    paste(
      "OTUs present in taxonomy but absent from the count table:",
      paste(
        head(
          otus_missing_counts,
          20
        ),
        collapse = ", "
      )
    )
  )
}

###############################################################################
# 9. BUILD TAXONOMY STRINGS
#
# Taxonomic ranks are extracted by prefix rather than column position.
#
# This prevents a species label such as `s:uncultured_bacterium` from being
# interpreted as a phylum when intermediate ranks are absent.
###############################################################################

taxonomy_string <- apply(
  taxonomy_raw,
  1,
  function(x) {

    assigned_values <- x[
      !is.na(x) &
        x != ""
    ]

    paste(
      assigned_values,
      collapse = ";"
    )
  }
)

extract_rank <- function(
    taxonomy_string,
    prefix
) {

  pattern <- paste0(
    "(^|;)",
    prefix,
    ":([^;]+)"
  )

  extracted <- stringr::str_match(
    taxonomy_string,
    pattern
  )[
    ,
    3
  ]

  extracted <- trimws(
    extracted
  )

  extracted[
    is.na(extracted) |
      extracted == ""
  ] <- "unclassified"

  extracted
}

taxonomy <- tibble::tibble(
  OTU = rownames(
    taxonomy_raw
  ),
  domain = paste0(
    "d:",
    extract_rank(
      taxonomy_string,
      "d"
    )
  ),
  phylum = paste0(
    "p:",
    extract_rank(
      taxonomy_string,
      "p"
    )
  ),
  class = paste0(
    "c:",
    extract_rank(
      taxonomy_string,
      "c"
    )
  ),
  order = paste0(
    "o:",
    extract_rank(
      taxonomy_string,
      "o"
    )
  ),
  family = paste0(
    "f:",
    extract_rank(
      taxonomy_string,
      "f"
    )
  ),
  genus = paste0(
    "g:",
    extract_rank(
      taxonomy_string,
      "g"
    )
  ),
  species = paste0(
    "s:",
    extract_rank(
      taxonomy_string,
      "s"
    )
  ),
  tax_string = taxonomy_string
) |>
  tibble::column_to_rownames(
    "OTU"
  )

taxonomy$domain[
  taxonomy$domain == "d:unclassified"
] <- "unclassified"

taxonomy$phylum[
  taxonomy$phylum == "p:unclassified"
] <- "unclassified"

taxonomy$class[
  taxonomy$class == "c:unclassified"
] <- "unclassified"

taxonomy$order[
  taxonomy$order == "o:unclassified"
] <- "unclassified"

taxonomy$family[
  taxonomy$family == "f:unclassified"
] <- "unclassified"

taxonomy$genus[
  taxonomy$genus == "g:unclassified"
] <- "unclassified"

taxonomy$species[
  taxonomy$species == "s:unclassified"
] <- "unclassified"

###############################################################################
# 10. ADD GENUS TO ASSIGNED SPECIES LABELS
#
# This retains the species-label formatting used in the original analysis.
###############################################################################

taxonomy$species <- ifelse(
  grepl(
    "^s:",
    taxonomy$species
  ) &
    grepl(
      "^g:",
      taxonomy$genus
    ),
  paste0(
    sub(
      "^g:",
      "s:",
      taxonomy$genus
    ),
    "_",
    sub(
      "^s:",
      "",
      taxonomy$species
    )
  ),
  taxonomy$species
)

###############################################################################
# 11. VERIFY PHYLUM PARSING
###############################################################################

unexpected_phylum_prefix <- taxonomy |>
  tibble::rownames_to_column(
    "OTU"
  ) |>
  dplyr::filter(
    grepl(
      "^[s:g:f:o:c]:",
      .data$phylum
    )
  )

if (nrow(unexpected_phylum_prefix) > 0) {

  print(
    unexpected_phylum_prefix
  )

  stop(
    paste(
      "Taxonomy parsing error:",
      "species, genus, family, order or class labels were found",
      "in the phylum field."
    )
  )
}

valid_phylum_labels <- grepl(
  "^p:",
  taxonomy$phylum
) |
  taxonomy$phylum == "unclassified"

if (any(!valid_phylum_labels)) {
  stop(
    "Unexpected taxonomy labels were found in the phylum field."
  )
}

cat(
  "\nTaxonomy table loaded using prefix-based rank parsing.\n"
)

cat(
  "OTUs in taxonomy table:",
  nrow(taxonomy),
  "\n"
)

###############################################################################
# 12. RETAIN BACTERIA AND ARCHAEA
###############################################################################

taxonomy_bacteria_archaea <- taxonomy |>
  dplyr::filter(
    .data$domain %in% c(
      "d:Bacteria",
      "d:Archaea"
    )
  )

cat(
  "\nAfter retaining Bacteria and Archaea:\n"
)

cat(
  "OTUs:",
  nrow(taxonomy_bacteria_archaea),
  "\n"
)

###############################################################################
# 13. IDENTIFY CHLOROPLAST AND MITOCHONDRIAL OTUs
###############################################################################

organelle_pattern <- "chloroplast|mitochond"

organelle_otus <- taxonomy_bacteria_archaea |>
  dplyr::filter(
    .data$order == "o:Chloroplast" |
      .data$family == "f:Mitochondria" |
      stringr::str_detect(
        .data$tax_string,
        stringr::regex(
          organelle_pattern,
          ignore_case = TRUE
        )
      )
  ) |>
  rownames()

removed_taxonomy <- taxonomy_bacteria_archaea |>
  tibble::rownames_to_column(
    "OTU"
  ) |>
  dplyr::filter(
    .data$OTU %in% organelle_otus
  )

utils::write.table(
  removed_taxonomy,
  file = removed_taxonomy_file,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

cat(
  "\nChloroplast and mitochondrial OTUs identified:",
  length(organelle_otus),
  "\n"
)

###############################################################################
# 14. CREATE CLEAN TAXONOMY TABLE
###############################################################################

taxonomy_clean <- taxonomy_bacteria_archaea |>
  dplyr::filter(
    !rownames(
      taxonomy_bacteria_archaea
    ) %in% organelle_otus
  )

remaining_organelles <- taxonomy_clean |>
  dplyr::filter(
    .data$order == "o:Chloroplast" |
      .data$family == "f:Mitochondria" |
      stringr::str_detect(
        .data$tax_string,
        stringr::regex(
          organelle_pattern,
          ignore_case = TRUE
        )
      )
  )

if (nrow(remaining_organelles) > 0) {
  stop(
    "Chloroplast or mitochondrial OTUs remain after filtering."
  )
}

cat(
  "\nAfter removing chloroplast and mitochondrial OTUs:\n"
)

cat(
  "OTUs:",
  nrow(taxonomy_clean),
  "\n"
)

###############################################################################
# 15. FORMAT TAXONOMY FOR OUTPUT
#
# Examples:
#   d:Bacteria       -> k__Bacteria
#   p:Acidobacteriota -> p__Acidobacteriota
###############################################################################

format_taxonomic_rank <- function(
    x,
    original_prefix,
    output_prefix,
    unknown = "NA"
) {

  x <- as.character(
    x
  )

  x[
    is.na(x) |
      x == "" |
      x == "unclassified"
  ] <- unknown

  prefixed_values <- grepl(
    "^[dkpcofgs]:",
    x
  )

  correct_prefix <- grepl(
    paste0(
      "^",
      original_prefix,
      ":"
    ),
    x
  )

  x[
    prefixed_values &
      !correct_prefix
  ] <- unknown

  x <- sub(
    paste0(
      "^",
      original_prefix,
      ":"
    ),
    paste0(
      output_prefix,
      "__"
    ),
    x
  )

  x
}

format_taxonomy_for_output <- function(
    taxonomy_table
) {

  taxonomy_table |>
    tibble::rownames_to_column(
      "OTU"
    ) |>
    dplyr::transmute(
      OTU = .data$OTU,
      Kingdom = format_taxonomic_rank(
        .data$domain,
        "d",
        "k"
      ),
      Phylum = format_taxonomic_rank(
        .data$phylum,
        "p",
        "p"
      ),
      Class = format_taxonomic_rank(
        .data$class,
        "c",
        "c"
      ),
      Order = format_taxonomic_rank(
        .data$order,
        "o",
        "o"
      ),
      Family = format_taxonomic_rank(
        .data$family,
        "f",
        "f"
      ),
      Genus = format_taxonomic_rank(
        .data$genus,
        "g",
        "g"
      ),
      Species = format_taxonomic_rank(
        .data$species,
        "s",
        "s"
      ),
      LCA_raw = .data$tax_string
    )
}

taxonomy_bacteria_archaea_output <- format_taxonomy_for_output(
  taxonomy_bacteria_archaea
)

taxonomy_clean_output <- format_taxonomy_for_output(
  taxonomy_clean
)

###############################################################################
# 16. BUILD COMBINED COUNT, TAXONOMY AND RELATIVE-ABUNDANCE TABLE
###############################################################################

make_combined_table <- function(
    count_table,
    taxonomy_table
) {

  selected_otus <- taxonomy_table$OTU

  missing_selected_otus <- setdiff(
    selected_otus,
    rownames(count_table)
  )

  if (length(missing_selected_otus) > 0) {
    stop(
      "Selected taxonomy OTUs are missing from the count table."
    )
  }

  count_table <- count_table[
    selected_otus,
    samples_all,
    drop = FALSE
  ]

  sample_read_totals <- colSums(
    count_table
  )

  if (any(sample_read_totals <= 0)) {
    stop(
      paste(
        "Samples with zero reads after filtering:",
        paste(
          names(sample_read_totals)[
            sample_read_totals <= 0
          ],
          collapse = ", "
        )
      )
    )
  }

  otu_levels <- gtools::mixedsort(
    selected_otus
  )

  counts_long <- count_table |>
    as.data.frame(
      check.names = FALSE
    ) |>
    tibble::rownames_to_column(
      "OTU"
    ) |>
    tidyr::pivot_longer(
      cols = dplyr::all_of(
        samples_all
      ),
      names_to = "Sample",
      values_to = "Count"
    ) |>
    dplyr::mutate(
      OTU = factor(
        .data$OTU,
        levels = otu_levels
      ),
      Sample = factor(
        .data$Sample,
        levels = samples_all
      ),
      Count = as.numeric(
        .data$Count
      )
    )

  combined_table <- counts_long |>
    dplyr::group_by(
      .data$Sample
    ) |>
    dplyr::mutate(
      Abundance = .data$Count /
        sum(
          .data$Count,
          na.rm = TRUE
        ),
      `Relative abundance` = .data$Abundance
    ) |>
    dplyr::ungroup() |>
    dplyr::mutate(
      OTU = as.character(
        .data$OTU
      )
    ) |>
    dplyr::left_join(
      taxonomy_table,
      by = "OTU"
    ) |>
    dplyr::mutate(
      Sample = factor(
        as.character(
          .data$Sample
        ),
        levels = samples_all
      ),
      OTU = factor(
        .data$OTU,
        levels = otu_levels
      ),
      Phylum = tidyr::replace_na(
        .data$Phylum,
        "NA"
      )
    ) |>
    dplyr::select(
      OTU,
      Sample,
      Count,
      Abundance,
      `Relative abundance`,
      Kingdom,
      Phylum,
      Class,
      Order,
      Family,
      Genus,
      Species,
      LCA_raw
    ) |>
    dplyr::arrange(
      .data$Sample,
      .data$OTU
    ) |>
    dplyr::mutate(
      OTU = as.character(
        .data$OTU
      ),
      Sample = as.character(
        .data$Sample
      )
    )

  expected_rows <- length(
    selected_otus
  ) * length(
    samples_all
  )

  if (nrow(combined_table) != expected_rows) {
    stop(
      paste0(
        "Unexpected number of rows in the combined table. Expected ",
        expected_rows,
        " but obtained ",
        nrow(combined_table),
        "."
      )
    )
  }

  combined_table
}

###############################################################################
# 17. BUILD TABLE INCLUDING ORGANELLES
###############################################################################

combined_with_organelles <- make_combined_table(
  count_table = otu_counts,
  taxonomy_table = taxonomy_bacteria_archaea_output
)

cat(
  "\nCombined table including organelles created.\n"
)

cat(
  "Rows:",
  nrow(combined_with_organelles),
  "\n"
)

cat(
  "OTUs:",
  dplyr::n_distinct(
    combined_with_organelles$OTU
  ),
  "\n"
)

###############################################################################
# 18. BUILD CLEAN TABLE WITHOUT ORGANELLES
###############################################################################

combined_clean <- make_combined_table(
  count_table = otu_counts,
  taxonomy_table = taxonomy_clean_output
)

cat(
  "\nClean combined table created.\n"
)

cat(
  "Rows:",
  nrow(combined_clean),
  "\n"
)

cat(
  "OTUs:",
  dplyr::n_distinct(
    combined_clean$OTU
  ),
  "\n"
)

###############################################################################
# 19. CHECK RELATIVE-ABUNDANCE SUMS
###############################################################################

check_with_organelles <- combined_with_organelles |>
  dplyr::group_by(
    .data$Sample
  ) |>
  dplyr::summarise(
    table = "with_chloroplast_mitochondria",
    abundance_sum = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::mutate(
    difference_from_one = .data$abundance_sum - 1
  )

check_clean <- combined_clean |>
  dplyr::group_by(
    .data$Sample
  ) |>
  dplyr::summarise(
    table = "without_chloroplast_mitochondria",
    abundance_sum = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::mutate(
    difference_from_one = .data$abundance_sum - 1
  )

abundance_check <- dplyr::bind_rows(
  check_with_organelles,
  check_clean
)

if (any(
  abs(
    abundance_check$difference_from_one
  ) > 1e-10
)) {
  stop(
    "At least one sample relative-abundance total differs from 1."
  )
}

utils::write.table(
  abundance_check,
  file = abundance_check_file,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

###############################################################################
# 20. VERIFY CLEAN OUTPUT
###############################################################################

clean_organelle_rows <- combined_clean |>
  dplyr::filter(
    stringr::str_detect(
      paste(
        .data$Kingdom,
        .data$Phylum,
        .data$Class,
        .data$Order,
        .data$Family,
        .data$Genus,
        .data$Species,
        .data$LCA_raw,
        sep = ";"
      ),
      stringr::regex(
        organelle_pattern,
        ignore_case = TRUE
      )
    )
  )

if (nrow(clean_organelle_rows) > 0) {
  stop(
    "Chloroplast or mitochondrial rows remain in the clean output table."
  )
}

unexpected_output_phyla <- combined_clean |>
  dplyr::filter(
    grepl(
      "^(s__|g__|f__|o__|c__)",
      .data$Phylum
    )
  )

if (nrow(unexpected_output_phyla) > 0) {
  stop(
    "Incorrect taxonomic prefixes were found in the output Phylum column."
  )
}

###############################################################################
# 21. CREATE ORGANELLE-REMOVAL REPORT
###############################################################################

removed_report <- combined_with_organelles |>
  dplyr::group_by(
    .data$Sample
  ) |>
  dplyr::summarise(
    total_before = sum(
      .data$Abundance,
      na.rm = TRUE
    ),
    .groups = "drop"
  ) |>
  dplyr::left_join(
    combined_with_organelles |>
      dplyr::filter(
        .data$OTU %in% organelle_otus
      ) |>
      dplyr::group_by(
        .data$Sample
      ) |>
      dplyr::summarise(
        removed_abundance = sum(
          .data$Abundance,
          na.rm = TRUE
        ),
        removed_reads = sum(
          .data$Count,
          na.rm = TRUE
        ),
        .groups = "drop"
      ),
    by = "Sample"
  ) |>
  dplyr::mutate(
    removed_abundance = tidyr::replace_na(
      .data$removed_abundance,
      0
    ),
    removed_reads = tidyr::replace_na(
      .data$removed_reads,
      0
    ),
    percent_removed = .data$removed_abundance /
      .data$total_before * 100
  ) |>
  dplyr::arrange(
    dplyr::desc(
      .data$percent_removed
    )
  )

utils::write.table(
  removed_report,
  file = removed_report_file,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  na = "NA"
)

###############################################################################
# 22. WRITE EXCEL TABLES
###############################################################################

writexl::write_xlsx(
  list(
    relative_abundance = combined_with_organelles
  ),
  path = with_organelles_file
)

writexl::write_xlsx(
  list(
    relative_abundance = combined_clean
  ),
  path = clean_output_file
)

###############################################################################
# 23. SESSION INFORMATION
###############################################################################

writeLines(
  capture.output(
    sessionInfo()
  ),
  session_info_file
)

###############################################################################
# 24. FINAL SUMMARY
###############################################################################

cat(
  "\n16S rRNA community-table preparation completed successfully.\n"
)

cat(
  "\nInput OTUs:",
  nrow(otu_counts),
  "\n"
)

cat(
  "Bacterial and archaeal OTUs:",
  nrow(taxonomy_bacteria_archaea),
  "\n"
)

cat(
  "Chloroplast and mitochondrial OTUs removed:",
  length(organelle_otus),
  "\n"
)

cat(
  "OTUs retained in clean table:",
  nrow(taxonomy_clean),
  "\n"
)

cat(
  "Samples retained:",
  length(samples_all),
  "\n"
)

cat(
  "\nPrimary output:\n",
  normalizePath(clean_output_file),
  "\n",
  sep = ""
)

cat(
  "\nOrganelle-removal summary:\n"
)

print(
  summary(
    removed_report$percent_removed
  )
)
