#!/usr/bin/env python3

# DESCRIPTION
# Applies the final BLASTn filters used in this study and identifies credible
# external-dataset matches to conserved EET gene cassettes.
#
# A credible match requires, on the same target contig:
#   1. at least one essential EET gene; and
#   2. at least one additional distinct gene from the same query cassette.
#
# Default hit filters:
#   E-value <= 1e-10
#   nucleotide identity >= 95%
#   query coverage >= 95%
#   gap openings = 0
#
# INPUT
# 1. Raw BLASTn outfmt 6 table generated by
#    01_run_BLASTn_external_MAGs.sh.
# 2. Contig-to-MAG mapping generated by
#    02_build_contig_to_MAG_mapping.py.
# 3. A text file containing one essential query-gene identifier per line.
#
# Query identifiers are expected to follow:
#   query_MAG|queryGene
#
# The query cassette is inferred from the query gene identifier by removing
# the final Prodigal-style numeric suffix from queryGene.
#
# OUTPUT
# Filtered hits, one best hit per query gene and target contig, cassette-level
# gene counts, credible cassette calls and a target-MAG list for GTDB-Tk.
#
# USAGE
# python3 03_call_credible_EET_cassettes_from_BLASTn.py \
#   --blast-tsv SPRUCE_EET_genes_BLASTn.tsv \
#   --dataset SPRUCE \
#   --contig-to-mag contig_to_MAG.tsv \
#   --essential-gene-ids EET_essential_gene_ids.txt \
#   --output-dir SPRUCE_credible_calls

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

import pandas as pd


BLAST_COLUMNS = [
    "qseqid",
    "sseqid",
    "pident",
    "length",
    "mismatch",
    "gapopen",
    "qstart",
    "qend",
    "sstart",
    "send",
    "evalue",
    "bitscore",
    "qlen",
    "slen",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Filter BLASTn hits and call credible EET cassette matches on "
            "individual target contigs."
        )
    )

    parser.add_argument("--blast-tsv", required=True, type=Path)
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--contig-to-mag", required=True, type=Path)
    parser.add_argument("--essential-gene-ids", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)

    parser.add_argument("--max-evalue", type=float, default=1e-10)
    parser.add_argument("--min-pident", type=float, default=95.0)
    parser.add_argument("--min-qcov", type=float, default=95.0)
    parser.add_argument("--max-gapopen", type=int, default=0)

    parser.add_argument(
        "--min-total-genes",
        type=int,
        default=2,
        help=(
            "Minimum distinct genes from one cassette on the same target "
            "contig. Default: 2."
        ),
    )
    parser.add_argument(
        "--min-essential-genes",
        type=int,
        default=1,
        help=(
            "Minimum distinct essential genes from one cassette on the same "
            "target contig. Default: 1."
        ),
    )
    parser.add_argument(
        "--allow-unmapped-contigs",
        action="store_true",
        help=(
            "Continue when filtered target contigs are absent from the "
            "contig-to-MAG mapping. By default this is an error."
        ),
    )

    return parser.parse_args()


def require_nonempty(path: Path, label: str) -> None:
    if not path.is_file() or path.stat().st_size == 0:
        raise FileNotFoundError(f"{label} is missing or empty: {path}")


def split_query_identifier(qseqid: str) -> tuple[str, str, str, str]:
    value = str(qseqid)

    if "|" in value:
        query_mag, query_gene = value.split("|", 1)
    else:
        query_mag = ""
        query_gene = value

    query_contig = re.sub(r"_[0-9]+$", "", query_gene)

    cassette_id = (
        f"{query_mag}|{query_contig}"
        if query_mag
        else query_contig
    )

    return query_mag, query_gene, query_contig, cassette_id


def normalize_target_contig(sseqid: str) -> str:
    value = str(sseqid).strip()
    token = value.split()[0]

    accession = re.search(r"([A-Za-z0-9_]+\.[0-9]+)", token)
    return accession.group(1) if accession else token


def read_essential_gene_ids(path: Path) -> set[str]:
    require_nonempty(path, "Essential-gene list")

    identifiers: set[str] = set()

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            value = raw_line.strip()

            if not value or value.startswith("#"):
                continue

            identifiers.add(value)

    if not identifiers:
        raise ValueError(f"No essential gene identifiers found in: {path}")

    return identifiers


def write_empty_table(path: Path, columns: list[str]) -> None:
    pd.DataFrame(columns=columns).to_csv(
        path,
        sep="\t",
        index=False,
    )


def main() -> None:
    args = parse_args()

    require_nonempty(args.blast_tsv, "BLASTn table")
    require_nonempty(args.contig_to_mag, "Contig-to-MAG mapping")

    if not args.dataset.strip():
        raise ValueError("--dataset cannot be empty.")

    if args.min_total_genes < 2:
        raise ValueError(
            "--min-total-genes must be at least 2 because a credible call "
            "requires an essential gene plus an additional cassette gene."
        )

    if args.min_essential_genes < 1:
        raise ValueError("--min-essential-genes must be at least 1.")

    output_dir = args.output_dir.resolve()

    if output_dir.exists() and any(output_dir.iterdir()):
        raise FileExistsError(
            f"Output directory exists and is not empty: {output_dir}"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    essential = read_essential_gene_ids(args.essential_gene_ids)

    mapping = pd.read_csv(
        args.contig_to_mag,
        sep="\t",
        dtype=str,
    )

    required_mapping_columns = {
        "target_contig",
        "target_MAG",
    }

    missing_mapping = required_mapping_columns - set(mapping.columns)

    if missing_mapping:
        raise ValueError(
            "Contig-to-MAG table is missing columns: "
            + ", ".join(sorted(missing_mapping))
        )

    if mapping["target_contig"].duplicated().any():
        duplicates = (
            mapping.loc[
                mapping["target_contig"].duplicated(keep=False),
                "target_contig",
            ]
            .drop_duplicates()
            .tolist()
        )
        raise ValueError(
            "Duplicated target contigs in mapping. Examples: "
            + ", ".join(duplicates[:10])
        )

    hits = pd.read_csv(
        args.blast_tsv,
        sep="\t",
        header=None,
        names=BLAST_COLUMNS,
    )

    if hits.empty:
        print("BLASTn table contains no hits.")
        write_empty_table(
            output_dir / f"{args.dataset}__filtered_BLASTn_hits.tsv",
            BLAST_COLUMNS,
        )
        write_empty_table(
            output_dir / f"{args.dataset}__credible_EET_cassette_calls.tsv",
            [
                "cassette_id",
                "dataset",
                "target_MAG",
                "target_contig",
                "n_total_genes",
                "n_essential_genes",
            ],
        )
        (
            output_dir
            / f"{args.dataset}__target_MAGs_for_GTDBTk.list"
        ).write_text("", encoding="utf-8")
        return

    numeric_columns = [
        "pident",
        "length",
        "mismatch",
        "gapopen",
        "qstart",
        "qend",
        "sstart",
        "send",
        "evalue",
        "bitscore",
        "qlen",
        "slen",
    ]

    for column in numeric_columns:
        hits[column] = pd.to_numeric(
            hits[column],
            errors="raise",
        )

    hits["dataset"] = args.dataset

    hits["qcov"] = (
        hits["length"]
        / hits["qlen"]
        * 100.0
    )

    parsed = hits["qseqid"].map(split_query_identifier)

    hits["query_MAG"] = [value[0] for value in parsed]
    hits["query_gene"] = [value[1] for value in parsed]
    hits["query_contig"] = [value[2] for value in parsed]
    hits["cassette_id"] = [value[3] for value in parsed]

    hits["target_contig"] = (
        hits["sseqid"]
        .map(normalize_target_contig)
    )

    filtered = hits[
        (hits["evalue"] <= args.max_evalue)
        & (hits["pident"] >= args.min_pident)
        & (hits["qcov"] >= args.min_qcov)
        & (hits["gapopen"] <= args.max_gapopen)
    ].copy()

    filtered = filtered.merge(
        mapping,
        on="target_contig",
        how="left",
        validate="many_to_one",
    )

    n_unmapped = int(filtered["target_MAG"].isna().sum())

    if n_unmapped and not args.allow_unmapped_contigs:
        examples = (
            filtered.loc[
                filtered["target_MAG"].isna(),
                "target_contig",
            ]
            .drop_duplicates()
            .head(10)
            .tolist()
        )
        raise ValueError(
            f"{n_unmapped} filtered hits map to contigs absent from the "
            "contig-to-MAG table. Examples: "
            + ", ".join(examples)
        )

    filtered["is_essential"] = (
        filtered["query_gene"].isin(essential)
        | filtered["qseqid"].isin(essential)
    )

    filtered_path = (
        output_dir
        / f"{args.dataset}__filtered_BLASTn_hits.tsv"
    )
    filtered.to_csv(
        filtered_path,
        sep="\t",
        index=False,
    )

    if filtered.empty:
        best = filtered.copy()
        counts = pd.DataFrame()
        credible = pd.DataFrame()
    else:
        best = (
            filtered.sort_values(
                ["bitscore", "qcov", "pident"],
                ascending=[False, False, False],
            )
            .drop_duplicates(
                subset=[
                    "cassette_id",
                    "query_gene",
                    "dataset",
                    "target_contig",
                ]
            )
            .copy()
        )

        group_columns = [
            "cassette_id",
            "query_MAG",
            "query_contig",
            "dataset",
            "target_MAG",
            "target_contig",
        ]

        count_rows: list[dict[str, object]] = []

        for keys, group in best.groupby(
            group_columns,
            dropna=False,
            sort=True,
        ):
            key_values = dict(zip(group_columns, keys))

            query_genes = sorted(
                set(group["query_gene"].astype(str))
            )
            essential_genes = sorted(
                set(
                    group.loc[
                        group["is_essential"],
                        "query_gene",
                    ].astype(str)
                )
            )

            count_rows.append(
                {
                    **key_values,
                    "n_total_genes": len(query_genes),
                    "n_essential_genes": len(essential_genes),
                    "query_genes": ",".join(query_genes),
                    "essential_genes": ",".join(essential_genes),
                    "best_bitscore": group["bitscore"].max(),
                    "best_pident": group["pident"].max(),
                    "best_qcov": group["qcov"].max(),
                    "best_evalue": group["evalue"].min(),
                }
            )

        counts = pd.DataFrame(count_rows)

        credible = counts[
            (counts["n_total_genes"] >= args.min_total_genes)
            & (
                counts["n_essential_genes"]
                >= args.min_essential_genes
            )
        ].copy()

        credible["call_label"] = (
            f"essential{args.min_essential_genes}"
            f"_plus_total{args.min_total_genes}"
            "_same_contig"
        )

    best_path = (
        output_dir
        / f"{args.dataset}__best_hit_per_gene_target_contig.tsv"
    )
    best.to_csv(best_path, sep="\t", index=False)

    counts_path = (
        output_dir
        / f"{args.dataset}__cassette_gene_counts_by_target_contig.tsv"
    )

    if counts.empty:
        write_empty_table(
            counts_path,
            [
                "cassette_id",
                "query_MAG",
                "query_contig",
                "dataset",
                "target_MAG",
                "target_contig",
                "n_total_genes",
                "n_essential_genes",
                "query_genes",
                "essential_genes",
                "best_bitscore",
                "best_pident",
                "best_qcov",
                "best_evalue",
            ],
        )
    else:
        counts.to_csv(counts_path, sep="\t", index=False)

    credible_path = (
        output_dir
        / f"{args.dataset}__credible_EET_cassette_calls.tsv"
    )

    if credible.empty:
        write_empty_table(
            credible_path,
            [
                "cassette_id",
                "query_MAG",
                "query_contig",
                "dataset",
                "target_MAG",
                "target_contig",
                "n_total_genes",
                "n_essential_genes",
                "query_genes",
                "essential_genes",
                "best_bitscore",
                "best_pident",
                "best_qcov",
                "best_evalue",
                "call_label",
            ],
        )
        target_mags: list[str] = []
    else:
        credible.to_csv(
            credible_path,
            sep="\t",
            index=False,
        )
        target_mags = sorted(
            set(
                credible["target_MAG"]
                .dropna()
                .astype(str)
            )
        )

    mag_list_path = (
        output_dir
        / f"{args.dataset}__target_MAGs_for_GTDBTk.list"
    )
    mag_list_path.write_text(
        "\n".join(target_mags)
        + ("\n" if target_mags else ""),
        encoding="utf-8",
    )

    summary_rows = [
        {
            "metric": "raw_BLASTn_hits",
            "value": len(hits),
        },
        {
            "metric": "filtered_BLASTn_hits",
            "value": len(filtered),
        },
        {
            "metric": "best_gene_target_contig_hits",
            "value": len(best),
        },
        {
            "metric": "credible_cassette_target_contig_calls",
            "value": len(credible),
        },
        {
            "metric": "credible_query_cassettes",
            "value": (
                credible["cassette_id"].nunique()
                if not credible.empty
                else 0
            ),
        },
        {
            "metric": "credible_target_contigs",
            "value": (
                credible["target_contig"].nunique()
                if not credible.empty
                else 0
            ),
        },
        {
            "metric": "credible_target_MAGs",
            "value": len(target_mags),
        },
    ]

    summary_path = (
        output_dir
        / f"{args.dataset}__BLASTn_credible_call_summary.tsv"
    )

    with summary_path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["metric", "value"],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(summary_rows)

    print("Credible EET cassette calling completed successfully.")
    print(f"Dataset: {args.dataset}")
    print(f"Raw hits: {len(hits)}")
    print(f"Filtered hits: {len(filtered)}")
    print(f"Credible same-contig calls: {len(credible)}")
    print(f"Credible target MAGs: {len(target_mags)}")
    print(f"Output directory: {output_dir}")


if __name__ == "__main__":
    main()
