#!/usr/bin/env Rscript

###############################################################################
# EXTENDED DATA FIGURE 1D — dbRDA OF BM, LM AND NR
#
# DESCRIPTION
# Generates the dbRDA of BM, LM and NR spatial 16S rRNA communities using
# CO2:CH4 ratio, pH, temperature and conductivity.
#
# INPUT
# Microbial community table generated by:
# scripts/analyses/01_16S_rRNA_analysis/
# 04_prepare_16S_community_table.R
#
# Environmental metadata:
# Supplementary_Table_2.xlsx
#
# Required microbial columns:
# Sample, OTU, Abundance
#
# BM.3.10 is intentionally excluded.
#
# OUTPUT
# EDFigure1D_dbRDA_BM_LM_NR.svg
#
# USAGE
# Rscript EDFigure1D_dbRDA_BM_LM_NR.R \
#   microbial_table.xlsx \
#   Supplementary_Table_2.xlsx \
#   output_directory
###############################################################################

required_packages <- c(
  "dplyr", "ggplot2", "ggrepel", "readxl",
  "scales", "svglite", "tidyr", "vegan"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_packages, collapse = ", ")
  )
}

set.seed(123)

###############################################################################
# INPUT AND OUTPUT
###############################################################################

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 2 || length(args) > 3) {
  stop(
    paste(
      "Usage: Rscript EDFigure1D_dbRDA_BM_LM_NR.R",
      "<microbial_table.xlsx>",
      "<Supplementary_Table_2.xlsx>",
      "[output_directory]"
    )
  )
}

microbial_file <- args[[1]]
metadata_file <- args[[2]]
output_dir <- if (length(args) == 3) args[[3]] else "."

if (!file.exists(microbial_file)) {
  stop("Microbial table not found: ", microbial_file)
}

if (!file.exists(metadata_file)) {
  stop("Metadata table not found: ", metadata_file)
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

output_svg <- file.path(
  output_dir,
  "EDFigure1D_dbRDA_BM_LM_NR.svg"
)

###############################################################################
# LOAD MICROBIAL TABLE
###############################################################################

microbial_data <- readxl::read_excel(
  microbial_file,
  sheet = "relative_abundance"
)

names(microbial_data) <- trimws(names(microbial_data))

required_microbial_columns <- c(
  "Sample",
  "OTU",
  "Abundance"
)

missing_microbial_columns <- setdiff(
  required_microbial_columns,
  names(microbial_data)
)

if (length(missing_microbial_columns) > 0) {
  stop(
    "Missing microbial columns: ",
    paste(missing_microbial_columns, collapse = ", ")
  )
}

microbial_data <- microbial_data |>
  dplyr::transmute(
    Sample = trimws(as.character(.data$Sample)),
    OTU = trimws(as.character(.data$OTU)),
    Abundance = suppressWarnings(as.numeric(.data$Abundance))
  )

if (anyNA(microbial_data$Sample) ||
    anyNA(microbial_data$OTU) ||
    anyNA(microbial_data$Abundance)) {
  stop("Missing or non-numeric values found in the microbial table.")
}

if (anyDuplicated(
  paste(
    microbial_data$Sample,
    microbial_data$OTU,
    sep = "__"
  )
)) {
  stop("Duplicated Sample × OTU rows found in the microbial table.")
}

###############################################################################
# LOAD ENVIRONMENTAL METADATA
###############################################################################

environmental_raw <- readxl::read_excel(
  metadata_file,
  sheet = "Supplementary_Table_2",
  skip = 4,
  na = ""
)

names(environmental_raw) <- trimws(names(environmental_raw))

required_metadata_columns <- c(
  "Sampling",
  "Peatland",
  "Site",
  "Depth (cm)",
  "pH",
  "Temperature (°C)",
  "Electrical conductivity (μS cm⁻¹)",
  "CO₂:CH₄ (mol mol⁻¹)"
)

missing_metadata_columns <- setdiff(
  required_metadata_columns,
  names(environmental_raw)
)

if (length(missing_metadata_columns) > 0) {
  stop(
    "Missing metadata columns: ",
    paste(missing_metadata_columns, collapse = ", ")
  )
}

to_numeric_metadata <- function(x) {
  x <- trimws(as.character(x))
  x[x %in% c("-", "–", "—")] <- "0"
  x[x == ""] <- NA_character_
  suppressWarnings(as.numeric(x))
}

environmental_data <- environmental_raw |>
  tidyr::fill(
    .data$Sampling,
    .data$Peatland,
    .data$Site,
    .direction = "down"
  ) |>
  dplyr::filter(
    .data$Sampling == "Spatial profiling"
  ) |>
  dplyr::mutate(
    Group = dplyr::case_when(
      .data$Peatland == "Björsmossen" ~ "BM",
      .data$Peatland == "Lungsmossen" ~ "LM",
      .data$Peatland == "Norra Romyren" ~ "NR",
      TRUE ~ NA_character_
    ),
    Site = suppressWarnings(as.integer(.data$Site)),
    Depth_end = suppressWarnings(
      as.integer(
        sub(
          ".*[-–—]",
          "",
          as.character(.data$`Depth (cm)`)
        )
      )
    ),
    Sample = paste(
      .data$Group,
      .data$Site,
      .data$Depth_end,
      sep = "."
    )
  ) |>
  dplyr::transmute(
    Sample,
    Group,
    CO2_CH4 = to_numeric_metadata(
      .data$`CO₂:CH₄ (mol mol⁻¹)`
    ),
    pH = to_numeric_metadata(
      .data$pH
    ),
    Temperature = to_numeric_metadata(
      .data$`Temperature (°C)`
    ),
    Conductivity = to_numeric_metadata(
      .data$`Electrical conductivity (μS cm⁻¹)`
    )
  ) |>
  dplyr::filter(
    .data$Group %in% c("BM", "LM", "NR"),
    .data$Sample != "BM.3.10"
  )

if (anyDuplicated(environmental_data$Sample)) {
  stop("Duplicated sample identifiers found in the metadata.")
}

###############################################################################
# MATCH SAMPLES
###############################################################################

matching_samples <- intersect(
  unique(microbial_data$Sample),
  unique(environmental_data$Sample)
)

if (length(matching_samples) == 0) {
  stop("No samples match between microbial data and metadata.")
}

selected_variables <- c(
  "CO2_CH4",
  "pH",
  "Temperature",
  "Conductivity"
)

environmental_complete <- environmental_data |>
  dplyr::filter(
    .data$Sample %in% matching_samples
  ) |>
  dplyr::select(
    Sample,
    Group,
    dplyr::all_of(selected_variables)
  ) |>
  dplyr::filter(
    stats::complete.cases(
      dplyr::across(
        dplyr::all_of(selected_variables)
      )
    )
  ) |>
  dplyr::arrange(.data$Sample)

if (nrow(environmental_complete) <= length(selected_variables) + 1) {
  stop("Too few complete samples for the dbRDA.")
}

microbial_selected <- microbial_data |>
  dplyr::filter(
    .data$Sample %in% environmental_complete$Sample,
    .data$Sample != "BM.3.10"
  )

###############################################################################
# COMMUNITY MATRIX
###############################################################################

community_wide <- microbial_selected |>
  dplyr::select(
    Sample,
    OTU,
    Abundance
  ) |>
  tidyr::pivot_wider(
    names_from = OTU,
    values_from = Abundance,
    values_fill = list(Abundance = 0)
  ) |>
  dplyr::arrange(.data$Sample)

community_matrix <- community_wide |>
  dplyr::select(-Sample) |>
  as.matrix()

storage.mode(community_matrix) <- "numeric"
rownames(community_matrix) <- community_wide$Sample

community_matrix <- community_matrix[
  environmental_complete$Sample,
  ,
  drop = FALSE
]

if (anyNA(community_matrix)) {
  stop("NA values found in the community matrix.")
}

###############################################################################
# TRANSFORMATIONS
###############################################################################

zero_variance_variables <- selected_variables[
  vapply(
    environmental_complete[selected_variables],
    function(x) stats::sd(x, na.rm = TRUE) == 0,
    FUN.VALUE = logical(1)
  )
]

if (length(zero_variance_variables) > 0) {
  stop(
    "Zero-variance variables: ",
    paste(zero_variance_variables, collapse = ", ")
  )
}

environmental_scaled <- environmental_complete

environmental_scaled[selected_variables] <- scale(
  environmental_complete[selected_variables]
)

rownames(environmental_scaled) <- environmental_scaled$Sample

community_hellinger <- vegan::decostand(
  community_matrix,
  method = "hellinger"
)

###############################################################################
# PERMANOVA AND dbRDA
###############################################################################

environmental_model <- environmental_scaled[
  ,
  selected_variables,
  drop = FALSE
]

permanova_formula <- stats::reformulate(
  selected_variables,
  response = "community_hellinger"
)

permanova_result <- vegan::adonis2(
  permanova_formula,
  data = environmental_model,
  method = "bray",
  permutations = 999
)

print(permanova_result)

dbrda_model <- vegan::capscale(
  community_hellinger ~ .,
  data = environmental_model,
  distance = "bray"
)

constrained_eigenvalues <- dbrda_model$CCA$eig

if (length(constrained_eigenvalues) < 2) {
  stop("The dbRDA produced fewer than two constrained axes.")
}

constrained_percent <- constrained_eigenvalues /
  sum(constrained_eigenvalues) * 100

axis1_percent <- round(constrained_percent[1], 2)
axis2_percent <- round(constrained_percent[2], 2)

###############################################################################
# SITE SCORES
###############################################################################

site_scores <- as.data.frame(
  vegan::scores(
    dbrda_model,
    display = "sites",
    scaling = 2
  )
)

site_scores$Sample <- rownames(site_scores)

site_scores <- site_scores |>
  dplyr::left_join(
    environmental_scaled |>
      dplyr::select(
        Sample,
        Group
      ),
    by = "Sample"
  )

###############################################################################
# ENVIRONMENTAL VECTORS
###############################################################################

environmental_fit <- vegan::envfit(
  dbrda_model,
  environmental_model,
  permutations = 999
)

vector_scores <- as.data.frame(
  vegan::scores(
    environmental_fit,
    display = "vectors"
  )
)

vector_scores$Variable <- rownames(vector_scores)

p_values <- data.frame(
  Variable = names(environmental_fit$vectors$pvals),
  p_value = environmental_fit$vectors$pvals
)

variable_labels <- c(
  CO2_CH4 = "CO2:CH4",
  pH = "pH",
  Temperature = "Temperature",
  Conductivity = "Conductivity"
)

vector_scores <- vector_scores |>
  dplyr::left_join(
    p_values,
    by = "Variable"
  ) |>
  dplyr::mutate(
    significance = dplyr::case_when(
      .data$p_value < 0.001 ~ "***",
      .data$p_value < 0.01 ~ "**",
      .data$p_value < 0.05 ~ "*",
      TRUE ~ "ns"
    ),
    Variable_label = unname(
      variable_labels[.data$Variable]
    ),
    label = paste0(
      .data$Variable_label,
      " (",
      .data$significance,
      ")"
    ),
    CAP1_plot = .data$CAP1 * 1.3,
    CAP2_plot = .data$CAP2 * 1.3
  )

###############################################################################
# PLOT
###############################################################################

group_colors <- c(
  "BM" = "#3366CC",
  "LM" = "#1B7741",
  "NR" = "#E6863B"
)

p_dbrda <- ggplot2::ggplot(
  site_scores,
  ggplot2::aes(
    x = .data$CAP1,
    y = .data$CAP2,
    colour = .data$Group
  )
) +
  ggplot2::stat_ellipse(
    level = 0.95,
    linewidth = 0.9,
    alpha = 0.35
  ) +
  ggplot2::geom_point(
    size = 4.5,
    alpha = 0.9
  ) +
  ggrepel::geom_text_repel(
    ggplot2::aes(
      label = .data$Sample
    ),
    size = 4.2,
    colour = "black",
    max.overlaps = 100
  ) +
  ggplot2::geom_segment(
    data = vector_scores,
    ggplot2::aes(
      x = 0,
      y = 0,
      xend = .data$CAP1_plot,
      yend = .data$CAP2_plot
    ),
    arrow = grid::arrow(
      length = grid::unit(0.22, "cm"),
      type = "open"
    ),
    colour = scales::alpha(
      "grey20",
      0.65
    ),
    linewidth = 0.9,
    inherit.aes = FALSE
  ) +
  ggrepel::geom_text_repel(
    data = vector_scores,
    ggplot2::aes(
      x = .data$CAP1_plot * 1.02,
      y = .data$CAP2_plot * 1.02,
      label = .data$label
    ),
    size = 5,
    colour = "black",
    force = 2,
    inherit.aes = FALSE
  ) +
  ggplot2::scale_colour_manual(
    values = group_colors
  ) +
  ggplot2::labs(
    title = "dbRDA (BM, LM and NR — shared environmental variables)",
    x = paste0(
      "dbRDA1 (",
      axis1_percent,
      "%)"
    ),
    y = paste0(
      "dbRDA2 (",
      axis2_percent,
      "%)"
    ),
    colour = "Peatland"
  ) +
  ggplot2::theme_classic(
    base_size = 18
  ) +
  ggplot2::theme(
    panel.grid = ggplot2::element_blank(),
    axis.line = ggplot2::element_line(
      colour = "black",
      linewidth = 0.4
    ),
    legend.position = "right",
    plot.title = ggplot2::element_text(
      size = 20,
      face = "bold"
    ),
    axis.title = ggplot2::element_text(
      size = 18
    ),
    axis.text = ggplot2::element_text(
      size = 15
    ),
    legend.title = ggplot2::element_text(
      size = 17
    ),
    legend.text = ggplot2::element_text(
      size = 15
    )
  )

print(p_dbrda)

ggplot2::ggsave(
  filename = output_svg,
  plot = p_dbrda,
  device = svglite::svglite,
  width = 8,
  height = 8,
  units = "in",
  bg = "white"
)

cat(
  "\nExtended Data Figure 1D saved to:\n",
  output_svg,
  "\n",
  sep = ""
)
