#!/usr/bin/env Rscript

###############################################################################
# EXTENDED DATA FIGURE 1C — ALPHA DIVERSITY
#
# DESCRIPTION
# Generates observed-richness, Shannon-diversity and Pielou-evenness plots.
#
# INPUT
# alpha_diversity_analysis_objects.rds
#
# Generated by:
# scripts/analyses/01_16S_rRNA_analysis/
# 02_alpha_diversity_analysis.R
#
# OUTPUT
# EDFigure1C_alpha_diversity.svg
#
# USAGE
# Rscript EDFigure1C_alpha_diversity.R \
#   alpha_diversity_analysis_objects.rds \
#   output_directory
###############################################################################

required_packages <- c(
  "dplyr",
  "ggbeeswarm",
  "ggplot2",
  "svglite",
  "tidyr"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_packages, collapse = ", ")
  )
}

###############################################################################
# INPUT AND OUTPUT
###############################################################################

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 1 || length(args) > 2) {
  stop(
    paste(
      "Usage:",
      "Rscript EDFigure1C_alpha_diversity.R",
      "<alpha_diversity_analysis_objects.rds>",
      "[output_directory]"
    )
  )
}

input_file <- args[[1]]

output_dir <- if (length(args) == 2) {
  args[[2]]
} else {
  "."
}

if (!file.exists(input_file)) {
  stop("Input file not found: ", input_file)
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

output_svg <- file.path(
  output_dir,
  "EDFigure1C_alpha_diversity.svg"
)

###############################################################################
# LOAD ALPHA-DIVERSITY RESULTS
###############################################################################

analysis_objects <- readRDS(input_file)

if (!is.list(analysis_objects)) {
  stop("The input RDS does not contain the expected list of analysis objects.")
}

if (!"alpha_diversity_with_design" %in% names(analysis_objects)) {
  stop(
    "Object 'alpha_diversity_with_design' was not found in the input RDS."
  )
}

alpha_data <- analysis_objects$alpha_diversity_with_design

required_columns <- c(
  "Sample",
  "treatment",
  "system",
  "sobs",
  "shannon",
  "evenness"
)

missing_columns <- setdiff(
  required_columns,
  names(alpha_data)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing required columns: ",
    paste(missing_columns, collapse = ", ")
  )
}

###############################################################################
# PREPARE PLOTTING DATA
###############################################################################

plot_data <- alpha_data |>
  dplyr::select(
    dplyr::all_of(required_columns)
  ) |>
  dplyr::filter(
    !is.na(.data$sobs),
    !is.na(.data$shannon),
    !is.na(.data$evenness)
  ) |>
  dplyr::mutate(
    treatment = factor(
      as.character(.data$treatment),
      levels = c(
        "Spatial",
        "Depth"
      ),
      labels = c(
        "Spatial profiling",
        "Deep profiling"
      )
    ),
    system = factor(
      as.character(.data$system),
      levels = c(
        "BM",
        "HV",
        "LM",
        "NR"
      )
    )
  )

if (anyNA(plot_data$treatment)) {
  stop(
    "Unexpected values were found in the treatment column."
  )
}

if (anyNA(plot_data$system)) {
  stop(
    "Unexpected values were found in the system column."
  )
}

plot_data_long <- plot_data |>
  tidyr::pivot_longer(
    cols = c(
      sobs,
      shannon,
      evenness
    ),
    names_to = "metric",
    values_to = "value"
  ) |>
  dplyr::mutate(
    metric = dplyr::recode(
      .data$metric,
      sobs = "Observed richness",
      shannon = "Shannon diversity",
      evenness = "Pielou evenness"
    ),
    metric = factor(
      .data$metric,
      levels = c(
        "Observed richness",
        "Shannon diversity",
        "Pielou evenness"
      )
    )
  )

###############################################################################
# PLOT
###############################################################################

profile_colors <- c(
  "Spatial profiling" = "#0072B2",
  "Deep profiling" = "#D55E00"
)

theme_figure <- ggplot2::theme_classic(
  base_size = 11
) +
  ggplot2::theme(
    panel.border = ggplot2::element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.35
    ),
    strip.background = ggplot2::element_rect(
      fill = "white",
      colour = NA
    ),
    strip.text = ggplot2::element_text(
      size = 15,
      face = "bold"
    ),
    axis.text.y = ggplot2::element_text(
      size = 12,
      colour = "black"
    ),
    axis.title.x = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    legend.position = "bottom",
    legend.title = ggplot2::element_blank(),
    legend.text = ggplot2::element_text(
      size = 12
    )
  )

p_alpha <- ggplot2::ggplot(
  plot_data_long,
  ggplot2::aes(
    x = .data$treatment,
    y = .data$value
  )
) +
  ggplot2::geom_boxplot(
    ggplot2::aes(
      fill = .data$treatment
    ),
    width = 0.62,
    outlier.shape = NA,
    colour = "black",
    alpha = 0.18,
    linewidth = 0.4
  ) +
  ggbeeswarm::geom_quasirandom(
    ggplot2::aes(
      colour = .data$treatment
    ),
    width = 0.18,
    size = 1.9,
    alpha = 0.9
  ) +
  ggplot2::facet_grid(
    metric ~ system,
    scales = "free_y"
  ) +
  ggplot2::scale_colour_manual(
    values = profile_colors
  ) +
  ggplot2::scale_fill_manual(
    values = profile_colors
  ) +
  ggplot2::labs(
    x = NULL,
    y = NULL
  ) +
  theme_figure

print(p_alpha)

###############################################################################
# SAVE FIGURE
###############################################################################

ggplot2::ggsave(
  filename = output_svg,
  plot = p_alpha,
  device = svglite::svglite,
  width = 7.2,
  height = 7.0,
  units = "in",
  bg = "white"
)

cat(
  "\nExtended Data Figure 1C saved to:\n",
  output_svg,
  "\n",
  sep = ""
)
